/**
 * Complete utility mapping from class name prefixes to CSS properties
 * Based on Panda CSS preset-base and preset-panda configurations
 *
 * @generated This file is auto-generated. Do not edit manually.
 * Run `npm run generate-mappings` to regenerate.
 * Generated on: 2025-08-25T21:53:50.205Z
 */

export const CLASS_TO_PROPERTY_MAP = new Map([
  ['ac', 'alignContent'],
  ['ac-c', 'accentColor'],
  ['ai', 'alignItems'],
  ['anim', 'animation'],
  ['anim-comp', 'animationComposition'],
  ['anim-dir', 'animationDirection'],
  ['anim-dly', 'animationDelay'],
  ['anim-dur', 'animationDuration'],
  ['anim-fm', 'animationFillMode'],
  ['anim-ic', 'animationIterationCount'],
  ['anim-n', 'animationName'],
  ['anim-ps', 'animationPlayState'],
  ['anim-r', 'animationRange'],
  ['anim-re', 'animationRangeEnd'],
  ['anim-rs', 'animationRangeStart'],
  ['anim-s', 'animationState'],
  ['anim-tl', 'animationTimeline'],
  ['anim-tmf', 'animationTimingFunction'],
  ['ap', 'appearance'],
  ['as', 'alignSelf'],
  ['asp', 'aspectRatio'],
  ['bd', 'border'],
  ['bd-b', 'borderBottom'],
  ['bd-b-c', 'borderBottomColor'],
  ['bd-b-w', 'borderBottomWidth'],
  ['bd-be', 'borderBlockEnd'],
  ['bd-be-c', 'borderBlockEndColor'],
  ['bd-be-w', 'borderBlockEndWidth'],
  ['bd-bs', 'borderBlockStart'],
  ['bd-bs-c', 'borderBlockStartColor'],
  ['bd-bs-w', 'borderBlockStartWidth'],
  ['bd-c', 'borderColor'],
  ['bd-cl', 'borderCollapse'],
  ['bd-e', 'borderInlineEnd'],
  ['bd-e-c', 'borderInlineEndColor'],
  ['bd-e-w', 'borderInlineEndWidth'],
  ['bd-l', 'borderLeft'],
  ['bd-l-c', 'borderLeftColor'],
  ['bd-l-w', 'borderLeftWidth'],
  ['bd-r', 'borderRight'],
  ['bd-r-c', 'borderRightColor'],
  ['bd-r-w', 'borderRightWidth'],
  ['bd-s', 'borderInlineStart'],
  ['bd-s-c', 'borderInlineStartColor'],
  ['bd-s-w', 'borderInlineStartWidth'],
  ['bd-sp', 'borderSpacing'],
  ['bd-sx', 'borderSpacingX'],
  ['bd-sy', 'borderSpacingY'],
  ['bd-t', 'borderTop'],
  ['bd-t-c', 'borderTopColor'],
  ['bd-t-w', 'borderTopWidth'],
  ['bd-w', 'borderWidth'],
  ['bd-x', 'borderInline'],
  ['bd-x-c', 'borderInlineColor'],
  ['bd-x-w', 'borderInlineWidth'],
  ['bd-y', 'borderBlock'],
  ['bd-y-c', 'borderBlockColor'],
  ['bd-y-w', 'borderBlockWidth'],
  ['bdr', 'borderRadius'],
  ['bdr-b', 'borderBottomRadius'],
  ['bdr-bl', 'borderBottomLeftRadius'],
  ['bdr-br', 'borderBottomRightRadius'],
  ['bdr-e', 'borderEndRadius'],
  ['bdr-ee', 'borderEndEndRadius'],
  ['bdr-es', 'borderEndStartRadius'],
  ['bdr-l', 'borderLeftRadius'],
  ['bdr-r', 'borderRightRadius'],
  ['bdr-s', 'borderStartRadius'],
  ['bdr-se', 'borderStartEndRadius'],
  ['bdr-ss', 'borderStartStartRadius'],
  ['bdr-t', 'borderTopRadius'],
  ['bdr-tl', 'borderTopLeftRadius'],
  ['bdr-tr', 'borderTopRightRadius'],
  ['bfv', 'backfaceVisibility'],
  ['bg', 'background'],
  ['bg-a', 'backgroundAttachment'],
  ['bg-bm', 'backgroundBlendMode'],
  ['bg-c', 'backgroundColor'],
  ['bg-conic', 'backgroundConic'],
  ['bg-cp', 'backgroundClip'],
  ['bg-grad', 'backgroundGradient'],
  ['bg-i', 'backgroundImage'],
  ['bg-linear', 'backgroundLinear'],
  ['bg-o', 'backgroundOrigin'],
  ['bg-p', 'backgroundPosition'],
  ['bg-p-x', 'backgroundPositionX'],
  ['bg-p-y', 'backgroundPositionY'],
  ['bg-r', 'backgroundRepeat'],
  ['bg-radial', 'backgroundRadial'],
  ['bg-s', 'backgroundSize'],
  ['bkdp', 'backdropFilter'],
  ['bkdp-blur', 'backdropBlur'],
  ['bkdp-brightness', 'backdropBrightness'],
  ['bkdp-contrast', 'backdropContrast'],
  ['bkdp-grayscale', 'backdropGrayscale'],
  ['bkdp-hue-rotate', 'backdropHueRotate'],
  ['bkdp-invert', 'backdropInvert'],
  ['bkdp-opacity', 'backdropOpacity'],
  ['bkdp-saturate', 'backdropSaturate'],
  ['bkdp-sepia', 'backdropSepia'],
  ['blur', 'blur'],
  ['bottom', 'bottom'],
  ['brightness', 'brightness'],
  ['bx-db', 'boxDecorationBreak'],
  ['bx-s', 'boxSizing'],
  ['bx-sh', 'boxShadow'],
  ['bx-sh-c', 'boxShadowColor'],
  ['c', 'color'],
  ['ca-c', 'caretColor'],
  ['cg', 'columnGap'],
  ['contrast', 'contrast'],
  ['cp-path', 'clipPath'],
  ['cq', 'container'],
  ['cq-n', 'containerName'],
  ['cq-t', 'containerType'],
  ['cursor', 'cursor'],
  ['d', 'display'],
  ['debug', 'debug'],
  ['drop-shadow', 'dropShadow'],
  ['dvd-c', 'divideColor'],
  ['dvd-s', 'divideStyle'],
  ['dvd-x', 'divideX'],
  ['dvd-y', 'divideY'],
  ['ff', 'fontFamily'],
  ['ff-s', 'fontFeatureSettings'],
  ['fill', 'fill'],
  ['filter', 'filter'],
  ['fk', 'fontKerning'],
  ['flex', 'flex'],
  ['flex-b', 'flexBasis'],
  ['flex-d', 'flexDirection'],
  ['flex-g', 'flexGrow'],
  ['flex-sh', 'flexShrink'],
  ['float', 'float'],
  ['focus-ring', 'focusRing'],
  ['focus-ring-c', 'focusRingColor'],
  ['focus-ring-o', 'focusRingOffset'],
  ['focus-ring-s', 'focusRingStyle'],
  ['focus-ring-w', 'focusRingWidth'],
  ['focus-v-ring', 'focusVisibleRing'],
  ['fp', 'fontPalette'],
  ['fs', 'fontSize'],
  ['fs-a', 'fontSizeAdjust'],
  ['fsmt', 'fontSmoothing'],
  ['fv', 'fontVariant'],
  ['fv-alt', 'fontVariantAlternates'],
  ['fv-caps', 'fontVariantCaps'],
  ['fv-num', 'fontVariantNumeric'],
  ['fv-s', 'fontVariationSettings'],
  ['fw', 'fontWeight'],
  ['gap', 'gap'],
  ['grad-from', 'gradientFrom'],
  ['grad-from-pos', 'gradientFromPosition'],
  ['grad-to', 'gradientTo'],
  ['grad-to-pos', 'gradientToPosition'],
  ['grad-via', 'gradientVia'],
  ['grad-via-pos', 'gradientViaPosition'],
  ['grayscale', 'grayscale'],
  ['grid-ac', 'gridAutoColumns'],
  ['grid-af', 'gridAutoFlow'],
  ['grid-ar', 'gridAutoRows'],
  ['grid-c', 'gridColumn'],
  ['grid-ce', 'gridColumnEnd'],
  ['grid-cg', 'gridColumnGap'],
  ['grid-cs', 'gridColumnStart'],
  ['grid-g', 'gridGap'],
  ['grid-r', 'gridRow'],
  ['grid-rg', 'gridRowGap'],
  ['grid-tc', 'gridTemplateColumns'],
  ['grid-tr', 'gridTemplateRows'],
  ['h', 'height'],
  ['h-bs', 'blockSize'],
  ['hide', 'hideFrom'],
  ['hue-rotate', 'hueRotate'],
  ['hy', 'hyphens'],
  ['inset', 'inset'],
  ['inset-be', 'insetBlockEnd'],
  ['inset-bs', 'insetBlockStart'],
  ['inset-e', 'insetInlineEnd'],
  ['inset-s', 'insetInlineStart'],
  ['inset-x', 'insetInline'],
  ['inset-y', 'insetBlock'],
  ['invert', 'invert'],
  ['jc', 'justifyContent'],
  ['lc', 'lineClamp'],
  ['left', 'left'],
  ['lh', 'lineHeight'],
  ['li-img', 'listStyleImage'],
  ['li-pos', 'listStylePosition'],
  ['li-s', 'listStyle'],
  ['li-t', 'listStyleType'],
  ['ls', 'letterSpacing'],
  ['m', 'margin'],
  ['max-b', 'maxBlockSize'],
  ['max-h', 'maxHeight'],
  ['max-w', 'maxWidth'],
  ['max-w-is', 'maxInlineSize'],
  ['mb', 'marginBottom'],
  ['mbe', 'marginBlockEnd'],
  ['mbs', 'marginBlockStart'],
  ['me', 'marginInlineEnd'],
  ['min-h', 'minHeight'],
  ['min-h-bs', 'minBlockSize'],
  ['min-w', 'minWidth'],
  ['min-w-is', 'minInlineSize'],
  ['mix-bm', 'mixBlendMode'],
  ['ml', 'marginLeft'],
  ['mr', 'marginRight'],
  ['ms', 'marginInlineStart'],
  ['msk', 'mask'],
  ['msk-i', 'maskImage'],
  ['msk-s', 'maskSize'],
  ['mt', 'marginTop'],
  ['mx', 'marginInline'],
  ['my', 'marginBlock'],
  ['obj-f', 'objectFit'],
  ['obj-p', 'objectPosition'],
  ['op', 'opacity'],
  ['ov', 'overflow'],
  ['ov-a', 'overflowAnchor'],
  ['ov-b', 'overflowBlock'],
  ['ov-i', 'overflowInline'],
  ['ov-wrap', 'overflowWrap'],
  ['ov-x', 'overflowX'],
  ['ov-y', 'overflowY'],
  ['ovcp-bx', 'overflowClipBox'],
  ['ovcp-m', 'overflowClipMargin'],
  ['ovs-b', 'overscrollBehavior'],
  ['ovs-bb', 'overscrollBehaviorBlock'],
  ['ovs-bi', 'overscrollBehaviorInline'],
  ['ovs-bx', 'overscrollBehaviorX'],
  ['ovs-by', 'overscrollBehaviorY'],
  ['p', 'padding'],
  ['pb', 'paddingBottom'],
  ['pbe', 'paddingBlockEnd'],
  ['pbs', 'paddingBlockStart'],
  ['pe', 'paddingInlineEnd'],
  ['pl', 'paddingLeft'],
  ['pos', 'position'],
  ['pr', 'paddingRight'],
  ['ps', 'paddingInlineStart'],
  ['pt', 'paddingTop'],
  ['px', 'paddingInline'],
  ['py', 'paddingBlock'],
  ['rg', 'rowGap'],
  ['right', 'right'],
  ['ring', 'outline'],
  ['ring-c', 'outlineColor'],
  ['ring-o', 'outlineOffset'],
  ['ring-w', 'outlineWidth'],
  ['rotate', 'rotate'],
  ['rotate-x', 'rotateX'],
  ['rotate-y', 'rotateY'],
  ['rotate-z', 'rotateZ'],
  ['saturate', 'saturate'],
  ['scale', 'scale'],
  ['scale-x', 'scaleX'],
  ['scale-y', 'scaleY'],
  ['scr-bar', 'scrollbar'],
  ['scr-bar-c', 'scrollbarColor'],
  ['scr-bar-g', 'scrollbarGutter'],
  ['scr-bar-w', 'scrollbarWidth'],
  ['scr-bhv', 'scrollBehavior'],
  ['scr-m', 'scrollMargin'],
  ['scr-mb', 'scrollMarginBottom'],
  ['scr-mbe', 'scrollMarginBlockEnd'],
  ['scr-mbt', 'scrollMarginBlockStart'],
  ['scr-me', 'scrollMarginInlineEnd'],
  ['scr-ml', 'scrollMarginLeft'],
  ['scr-mr', 'scrollMarginRight'],
  ['scr-ms', 'scrollMarginInlineStart'],
  ['scr-mt', 'scrollMarginTop'],
  ['scr-mx', 'scrollMarginInline'],
  ['scr-my', 'scrollMarginBlock'],
  ['scr-p', 'scrollPadding'],
  ['scr-pb', 'scrollPaddingBottom'],
  ['scr-pbe', 'scrollPaddingBlockEnd'],
  ['scr-pbs', 'scrollPaddingBlockStart'],
  ['scr-pe', 'scrollPaddingInlineEnd'],
  ['scr-pl', 'scrollPaddingLeft'],
  ['scr-pr', 'scrollPaddingRight'],
  ['scr-ps', 'scrollPaddingInlineStart'],
  ['scr-pt', 'scrollPaddingTop'],
  ['scr-px', 'scrollPaddingInline'],
  ['scr-py', 'scrollPaddingBlock'],
  ['scr-sa', 'scrollSnapAlign'],
  ['scrs-c', 'scrollSnapCoordinate'],
  ['scrs-d', 'scrollSnapDestination'],
  ['scrs-m', 'scrollSnapMargin'],
  ['scrs-mb', 'scrollSnapMarginBottom'],
  ['scrs-ml', 'scrollSnapMarginLeft'],
  ['scrs-mr', 'scrollSnapMarginRight'],
  ['scrs-mt', 'scrollSnapMarginTop'],
  ['scrs-px', 'scrollSnapPointsX'],
  ['scrs-py', 'scrollSnapPointsY'],
  ['scrs-s', 'scrollSnapStop'],
  ['scrs-strt', 'scrollSnapStrictness'],
  ['scrs-t', 'scrollSnapType'],
  ['scrs-tx', 'scrollSnapTypeX'],
  ['scrs-ty', 'scrollSnapTypeY'],
  ['scrtl', 'scrollTimeline'],
  ['scrtl-a', 'scrollTimelineAxis'],
  ['scrtl-n', 'scrollTimelineName'],
  ['sepia', 'sepia'],
  ['show', 'hideBelow'],
  ['size', 'boxSize'],
  ['sr', 'srOnly'],
  ['stk', 'stroke'],
  ['stk-do', 'strokeDashoffset'],
  ['stk-dsh', 'strokeDasharray'],
  ['stk-lc', 'strokeLinecap'],
  ['stk-lj', 'strokeLinejoin'],
  ['stk-ml', 'strokeMiterlimit'],
  ['stk-op', 'strokeOpacity'],
  ['stk-w', 'strokeWidth'],
  ['sx', 'spaceX'],
  ['sy', 'spaceY'],
  ['ta', 'textAlign'],
  ['tbl', 'tableLayout'],
  ['tch-a', 'touchAction'],
  ['td', 'textDecoration'],
  ['td-c', 'textDecorationColor'],
  ['td-s', 'textDecorationStyle'],
  ['td-t', 'textDecorationThickness'],
  ['te-c', 'textEmphasisColor'],
  ['ti', 'textIndent'],
  ['top', 'top'],
  ['tov', 'textOverflow'],
  ['translate', 'translate'],
  ['translate-x', 'translateX'],
  ['translate-y', 'translateY'],
  ['translate-z', 'translateZ'],
  ['trf', 'transform'],
  ['trf-b', 'transformBox'],
  ['trf-o', 'transformOrigin'],
  ['trf-s', 'transformStyle'],
  ['trs', 'transition'],
  ['trs-dly', 'transitionDelay'],
  ['trs-dur', 'transitionDuration'],
  ['trs-prop', 'transitionProperty'],
  ['trs-tmf', 'transitionTimingFunction'],
  ['trunc', 'truncate'],
  ['tsh', 'textShadow'],
  ['tsh-c', 'textShadowColor'],
  ['tt', 'textTransform'],
  ['tu-o', 'textUnderlineOffset'],
  ['tw', 'textWrap'],
  ['txt-adj', 'textSizeAdjust'],
  ['txt-grad', 'textGradient'],
  ['us', 'userSelect'],
  ['va', 'verticalAlign'],
  ['vis', 'visibility'],
  ['w', 'width'],
  ['w-is', 'inlineSize'],
  ['wb', 'wordBreak'],
  ['z', 'zIndex'],
])

/**
 * Shorthand property aliases
 */
export const SHORTHAND_ALIASES = new Map([
  ['bg', 'background'],
  ['bgAttachment', 'backgroundAttachment'],
  ['bgBlendMode', 'backgroundBlendMode'],
  ['bgClip', 'backgroundClip'],
  ['bgColor', 'backgroundColor'],
  ['bgConic', 'backgroundConic'],
  ['bgGradient', 'backgroundGradient'],
  ['bgImage', 'backgroundImage'],
  ['bgLinear', 'backgroundLinear'],
  ['bgOrigin', 'backgroundOrigin'],
  ['bgPosition', 'backgroundPosition'],
  ['bgPositionX', 'backgroundPositionX'],
  ['bgPositionY', 'backgroundPositionY'],
  ['bgRadial', 'backgroundRadial'],
  ['bgRepeat', 'backgroundRepeat'],
  ['bgSize', 'backgroundSize'],
  ['borderEnd', 'borderInlineEnd'],
  ['borderEndColor', 'borderInlineEndColor'],
  ['borderEndWidth', 'borderInlineEndWidth'],
  ['borderStart', 'borderInlineStart'],
  ['borderStartColor', 'borderInlineStartColor'],
  ['borderStartWidth', 'borderInlineStartWidth'],
  ['borderX', 'borderInline'],
  ['borderXColor', 'borderInlineColor'],
  ['borderXWidth', 'borderInlineWidth'],
  ['borderY', 'borderBlock'],
  ['borderYColor', 'borderBlockColor'],
  ['borderYWidth', 'borderBlockWidth'],
  ['end', 'insetInlineEnd'],
  ['flexDir', 'flexDirection'],
  ['h', 'height'],
  ['insetEnd', 'insetInlineEnd'],
  ['insetStart', 'insetInlineStart'],
  ['insetX', 'insetInline'],
  ['insetY', 'insetBlock'],
  ['m', 'margin'],
  ['marginEnd', 'marginInlineEnd'],
  ['marginStart', 'marginInlineStart'],
  ['marginX', 'marginInline'],
  ['marginY', 'marginBlock'],
  ['maxH', 'maxHeight'],
  ['maxW', 'maxWidth'],
  ['mb', 'marginBottom'],
  ['me', 'marginInlineEnd'],
  ['minH', 'minHeight'],
  ['minW', 'minWidth'],
  ['ml', 'marginLeft'],
  ['mr', 'marginRight'],
  ['ms', 'marginInlineStart'],
  ['mt', 'marginTop'],
  ['mx', 'marginInline'],
  ['my', 'marginBlock'],
  ['p', 'padding'],
  ['paddingEnd', 'paddingInlineEnd'],
  ['paddingStart', 'paddingInlineStart'],
  ['paddingX', 'paddingInline'],
  ['paddingY', 'paddingBlock'],
  ['pb', 'paddingBottom'],
  ['pe', 'paddingInlineEnd'],
  ['pl', 'paddingLeft'],
  ['pos', 'position'],
  ['pr', 'paddingRight'],
  ['ps', 'paddingInlineStart'],
  ['pt', 'paddingTop'],
  ['px', 'paddingInline'],
  ['py', 'paddingBlock'],
  ['ring', 'outline'],
  ['ringColor', 'outlineColor'],
  ['ringOffset', 'outlineOffset'],
  ['ringWidth', 'outlineWidth'],
  ['rounded', 'borderRadius'],
  ['roundedBottom', 'borderBottomRadius'],
  ['roundedBottomLeft', 'borderBottomLeftRadius'],
  ['roundedBottomRight', 'borderBottomRightRadius'],
  ['roundedEnd', 'borderEndRadius'],
  ['roundedEndEnd', 'borderEndEndRadius'],
  ['roundedEndStart', 'borderEndStartRadius'],
  ['roundedLeft', 'borderLeftRadius'],
  ['roundedRight', 'borderRightRadius'],
  ['roundedStart', 'borderStartRadius'],
  ['roundedStartEnd', 'borderStartEndRadius'],
  ['roundedStartStart', 'borderStartStartRadius'],
  ['roundedTop', 'borderTopRadius'],
  ['roundedTopLeft', 'borderTopLeftRadius'],
  ['roundedTopRight', 'borderTopRightRadius'],
  ['scrollMarginX', 'scrollMarginInline'],
  ['scrollMarginY', 'scrollMarginBlock'],
  ['scrollPaddingX', 'scrollPaddingInline'],
  ['scrollPaddingY', 'scrollPaddingBlock'],
  ['shadow', 'boxShadow'],
  ['shadowColor', 'boxShadowColor'],
  ['start', 'insetInlineStart'],
  ['textShadowColor', 'textShadowColor'],
  ['w', 'width'],
  ['x', 'translateX'],
  ['y', 'translateY'],
  ['z', 'translateZ'],
])

/**
 * Breakpoints and condition mapping
 */
export const CONDITION_MAP = new Map([
  ['2xl', '2xl'],
  ['active', '_active'],
  ['after', '_after'],
  ['atValue', '_atValue'],
  ['autofill', '_autofill'],
  ['backdrop', '_backdrop'],
  ['base', 'base'],
  ['before', '_before'],
  ['checked', '_checked'],
  ['closed', '_closed'],
  ['complete', '_complete'],
  ['current', '_current'],
  ['currentPage', '_currentPage'],
  ['currentStep', '_currentStep'],
  ['dark', '_dark'],
  ['default', '_default'],
  ['disabled', '_disabled'],
  ['dragging', '_dragging'],
  ['empty', '_empty'],
  ['enabled', '_enabled'],
  ['even', '_even'],
  ['expanded', '_expanded'],
  ['file', '_file'],
  ['first', '_first'],
  ['firstLetter', '_firstLetter'],
  ['firstLine', '_firstLine'],
  ['firstOfType', '_firstOfType'],
  ['focus', '_focus'],
  ['focusVisible', '_focusVisible'],
  ['focusWithin', '_focusWithin'],
  ['fullscreen', '_fullscreen'],
  ['grabbed', '_grabbed'],
  ['groupActive', '_groupActive'],
  ['groupChecked', '_groupChecked'],
  ['groupDisabled', '_groupDisabled'],
  ['groupExpanded', '_groupExpanded'],
  ['groupFocus', '_groupFocus'],
  ['groupFocusVisible', '_groupFocusVisible'],
  ['groupFocusWithin', '_groupFocusWithin'],
  ['groupHover', '_groupHover'],
  ['groupInvalid', '_groupInvalid'],
  ['hidden', '_hidden'],
  ['highContrast', '_highContrast'],
  ['highlighted', '_highlighted'],
  ['horizontal', '_horizontal'],
  ['hover', '_hover'],
  ['icon', '_icon'],
  ['incomplete', '_incomplete'],
  ['indeterminate', '_indeterminate'],
  ['inRange', '_inRange'],
  ['invalid', '_invalid'],
  ['invertedColors', '_invertedColors'],
  ['landscape', '_landscape'],
  ['last', '_last'],
  ['lastOfType', '_lastOfType'],
  ['lessContrast', '_lessContrast'],
  ['lg', 'lg'],
  ['light', '_light'],
  ['loading', '_loading'],
  ['ltr', '_ltr'],
  ['marker', '_marker'],
  ['md', 'md'],
  ['moreContrast', '_moreContrast'],
  ['motionReduce', '_motionReduce'],
  ['motionSafe', '_motionSafe'],
  ['noscript', '_noscript'],
  ['now', '_now'],
  ['odd', '_odd'],
  ['only', '_only'],
  ['onlyOfType', '_onlyOfType'],
  ['open', '_open'],
  ['optional', '_optional'],
  ['osDark', '_osDark'],
  ['osLight', '_osLight'],
  ['outOfRange', '_outOfRange'],
  ['overValue', '_overValue'],
  ['peerActive', '_peerActive'],
  ['peerChecked', '_peerChecked'],
  ['peerDisabled', '_peerDisabled'],
  ['peerExpanded', '_peerExpanded'],
  ['peerFocus', '_peerFocus'],
  ['peerFocusVisible', '_peerFocusVisible'],
  ['peerFocusWithin', '_peerFocusWithin'],
  ['peerHover', '_peerHover'],
  ['peerInvalid', '_peerInvalid'],
  ['peerPlaceholderShown', '_peerPlaceholderShown'],
  ['placeholder', '_placeholder'],
  ['placeholderShown', '_placeholderShown'],
  ['portrait', '_portrait'],
  ['pressed', '_pressed'],
  ['print', '_print'],
  ['rangeEnd', '_rangeEnd'],
  ['rangeStart', '_rangeStart'],
  ['readOnly', '_readOnly'],
  ['readWrite', '_readWrite'],
  ['required', '_required'],
  ['rtl', '_rtl'],
  ['scrollbar', '_scrollbar'],
  ['scrollbarThumb', '_scrollbarThumb'],
  ['scrollbarTrack', '_scrollbarTrack'],
  ['selected', '_selected'],
  ['selection', '_selection'],
  ['sm', 'sm'],
  ['starting', '_starting'],
  ['target', '_target'],
  ['today', '_today'],
  ['topmost', '_topmost'],
  ['unavailable', '_unavailable'],
  ['underValue', '_underValue'],
  ['valid', '_valid'],
  ['vertical', '_vertical'],
  ['visited', '_visited'],
  ['xl', 'xl'],
])

/**
 * Property to token category mapping
 * Based on Panda CSS preset-panda theme configuration
 */
export const PROPERTY_TO_TOKEN_CATEGORY: Record<string, string> = {
  accentColor: 'colors',
  backgroundColor: 'colors',
  blockSize: 'sizes',
  borderBlockEndWidth: 'spacing',
  borderBlockStartWidth: 'spacing',
  borderBlockWidth: 'spacing',
  borderBottomLeftRadius: 'radii',
  borderBottomRightRadius: 'radii',
  borderBottomWidth: 'spacing',
  borderColor: 'colors',
  borderEndEndRadius: 'radii',
  borderEndStartRadius: 'radii',
  borderInlineEndWidth: 'spacing',
  borderInlineStartWidth: 'spacing',
  borderInlineWidth: 'spacing',
  borderLeftWidth: 'spacing',
  borderRadius: 'radii',
  borderRightWidth: 'spacing',
  borderStartEndRadius: 'radii',
  borderStartStartRadius: 'radii',
  borderTopLeftRadius: 'radii',
  borderTopRightRadius: 'radii',
  borderTopWidth: 'spacing',
  borderWidth: 'spacing',
  boxShadow: 'shadows',
  caretColor: 'colors',
  color: 'colors',
  columnGap: 'spacing',
  dropShadow: 'shadows',
  fontFamily: 'fonts',
  fontSize: 'fontSizes',
  fontWeight: 'fontWeights',
  gap: 'spacing',
  height: 'sizes',
  inlineSize: 'sizes',
  letterSpacing: 'letterSpacings',
  lineHeight: 'lineHeights',
  margin: 'spacing',
  marginBlock: 'spacing',
  marginBlockEnd: 'spacing',
  marginBlockStart: 'spacing',
  marginBottom: 'spacing',
  marginInline: 'spacing',
  marginInlineEnd: 'spacing',
  marginInlineStart: 'spacing',
  marginLeft: 'spacing',
  marginRight: 'spacing',
  marginTop: 'spacing',
  maxBlockSize: 'sizes',
  maxHeight: 'sizes',
  maxInlineSize: 'sizes',
  maxWidth: 'sizes',
  minBlockSize: 'sizes',
  minHeight: 'sizes',
  minInlineSize: 'sizes',
  minWidth: 'sizes',
  outlineColor: 'colors',
  outlineOffset: 'spacing',
  outlineWidth: 'spacing',
  padding: 'spacing',
  paddingBlock: 'spacing',
  paddingBlockEnd: 'spacing',
  paddingBlockStart: 'spacing',
  paddingBottom: 'spacing',
  paddingInline: 'spacing',
  paddingInlineEnd: 'spacing',
  paddingInlineStart: 'spacing',
  paddingLeft: 'spacing',
  paddingRight: 'spacing',
  paddingTop: 'spacing',
  rowGap: 'spacing',
  scrollbarColor: 'colors',
  spaceX: 'spacing',
  spaceY: 'spacing',
  textDecorationColor: 'colors',
  textShadow: 'shadows',
  width: 'sizes',
  zIndex: 'zIndex',
}

/**
 * Default breakpoints from Panda CSS preset
 */
export const DEFAULT_BREAKPOINTS = {
  sm: '640px',
  md: '768px',
  lg: '1024px',
  xl: '1280px',
  '2xl': '1536px',
} as const

/**
 * Default conditions from Panda CSS preset
 */
export const DEFAULT_CONDITIONS = {
  hover: '&:is(:hover, [data-hover])',
  focus: '&:is(:focus, [data-focus])',
  focusWithin: '&:focus-within',
  focusVisible: '&:is(:focus-visible, [data-focus-visible])',
  disabled: '&:is(:disabled, [disabled], [data-disabled], [aria-disabled=true])',
  active: '&:is(:active, [data-active])',
  visited: '&:visited',
  target: '&:target',
  readOnly: '&:is(:read-only, [data-read-only], [aria-readonly=true])',
  readWrite: '&:read-write',
  empty: '&:is(:empty, [data-empty])',
  checked: '&:is(:checked, [data-checked], [aria-checked=true], [data-state="checked"])',
  enabled: '&:enabled',
  expanded: '&:is([aria-expanded=true], [data-expanded], [data-state="expanded"])',
  highlighted: '&[data-highlighted]',
  complete: '&[data-complete]',
  incomplete: '&[data-incomplete]',
  dragging: '&[data-dragging]',
  before: '&::before',
  after: '&::after',
  firstLetter: '&::first-letter',
  firstLine: '&::first-line',
  marker: '&:is(::marker, ::-webkit-details-marker)',
  selection: '&::selection',
  file: '&::file-selector-button',
  backdrop: '&::backdrop',
  first: '&:first-child',
  last: '&:last-child',
  only: '&:only-child',
  even: '&:nth-child(even)',
  odd: '&:nth-child(odd)',
  firstOfType: '&:first-of-type',
  lastOfType: '&:last-of-type',
  onlyOfType: '&:only-of-type',
  peerFocus: '.peer:is(:focus, [data-focus]) ~ &',
  peerHover: '.peer:is(:hover, [data-hover]) ~ &',
  peerActive: '.peer:is(:active, [data-active]) ~ &',
  peerFocusWithin: '.peer:focus-within ~ &',
  peerFocusVisible: '.peer:is(:focus-visible, [data-focus-visible]) ~ &',
  peerDisabled: '.peer:is(:disabled, [disabled], [data-disabled], [aria-disabled=true]) ~ &',
  peerChecked: '.peer:is(:checked, [data-checked], [aria-checked=true], [data-state="checked"]) ~ &',
  peerInvalid: '.peer:is(:invalid, [data-invalid], [aria-invalid=true]) ~ &',
  peerExpanded: '.peer:is([aria-expanded=true], [data-expanded], [data-state="expanded"]) ~ &',
  peerPlaceholderShown: '.peer:placeholder-shown ~ &',
  groupFocus: '.group:is(:focus, [data-focus]) &',
  groupHover: '.group:is(:hover, [data-hover]) &',
  groupActive: '.group:is(:active, [data-active]) &',
  groupFocusWithin: '.group:focus-within &',
  groupFocusVisible: '.group:is(:focus-visible, [data-focus-visible]) &',
  groupDisabled: '.group:is(:disabled, [disabled], [data-disabled], [aria-disabled=true]) &',
  groupChecked: '.group:is(:checked, [data-checked], [aria-checked=true], [data-state="checked"]) &',
  groupExpanded: '.group:is([aria-expanded=true], [data-expanded], [data-state="expanded"]) &',
  groupInvalid: '.group:is(:invalid, [data-invalid], [aria-invalid=true]) &',
  indeterminate: '&:is(:indeterminate, [data-indeterminate], [aria-checked=mixed], [data-state="indeterminate"])',
  required: '&:is(:required, [data-required], [aria-required=true])',
  valid: '&:is(:valid, [data-valid])',
  invalid: '&:is(:invalid, [data-invalid], [aria-invalid=true])',
  autofill: '&:autofill',
  inRange: '&:is(:in-range, [data-in-range])',
  outOfRange: '&:is(:out-of-range, [data-outside-range])',
  placeholder: '&::placeholder, &[data-placeholder]',
  placeholderShown: '&:is(:placeholder-shown, [data-placeholder-shown])',
  pressed: '&:is([aria-pressed=true], [data-pressed])',
  selected: '&:is([aria-selected=true], [data-selected])',
  grabbed: '&:is([aria-grabbed=true], [data-grabbed])',
  underValue: '&[data-state=under-value]',
  overValue: '&[data-state=over-value]',
  atValue: '&[data-state=at-value]',
  default: '&:default',
  optional: '&:optional',
  open: '&:is([open], [data-open], [data-state="open"], :popover-open)',
  closed: '&:is([closed], [data-closed], [data-state="closed"])',
  fullscreen: '&:is(:fullscreen, [data-fullscreen])',
  loading: '&:is([data-loading], [aria-busy=true])',
  hidden: '&:is([hidden], [data-hidden])',
  current: '&:is([aria-current=true], [data-current])',
  currentPage: '&[aria-current=page]',
  currentStep: '&[aria-current=step]',
  today: '&[data-today]',
  unavailable: '&[data-unavailable]',
  rangeStart: '&[data-range-start]',
  rangeEnd: '&[data-range-end]',
  now: '&[data-now]',
  topmost: '&[data-topmost]',
  motionReduce: '@media (prefers-reduced-motion: reduce)',
  motionSafe: '@media (prefers-reduced-motion: no-preference)',
  print: '@media print',
  landscape: '@media (orientation: landscape)',
  portrait: '@media (orientation: portrait)',
  dark: '.dark &',
  light: '.light &',
  osDark: '@media (prefers-color-scheme: dark)',
  osLight: '@media (prefers-color-scheme: light)',
  highContrast: '@media (forced-colors: active)',
  lessContrast: '@media (prefers-contrast: less)',
  moreContrast: '@media (prefers-contrast: more)',
  ltr: ':where([dir=ltr], :dir(ltr)) &',
  rtl: ':where([dir=rtl], :dir(rtl)) &',
  scrollbar: '&::-webkit-scrollbar',
  scrollbarThumb: '&::-webkit-scrollbar-thumb',
  scrollbarTrack: '&::-webkit-scrollbar-track',
  horizontal: '&[data-orientation=horizontal]',
  vertical: '&[data-orientation=vertical]',
  icon: '& :where(svg)',
  starting: '@starting-style',
  noscript: '@media (scripting: none)',
  invertedColors: '@media (inverted-colors: inverted)',
} as const

/**
 * Default tokens from Panda CSS preset
 */
export const DEFAULT_TOKENS = {
  colors: {
    current: 'currentColor',
    black: '#000',
    white: '#fff',
    transparent: 'rgb(0 0 0 / 0)',
    'rose.50': '#fff1f2',
    'rose.100': '#ffe4e6',
    'rose.200': '#fecdd3',
    'rose.300': '#fda4af',
    'rose.400': '#fb7185',
    'rose.500': '#f43f5e',
    'rose.600': '#e11d48',
    'rose.700': '#be123c',
    'rose.800': '#9f1239',
    'rose.900': '#881337',
    'rose.950': '#4c0519',
    'pink.50': '#fdf2f8',
    'pink.100': '#fce7f3',
    'pink.200': '#fbcfe8',
    'pink.300': '#f9a8d4',
    'pink.400': '#f472b6',
    'pink.500': '#ec4899',
    'pink.600': '#db2777',
    'pink.700': '#be185d',
    'pink.800': '#9d174d',
    'pink.900': '#831843',
    'pink.950': '#500724',
    'fuchsia.50': '#fdf4ff',
    'fuchsia.100': '#fae8ff',
    'fuchsia.200': '#f5d0fe',
    'fuchsia.300': '#f0abfc',
    'fuchsia.400': '#e879f9',
    'fuchsia.500': '#d946ef',
    'fuchsia.600': '#c026d3',
    'fuchsia.700': '#a21caf',
    'fuchsia.800': '#86198f',
    'fuchsia.900': '#701a75',
    'fuchsia.950': '#4a044e',
    'purple.50': '#faf5ff',
    'purple.100': '#f3e8ff',
    'purple.200': '#e9d5ff',
    'purple.300': '#d8b4fe',
    'purple.400': '#c084fc',
    'purple.500': '#a855f7',
    'purple.600': '#9333ea',
    'purple.700': '#7e22ce',
    'purple.800': '#6b21a8',
    'purple.900': '#581c87',
    'purple.950': '#3b0764',
    'violet.50': '#f5f3ff',
    'violet.100': '#ede9fe',
    'violet.200': '#ddd6fe',
    'violet.300': '#c4b5fd',
    'violet.400': '#a78bfa',
    'violet.500': '#8b5cf6',
    'violet.600': '#7c3aed',
    'violet.700': '#6d28d9',
    'violet.800': '#5b21b6',
    'violet.900': '#4c1d95',
    'violet.950': '#2e1065',
    'indigo.50': '#eef2ff',
    'indigo.100': '#e0e7ff',
    'indigo.200': '#c7d2fe',
    'indigo.300': '#a5b4fc',
    'indigo.400': '#818cf8',
    'indigo.500': '#6366f1',
    'indigo.600': '#4f46e5',
    'indigo.700': '#4338ca',
    'indigo.800': '#3730a3',
    'indigo.900': '#312e81',
    'indigo.950': '#1e1b4b',
    'blue.50': '#eff6ff',
    'blue.100': '#dbeafe',
    'blue.200': '#bfdbfe',
    'blue.300': '#93c5fd',
    'blue.400': '#60a5fa',
    'blue.500': '#3b82f6',
    'blue.600': '#2563eb',
    'blue.700': '#1d4ed8',
    'blue.800': '#1e40af',
    'blue.900': '#1e3a8a',
    'blue.950': '#172554',
    'sky.50': '#f0f9ff',
    'sky.100': '#e0f2fe',
    'sky.200': '#bae6fd',
    'sky.300': '#7dd3fc',
    'sky.400': '#38bdf8',
    'sky.500': '#0ea5e9',
    'sky.600': '#0284c7',
    'sky.700': '#0369a1',
    'sky.800': '#075985',
    'sky.900': '#0c4a6e',
    'sky.950': '#082f49',
    'cyan.50': '#ecfeff',
    'cyan.100': '#cffafe',
    'cyan.200': '#a5f3fc',
    'cyan.300': '#67e8f9',
    'cyan.400': '#22d3ee',
    'cyan.500': '#06b6d4',
    'cyan.600': '#0891b2',
    'cyan.700': '#0e7490',
    'cyan.800': '#155e75',
    'cyan.900': '#164e63',
    'cyan.950': '#083344',
    'teal.50': '#f0fdfa',
    'teal.100': '#ccfbf1',
    'teal.200': '#99f6e4',
    'teal.300': '#5eead4',
    'teal.400': '#2dd4bf',
    'teal.500': '#14b8a6',
    'teal.600': '#0d9488',
    'teal.700': '#0f766e',
    'teal.800': '#115e59',
    'teal.900': '#134e4a',
    'teal.950': '#042f2e',
    'emerald.50': '#ecfdf5',
    'emerald.100': '#d1fae5',
    'emerald.200': '#a7f3d0',
    'emerald.300': '#6ee7b7',
    'emerald.400': '#34d399',
    'emerald.500': '#10b981',
    'emerald.600': '#059669',
    'emerald.700': '#047857',
    'emerald.800': '#065f46',
    'emerald.900': '#064e3b',
    'emerald.950': '#022c22',
    'green.50': '#f0fdf4',
    'green.100': '#dcfce7',
    'green.200': '#bbf7d0',
    'green.300': '#86efac',
    'green.400': '#4ade80',
    'green.500': '#22c55e',
    'green.600': '#16a34a',
    'green.700': '#15803d',
    'green.800': '#166534',
    'green.900': '#14532d',
    'green.950': '#052e16',
    'lime.50': '#f7fee7',
    'lime.100': '#ecfccb',
    'lime.200': '#d9f99d',
    'lime.300': '#bef264',
    'lime.400': '#a3e635',
    'lime.500': '#84cc16',
    'lime.600': '#65a30d',
    'lime.700': '#4d7c0f',
    'lime.800': '#3f6212',
    'lime.900': '#365314',
    'lime.950': '#1a2e05',
    'yellow.50': '#fefce8',
    'yellow.100': '#fef9c3',
    'yellow.200': '#fef08a',
    'yellow.300': '#fde047',
    'yellow.400': '#facc15',
    'yellow.500': '#eab308',
    'yellow.600': '#ca8a04',
    'yellow.700': '#a16207',
    'yellow.800': '#854d0e',
    'yellow.900': '#713f12',
    'yellow.950': '#422006',
    'amber.50': '#fffbeb',
    'amber.100': '#fef3c7',
    'amber.200': '#fde68a',
    'amber.300': '#fcd34d',
    'amber.400': '#fbbf24',
    'amber.500': '#f59e0b',
    'amber.600': '#d97706',
    'amber.700': '#b45309',
    'amber.800': '#92400e',
    'amber.900': '#78350f',
    'amber.950': '#451a03',
    'orange.50': '#fff7ed',
    'orange.100': '#ffedd5',
    'orange.200': '#fed7aa',
    'orange.300': '#fdba74',
    'orange.400': '#fb923c',
    'orange.500': '#f97316',
    'orange.600': '#ea580c',
    'orange.700': '#c2410c',
    'orange.800': '#9a3412',
    'orange.900': '#7c2d12',
    'orange.950': '#431407',
    'red.50': '#fef2f2',
    'red.100': '#fee2e2',
    'red.200': '#fecaca',
    'red.300': '#fca5a5',
    'red.400': '#f87171',
    'red.500': '#ef4444',
    'red.600': '#dc2626',
    'red.700': '#b91c1c',
    'red.800': '#991b1b',
    'red.900': '#7f1d1d',
    'red.950': '#450a0a',
    'neutral.50': '#fafafa',
    'neutral.100': '#f5f5f5',
    'neutral.200': '#e5e5e5',
    'neutral.300': '#d4d4d4',
    'neutral.400': '#a3a3a3',
    'neutral.500': '#737373',
    'neutral.600': '#525252',
    'neutral.700': '#404040',
    'neutral.800': '#262626',
    'neutral.900': '#171717',
    'neutral.950': '#0a0a0a',
    'stone.50': '#fafaf9',
    'stone.100': '#f5f5f4',
    'stone.200': '#e7e5e4',
    'stone.300': '#d6d3d1',
    'stone.400': '#a8a29e',
    'stone.500': '#78716c',
    'stone.600': '#57534e',
    'stone.700': '#44403c',
    'stone.800': '#292524',
    'stone.900': '#1c1917',
    'stone.950': '#0c0a09',
    'zinc.50': '#fafafa',
    'zinc.100': '#f4f4f5',
    'zinc.200': '#e4e4e7',
    'zinc.300': '#d4d4d8',
    'zinc.400': '#a1a1aa',
    'zinc.500': '#71717a',
    'zinc.600': '#52525b',
    'zinc.700': '#3f3f46',
    'zinc.800': '#27272a',
    'zinc.900': '#18181b',
    'zinc.950': '#09090b',
    'gray.50': '#f9fafb',
    'gray.100': '#f3f4f6',
    'gray.200': '#e5e7eb',
    'gray.300': '#d1d5db',
    'gray.400': '#9ca3af',
    'gray.500': '#6b7280',
    'gray.600': '#4b5563',
    'gray.700': '#374151',
    'gray.800': '#1f2937',
    'gray.900': '#111827',
    'gray.950': '#030712',
    'slate.50': '#f8fafc',
    'slate.100': '#f1f5f9',
    'slate.200': '#e2e8f0',
    'slate.300': '#cbd5e1',
    'slate.400': '#94a3b8',
    'slate.500': '#64748b',
    'slate.600': '#475569',
    'slate.700': '#334155',
    'slate.800': '#1e293b',
    'slate.900': '#0f172a',
    'slate.950': '#020617',
  },
  spacing: {
    '0': '0rem',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '7': '1.75rem',
    '8': '2rem',
    '9': '2.25rem',
    '10': '2.5rem',
    '11': '2.75rem',
    '12': '3rem',
    '13': '3.25rem',
    '14': '3.5rem',
    '15': '3.75rem',
    '16': '4rem',
    '17': '4.25rem',
    '18': '4.5rem',
    '19': '4.75rem',
    '20': '5rem',
    '21': '5.25rem',
    '22': '5.5rem',
    '23': '5.75rem',
    '24': '6rem',
    '28': '7rem',
    '32': '8rem',
    '36': '9rem',
    '40': '10rem',
    '44': '11rem',
    '48': '12rem',
    '52': '13rem',
    '56': '14rem',
    '60': '15rem',
    '64': '16rem',
    '72': '18rem',
    '80': '20rem',
    '96': '24rem',
    '0.5': '0.125rem',
    '1.5': '0.375rem',
    '2.5': '0.625rem',
    '3.5': '0.875rem',
    '-0.5': '-0.125rem',
    '-1': '-0.25rem',
    '-1.5': '-0.375rem',
    '-2': '-0.5rem',
    '-2.5': '-0.625rem',
    '-3': '-0.75rem',
    '-3.5': '-0.875rem',
    '-4': '-1rem',
    '-5': '-1.25rem',
    '-6': '-1.5rem',
    '-7': '-1.75rem',
    '-8': '-2rem',
    '-9': '-2.25rem',
    '-10': '-2.5rem',
    '-11': '-2.75rem',
    '-12': '-3rem',
    '-14': '-3.5rem',
    '-16': '-4rem',
    '-20': '-5rem',
    '-24': '-6rem',
    '-28': '-7rem',
    '-32': '-8rem',
    '-36': '-9rem',
    '-40': '-10rem',
    '-44': '-11rem',
    '-48': '-12rem',
    '-52': '-13rem',
    '-56': '-14rem',
    '-60': '-15rem',
    '-64': '-16rem',
    '-72': '-18rem',
    '-80': '-20rem',
    '-96': '-24rem',
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    '1/5': '20%',
    '2/5': '40%',
    '3/5': '60%',
    '4/5': '80%',
    '1/6': '16.666667%',
    '2/6': '33.333333%',
    '3/6': '50%',
    '4/6': '66.666667%',
    '5/6': '83.333333%',
    '1/12': '8.333333%',
    '2/12': '16.666667%',
    '3/12': '25%',
    '4/12': '33.333333%',
    '5/12': '41.666667%',
    '6/12': '50%',
    '7/12': '58.333333%',
    '8/12': '66.666667%',
    '9/12': '75%',
    '10/12': '83.333333%',
    '11/12': '91.666667%',
    px: '1px',
  },
  fonts: {
    sans: 'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
    serif: 'ui-serif, Georgia, Cambria, "Times New Roman", Times, serif',
    mono: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  fontSizes: {
    '2xs': '0.5rem',
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '3.75rem',
    '7xl': '4.5rem',
    '8xl': '6rem',
    '9xl': '8rem',
  },
  fontWeights: {
    thin: '100',
    extralight: '200',
    light: '300',
    normal: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
    extrabold: '800',
    black: '900',
  },
  lineHeights: {
    none: '1',
    tight: '1.25',
    snug: '1.375',
    normal: '1.5',
    relaxed: '1.625',
    loose: '2',
  },
  letterSpacings: {
    tighter: '-0.05em',
    tight: '-0.025em',
    normal: '0em',
    wide: '0.025em',
    wider: '0.05em',
    widest: '0.1em',
  },
  sizes: {
    '0': '0rem',
    '1': '0.25rem',
    '2': '0.5rem',
    '3': '0.75rem',
    '4': '1rem',
    '5': '1.25rem',
    '6': '1.5rem',
    '7': '1.75rem',
    '8': '2rem',
    '9': '2.25rem',
    '10': '2.5rem',
    '11': '2.75rem',
    '12': '3rem',
    '14': '3.5rem',
    '16': '4rem',
    '20': '5rem',
    '24': '6rem',
    '28': '7rem',
    '32': '8rem',
    '36': '9rem',
    '40': '10rem',
    '44': '11rem',
    '48': '12rem',
    '52': '13rem',
    '56': '14rem',
    '60': '15rem',
    '64': '16rem',
    '72': '18rem',
    '80': '20rem',
    '96': '24rem',
    '0.5': '0.125rem',
    '1.5': '0.375rem',
    '2.5': '0.625rem',
    '3.5': '0.875rem',
    xs: '20rem',
    sm: '24rem',
    md: '28rem',
    lg: '32rem',
    xl: '36rem',
    '2xl': '42rem',
    '3xl': '48rem',
    '4xl': '56rem',
    '5xl': '64rem',
    '6xl': '72rem',
    '7xl': '80rem',
    '8xl': '90rem',
    prose: '65ch',
    full: '100%',
    min: 'min-content',
    max: 'max-content',
    fit: 'fit-content',
    screen: '100vw',
    dvh: '100dvh',
    lvh: '100lvh',
    svh: '100svh',
    dvw: '100dvw',
    lvw: '100lvw',
    svw: '100svw',
    '9xl': '96rem',
    '10xl': '104rem',
    '11xl': '112rem',
    '12xl': '120rem',
    auto: 'auto',
    '1/2': '50%',
    '1/3': '33.333333%',
    '2/3': '66.666667%',
    '1/4': '25%',
    '2/4': '50%',
    '3/4': '75%',
    '1/5': '20%',
    '2/5': '40%',
    '3/5': '60%',
    '4/5': '80%',
    '1/6': '16.666667%',
    '2/6': '33.333333%',
    '3/6': '50%',
    '4/6': '66.666667%',
    '5/6': '83.333333%',
    '1/12': '8.333333%',
    '2/12': '16.666667%',
    '3/12': '25%',
    '4/12': '33.333333%',
    '5/12': '41.666667%',
    '6/12': '50%',
    '7/12': '58.333333%',
    '8/12': '66.666667%',
    '9/12': '75%',
    '10/12': '83.333333%',
    '11/12': '91.666667%',
    '-0.5': '-0.125rem',
    '-1': '-0.25rem',
    '-1.5': '-0.375rem',
    '-2': '-0.5rem',
    '-2.5': '-0.625rem',
    '-3': '-0.75rem',
    '-3.5': '-0.875rem',
    '-4': '-1rem',
    '-5': '-1.25rem',
    '-6': '-1.5rem',
    '-7': '-1.75rem',
    '-8': '-2rem',
    '-9': '-2.25rem',
    '-10': '-2.5rem',
    '-11': '-2.75rem',
    '-12': '-3rem',
    '-14': '-3.5rem',
    '-16': '-4rem',
    '-20': '-5rem',
    '-24': '-6rem',
    '-28': '-7rem',
    '-32': '-8rem',
    '-36': '-9rem',
    '-40': '-10rem',
    '-44': '-11rem',
    '-48': '-12rem',
    '-52': '-13rem',
    '-56': '-14rem',
    '-60': '-15rem',
    '-64': '-16rem',
    '-72': '-18rem',
    '-80': '-20rem',
    '-96': '-24rem',
  },
  shadows: {
    '2xs': '0 1px rgb(0 0 0 / 0.05)',
    xs: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
    sm: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
    md: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
    lg: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
    xl: '0 20px 25px -5px rgb(0 0 0 / 0.1), 0 8px 10px -6px rgb(0 0 0 / 0.1)',
    '2xl': '0 25px 50px -12px rgb(0 0 0 / 0.25)',
    'inset-2xs': 'inset 0 1px rgb(0 0 0 / 0.05)',
    'inset-xs': 'inset 0 1px 1px rgb(0 0 0 / 0.05)',
    'inset-sm': 'inset 0 2px 4px rgb(0 0 0 / 0.05)',
  },
  radii: {
    xs: '0.125rem',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    '4xl': '2rem',
    full: '9999px',
  },
  zIndex: {},
} as const
