import { describe, test, expect } from 'vitest'
import { setupPackage } from '../src/generate-package'

describe('package gen', () => {
  test('should generate package', () => {
    expect(
      setupPackage({
        name: 'dot-panda',
        outDir: 'dist',
        exports: ['design-tokens', 'css'],
      }),
    ).toMatchInlineSnapshot(`
      {
        "description": "This package is auto-generated by Css Panda",
        "exports": {
          "./css": {
            "import": "./dist/css/index.mjs",
          },
          "./design-tokens": {
            "import": "./dist/design-tokens/index.mjs",
          },
        },
        "name": "dot-panda",
        "typeVersions": {
          "*": {
            "css": [
              "./dist/css",
            ],
            "design-tokens": [
              "./dist/design-tokens",
            ],
          },
        },
      }
    `)
  })
})
