/* eslint-disable */
export type TokenValue = string & { var: string }

export declare const aspectRatios_square: TokenValue
export declare const aspectRatios_landscape: TokenValue
export declare const aspectRatios_portrait: TokenValue
export declare const aspectRatios_wide: TokenValue
export declare const aspectRatios_ultrawide: TokenValue
export declare const aspectRatios_golden: TokenValue
export declare const borders_none: TokenValue
export declare const easings_default: TokenValue
export declare const easings_linear: TokenValue
export declare const easings_in: TokenValue
export declare const easings_out: TokenValue
export declare const durations_fastest: TokenValue
export declare const durations_faster: TokenValue
export declare const durations_fast: TokenValue
export declare const durations_normal: TokenValue
export declare const durations_slow: TokenValue
export declare const durations_slower: TokenValue
export declare const durations_slowest: TokenValue
export declare const radii_xs: TokenValue
export declare const radii_sm: TokenValue
export declare const radii_md: TokenValue
export declare const radii_lg: TokenValue
export declare const radii_xl: TokenValue
export declare const radii_2xl: TokenValue
export declare const radii_3xl: TokenValue
export declare const radii_4xl: TokenValue
export declare const radii_full: TokenValue
export declare const fontWeights_thin: TokenValue
export declare const fontWeights_extralight: TokenValue
export declare const fontWeights_light: TokenValue
export declare const fontWeights_normal: TokenValue
export declare const fontWeights_medium: TokenValue
export declare const fontWeights_semibold: TokenValue
export declare const fontWeights_bold: TokenValue
export declare const fontWeights_extrabold: TokenValue
export declare const fontWeights_black: TokenValue
export declare const lineHeights_none: TokenValue
export declare const lineHeights_tight: TokenValue
export declare const lineHeights_snug: TokenValue
export declare const lineHeights_normal: TokenValue
export declare const lineHeights_relaxed: TokenValue
export declare const lineHeights_loose: TokenValue
export declare const fonts_sans: TokenValue
export declare const fonts_serif: TokenValue
export declare const fonts_mono: TokenValue
export declare const letterSpacings_tighter: TokenValue
export declare const letterSpacings_tight: TokenValue
export declare const letterSpacings_normal: TokenValue
export declare const letterSpacings_wide: TokenValue
export declare const letterSpacings_wider: TokenValue
export declare const letterSpacings_widest: TokenValue
export declare const fontSizes_2xs: TokenValue
export declare const fontSizes_xs: TokenValue
export declare const fontSizes_sm: TokenValue
export declare const fontSizes_md: TokenValue
export declare const fontSizes_lg: TokenValue
export declare const fontSizes_xl: TokenValue
export declare const fontSizes_2xl: TokenValue
export declare const fontSizes_3xl: TokenValue
export declare const fontSizes_4xl: TokenValue
export declare const fontSizes_5xl: TokenValue
export declare const fontSizes_6xl: TokenValue
export declare const fontSizes_7xl: TokenValue
export declare const fontSizes_8xl: TokenValue
export declare const fontSizes_9xl: TokenValue
export declare const shadows_xs: TokenValue
export declare const shadows_sm: TokenValue
export declare const shadows_md: TokenValue
export declare const shadows_lg: TokenValue
export declare const shadows_xl: TokenValue
export declare const shadows_2xl: TokenValue
export declare const shadows_inner: TokenValue
export declare const blurs_sm: TokenValue
export declare const blurs_base: TokenValue
export declare const blurs_md: TokenValue
export declare const blurs_lg: TokenValue
export declare const blurs_xl: TokenValue
export declare const blurs_2xl: TokenValue
export declare const blurs_3xl: TokenValue
export declare const spacing_0: TokenValue
export declare const spacing_1: TokenValue
export declare const spacing_2: TokenValue
export declare const spacing_3: TokenValue
export declare const spacing_4: TokenValue
export declare const spacing_5: TokenValue
export declare const spacing_6: TokenValue
export declare const spacing_7: TokenValue
export declare const spacing_8: TokenValue
export declare const spacing_9: TokenValue
export declare const spacing_10: TokenValue
export declare const spacing_11: TokenValue
export declare const spacing_12: TokenValue
export declare const spacing_14: TokenValue
export declare const spacing_16: TokenValue
export declare const spacing_20: TokenValue
export declare const spacing_24: TokenValue
export declare const spacing_28: TokenValue
export declare const spacing_32: TokenValue
export declare const spacing_36: TokenValue
export declare const spacing_40: TokenValue
export declare const spacing_44: TokenValue
export declare const spacing_48: TokenValue
export declare const spacing_52: TokenValue
export declare const spacing_56: TokenValue
export declare const spacing_60: TokenValue
export declare const spacing_64: TokenValue
export declare const spacing_72: TokenValue
export declare const spacing_80: TokenValue
export declare const spacing_96: TokenValue
export declare const spacing_0_5: TokenValue
export declare const spacing_1_5: TokenValue
export declare const spacing_2_5: TokenValue
export declare const spacing_3_5: TokenValue
export declare const sizes_0: TokenValue
export declare const sizes_1: TokenValue
export declare const sizes_2: TokenValue
export declare const sizes_3: TokenValue
export declare const sizes_4: TokenValue
export declare const sizes_5: TokenValue
export declare const sizes_6: TokenValue
export declare const sizes_7: TokenValue
export declare const sizes_8: TokenValue
export declare const sizes_9: TokenValue
export declare const sizes_10: TokenValue
export declare const sizes_11: TokenValue
export declare const sizes_12: TokenValue
export declare const sizes_14: TokenValue
export declare const sizes_16: TokenValue
export declare const sizes_20: TokenValue
export declare const sizes_24: TokenValue
export declare const sizes_28: TokenValue
export declare const sizes_32: TokenValue
export declare const sizes_36: TokenValue
export declare const sizes_40: TokenValue
export declare const sizes_44: TokenValue
export declare const sizes_48: TokenValue
export declare const sizes_52: TokenValue
export declare const sizes_56: TokenValue
export declare const sizes_60: TokenValue
export declare const sizes_64: TokenValue
export declare const sizes_72: TokenValue
export declare const sizes_80: TokenValue
export declare const sizes_96: TokenValue
export declare const sizes_0_5: TokenValue
export declare const sizes_1_5: TokenValue
export declare const sizes_2_5: TokenValue
export declare const sizes_3_5: TokenValue
export declare const sizes_xs: TokenValue
export declare const sizes_sm: TokenValue
export declare const sizes_md: TokenValue
export declare const sizes_lg: TokenValue
export declare const sizes_xl: TokenValue
export declare const sizes_2xl: TokenValue
export declare const sizes_3xl: TokenValue
export declare const sizes_4xl: TokenValue
export declare const sizes_5xl: TokenValue
export declare const sizes_6xl: TokenValue
export declare const sizes_7xl: TokenValue
export declare const sizes_8xl: TokenValue
export declare const sizes_prose: TokenValue
export declare const sizes_full: TokenValue
export declare const sizes_min: TokenValue
export declare const sizes_max: TokenValue
export declare const sizes_fit: TokenValue
export declare const animations_spin: TokenValue
export declare const animations_ping: TokenValue
export declare const animations_pulse: TokenValue
export declare const animations_bounce: TokenValue
export declare const colors_current: TokenValue
export declare const colors_black: TokenValue
export declare const colors_white: TokenValue
export declare const colors_transparent: TokenValue
export declare const colors_rose_50: TokenValue
export declare const colors_rose_100: TokenValue
export declare const colors_rose_200: TokenValue
export declare const colors_rose_300: TokenValue
export declare const colors_rose_400: TokenValue
export declare const colors_rose_500: TokenValue
export declare const colors_rose_600: TokenValue
export declare const colors_rose_700: TokenValue
export declare const colors_rose_800: TokenValue
export declare const colors_rose_900: TokenValue
export declare const colors_rose_950: TokenValue
export declare const colors_pink_50: TokenValue
export declare const colors_pink_100: TokenValue
export declare const colors_pink_200: TokenValue
export declare const colors_pink_300: TokenValue
export declare const colors_pink_400: TokenValue
export declare const colors_pink_500: TokenValue
export declare const colors_pink_600: TokenValue
export declare const colors_pink_700: TokenValue
export declare const colors_pink_800: TokenValue
export declare const colors_pink_900: TokenValue
export declare const colors_pink_950: TokenValue
export declare const colors_fuchsia_50: TokenValue
export declare const colors_fuchsia_100: TokenValue
export declare const colors_fuchsia_200: TokenValue
export declare const colors_fuchsia_300: TokenValue
export declare const colors_fuchsia_400: TokenValue
export declare const colors_fuchsia_500: TokenValue
export declare const colors_fuchsia_600: TokenValue
export declare const colors_fuchsia_700: TokenValue
export declare const colors_fuchsia_800: TokenValue
export declare const colors_fuchsia_900: TokenValue
export declare const colors_fuchsia_950: TokenValue
export declare const colors_purple_50: TokenValue
export declare const colors_purple_100: TokenValue
export declare const colors_purple_200: TokenValue
export declare const colors_purple_300: TokenValue
export declare const colors_purple_400: TokenValue
export declare const colors_purple_500: TokenValue
export declare const colors_purple_600: TokenValue
export declare const colors_purple_700: TokenValue
export declare const colors_purple_800: TokenValue
export declare const colors_purple_900: TokenValue
export declare const colors_purple_950: TokenValue
export declare const colors_violet_50: TokenValue
export declare const colors_violet_100: TokenValue
export declare const colors_violet_200: TokenValue
export declare const colors_violet_300: TokenValue
export declare const colors_violet_400: TokenValue
export declare const colors_violet_500: TokenValue
export declare const colors_violet_600: TokenValue
export declare const colors_violet_700: TokenValue
export declare const colors_violet_800: TokenValue
export declare const colors_violet_900: TokenValue
export declare const colors_violet_950: TokenValue
export declare const colors_indigo_50: TokenValue
export declare const colors_indigo_100: TokenValue
export declare const colors_indigo_200: TokenValue
export declare const colors_indigo_300: TokenValue
export declare const colors_indigo_400: TokenValue
export declare const colors_indigo_500: TokenValue
export declare const colors_indigo_600: TokenValue
export declare const colors_indigo_700: TokenValue
export declare const colors_indigo_800: TokenValue
export declare const colors_indigo_900: TokenValue
export declare const colors_indigo_950: TokenValue
export declare const colors_blue_50: TokenValue
export declare const colors_blue_100: TokenValue
export declare const colors_blue_200: TokenValue
export declare const colors_blue_300: TokenValue
export declare const colors_blue_400: TokenValue
export declare const colors_blue_500: TokenValue
export declare const colors_blue_600: TokenValue
export declare const colors_blue_700: TokenValue
export declare const colors_blue_800: TokenValue
export declare const colors_blue_900: TokenValue
export declare const colors_blue_950: TokenValue
export declare const colors_sky_50: TokenValue
export declare const colors_sky_100: TokenValue
export declare const colors_sky_200: TokenValue
export declare const colors_sky_300: TokenValue
export declare const colors_sky_400: TokenValue
export declare const colors_sky_500: TokenValue
export declare const colors_sky_600: TokenValue
export declare const colors_sky_700: TokenValue
export declare const colors_sky_800: TokenValue
export declare const colors_sky_900: TokenValue
export declare const colors_sky_950: TokenValue
export declare const colors_cyan_50: TokenValue
export declare const colors_cyan_100: TokenValue
export declare const colors_cyan_200: TokenValue
export declare const colors_cyan_300: TokenValue
export declare const colors_cyan_400: TokenValue
export declare const colors_cyan_500: TokenValue
export declare const colors_cyan_600: TokenValue
export declare const colors_cyan_700: TokenValue
export declare const colors_cyan_800: TokenValue
export declare const colors_cyan_900: TokenValue
export declare const colors_cyan_950: TokenValue
export declare const colors_teal_50: TokenValue
export declare const colors_teal_100: TokenValue
export declare const colors_teal_200: TokenValue
export declare const colors_teal_300: TokenValue
export declare const colors_teal_400: TokenValue
export declare const colors_teal_500: TokenValue
export declare const colors_teal_600: TokenValue
export declare const colors_teal_700: TokenValue
export declare const colors_teal_800: TokenValue
export declare const colors_teal_900: TokenValue
export declare const colors_teal_950: TokenValue
export declare const colors_emerald_50: TokenValue
export declare const colors_emerald_100: TokenValue
export declare const colors_emerald_200: TokenValue
export declare const colors_emerald_300: TokenValue
export declare const colors_emerald_400: TokenValue
export declare const colors_emerald_500: TokenValue
export declare const colors_emerald_600: TokenValue
export declare const colors_emerald_700: TokenValue
export declare const colors_emerald_800: TokenValue
export declare const colors_emerald_900: TokenValue
export declare const colors_emerald_950: TokenValue
export declare const colors_green_50: TokenValue
export declare const colors_green_100: TokenValue
export declare const colors_green_200: TokenValue
export declare const colors_green_300: TokenValue
export declare const colors_green_400: TokenValue
export declare const colors_green_500: TokenValue
export declare const colors_green_600: TokenValue
export declare const colors_green_700: TokenValue
export declare const colors_green_800: TokenValue
export declare const colors_green_900: TokenValue
export declare const colors_green_950: TokenValue
export declare const colors_lime_50: TokenValue
export declare const colors_lime_100: TokenValue
export declare const colors_lime_200: TokenValue
export declare const colors_lime_300: TokenValue
export declare const colors_lime_400: TokenValue
export declare const colors_lime_500: TokenValue
export declare const colors_lime_600: TokenValue
export declare const colors_lime_700: TokenValue
export declare const colors_lime_800: TokenValue
export declare const colors_lime_900: TokenValue
export declare const colors_lime_950: TokenValue
export declare const colors_yellow_50: TokenValue
export declare const colors_yellow_100: TokenValue
export declare const colors_yellow_200: TokenValue
export declare const colors_yellow_300: TokenValue
export declare const colors_yellow_400: TokenValue
export declare const colors_yellow_500: TokenValue
export declare const colors_yellow_600: TokenValue
export declare const colors_yellow_700: TokenValue
export declare const colors_yellow_800: TokenValue
export declare const colors_yellow_900: TokenValue
export declare const colors_yellow_950: TokenValue
export declare const colors_amber_50: TokenValue
export declare const colors_amber_100: TokenValue
export declare const colors_amber_200: TokenValue
export declare const colors_amber_300: TokenValue
export declare const colors_amber_400: TokenValue
export declare const colors_amber_500: TokenValue
export declare const colors_amber_600: TokenValue
export declare const colors_amber_700: TokenValue
export declare const colors_amber_800: TokenValue
export declare const colors_amber_900: TokenValue
export declare const colors_amber_950: TokenValue
export declare const colors_orange_50: TokenValue
export declare const colors_orange_100: TokenValue
export declare const colors_orange_200: TokenValue
export declare const colors_orange_300: TokenValue
export declare const colors_orange_400: TokenValue
export declare const colors_orange_500: TokenValue
export declare const colors_orange_600: TokenValue
export declare const colors_orange_700: TokenValue
export declare const colors_orange_800: TokenValue
export declare const colors_orange_900: TokenValue
export declare const colors_orange_950: TokenValue
export declare const colors_red_50: TokenValue
export declare const colors_red_100: TokenValue
export declare const colors_red_200: TokenValue
export declare const colors_red_300: TokenValue
export declare const colors_red_400: TokenValue
export declare const colors_red_500: TokenValue
export declare const colors_red_600: TokenValue
export declare const colors_red_700: TokenValue
export declare const colors_red_800: TokenValue
export declare const colors_red_900: TokenValue
export declare const colors_red_950: TokenValue
export declare const colors_stone_50: TokenValue
export declare const colors_stone_100: TokenValue
export declare const colors_stone_200: TokenValue
export declare const colors_stone_300: TokenValue
export declare const colors_stone_400: TokenValue
export declare const colors_stone_500: TokenValue
export declare const colors_stone_600: TokenValue
export declare const colors_stone_700: TokenValue
export declare const colors_stone_800: TokenValue
export declare const colors_stone_900: TokenValue
export declare const colors_stone_950: TokenValue
export declare const colors_zinc_50: TokenValue
export declare const colors_zinc_100: TokenValue
export declare const colors_zinc_200: TokenValue
export declare const colors_zinc_300: TokenValue
export declare const colors_zinc_400: TokenValue
export declare const colors_zinc_500: TokenValue
export declare const colors_zinc_600: TokenValue
export declare const colors_zinc_700: TokenValue
export declare const colors_zinc_800: TokenValue
export declare const colors_zinc_900: TokenValue
export declare const colors_zinc_950: TokenValue
export declare const colors_gray_50: TokenValue
export declare const colors_gray_100: TokenValue
export declare const colors_gray_200: TokenValue
export declare const colors_gray_300: TokenValue
export declare const colors_gray_400: TokenValue
export declare const colors_gray_500: TokenValue
export declare const colors_gray_600: TokenValue
export declare const colors_gray_700: TokenValue
export declare const colors_gray_800: TokenValue
export declare const colors_gray_900: TokenValue
export declare const colors_gray_950: TokenValue
export declare const colors_slate_50: TokenValue
export declare const colors_slate_100: TokenValue
export declare const colors_slate_200: TokenValue
export declare const colors_slate_300: TokenValue
export declare const colors_slate_400: TokenValue
export declare const colors_slate_500: TokenValue
export declare const colors_slate_600: TokenValue
export declare const colors_slate_700: TokenValue
export declare const colors_slate_800: TokenValue
export declare const colors_slate_900: TokenValue
export declare const colors_slate_950: TokenValue
export declare const colors_neutral_50: TokenValue
export declare const colors_neutral_100: TokenValue
export declare const colors_neutral_200: TokenValue
export declare const colors_neutral_300: TokenValue
export declare const colors_neutral_400: TokenValue
export declare const colors_neutral_500: TokenValue
export declare const colors_neutral_600: TokenValue
export declare const colors_neutral_700: TokenValue
export declare const colors_neutral_800: TokenValue
export declare const colors_neutral_900: TokenValue
export declare const colors_neutral_950: TokenValue
export declare const assets_check: TokenValue
export declare const breakpoints_sm: TokenValue
export declare const breakpoints_md: TokenValue
export declare const breakpoints_lg: TokenValue
export declare const breakpoints_xl: TokenValue
export declare const breakpoints_2xl: TokenValue
export declare const shadows_inset: TokenValue
export declare const colors_text: TokenValue
export declare const colors_bg: TokenValue
export declare const colors_card: TokenValue
export declare const colors_border: TokenValue
export declare const colors_accent: TokenValue
export declare const spacing_n1: TokenValue
export declare const spacing_n2: TokenValue
export declare const spacing_n3: TokenValue
export declare const spacing_n4: TokenValue
export declare const spacing_n5: TokenValue
export declare const spacing_n6: TokenValue
export declare const spacing_n7: TokenValue
export declare const spacing_n8: TokenValue
export declare const spacing_n9: TokenValue
export declare const spacing_n10: TokenValue
export declare const spacing_n11: TokenValue
export declare const spacing_n12: TokenValue
export declare const spacing_n14: TokenValue
export declare const spacing_n16: TokenValue
export declare const spacing_n20: TokenValue
export declare const spacing_n24: TokenValue
export declare const spacing_n28: TokenValue
export declare const spacing_n32: TokenValue
export declare const spacing_n36: TokenValue
export declare const spacing_n40: TokenValue
export declare const spacing_n44: TokenValue
export declare const spacing_n48: TokenValue
export declare const spacing_n52: TokenValue
export declare const spacing_n56: TokenValue
export declare const spacing_n60: TokenValue
export declare const spacing_n64: TokenValue
export declare const spacing_n72: TokenValue
export declare const spacing_n80: TokenValue
export declare const spacing_n96: TokenValue
export declare const spacing_n0_5: TokenValue
export declare const spacing_n1_5: TokenValue
export declare const spacing_n2_5: TokenValue
export declare const spacing_n3_5: TokenValue
export declare const colors_colorPalette: TokenValue
export declare const colors_colorPalette_50: TokenValue
export declare const colors_colorPalette_100: TokenValue
export declare const colors_colorPalette_200: TokenValue
export declare const colors_colorPalette_300: TokenValue
export declare const colors_colorPalette_400: TokenValue
export declare const colors_colorPalette_500: TokenValue
export declare const colors_colorPalette_600: TokenValue
export declare const colors_colorPalette_700: TokenValue
export declare const colors_colorPalette_800: TokenValue
export declare const colors_colorPalette_900: TokenValue
export declare const colors_colorPalette_950: TokenValue

export declare const $: Record<"easings.in-out" | "sizes.breakpoint-sm" | "sizes.breakpoint-md" | "sizes.breakpoint-lg" | "sizes.breakpoint-xl" | "sizes.breakpoint-2xl", string>;
