import type { PackageJson } from 'pkg-types'

export function generatePackageJSON() {
  const pkg: PackageJson = {
    name: 'dot-panda',
    description: 'This package is auto-generated by Panda',
    version: `0.0.0-${performance.now()}`,
    exports: {
      './css': {
        import: './css/index.js',
        types: './css/index.d.ts',
      },
      './design-tokens': {
        import: './design-tokens/index.js',
        types: './design-tokens/index.d.ts',
      },
      './tokens.css': './design-tokens/index.css',
      './styles.css': './styles.css',
      './package.json': './package.json',
    },
    typeVersions: {
      '*': {
        css: ['./css'],
        'design-tokens': ['./design-tokens'],
      },
    },
  }

  return JSON.stringify(pkg, null, 2)
}
