import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { build, defineConfig, type Options } from 'tsup'

/** Baked into the virtual internal css module; patched per-project at load time. */
const CX_SEPARATOR_PLACEHOLDER = '__PANDA_CX_SEPARATOR__'

const internalCssRuntimeOut = join('dist/runtime/internal.runtime.mjs')
const internalCssSourceOut = join('src/runtime/internal/source.ts')

function writeInternalCssSource() {
  const bundled = readFileSync(internalCssRuntimeOut, 'utf8')
  writeFileSync(
    internalCssSourceOut,
    `// Generated by tsup — do not edit.\nexport const internalCssSource = ${JSON.stringify(bundled)}\n`,
  )
}

const internalCssRuntimeBuild: Options = {
  entry: ['src/runtime/internal.runtime.ts'],
  outDir: 'dist/runtime',
  outExtension: () => ({ js: '.mjs' }),
  format: ['esm'],
  platform: 'neutral',
  minify: true,
  bundle: true,
  dts: false,
  clean: false,
  esbuildOptions(options) {
    options.define = {
      ...options.define,
      __PANDA_CX_SEPARATOR__: JSON.stringify(CX_SEPARATOR_PLACEHOLDER),
    }
  },
}

export default defineConfig((options) => ({
  entry: {
    index: 'src/index.ts',
    'runtime/cx': 'src/runtime/internal/cx.ts',
    'runtime/internal': 'src/runtime/internal/index.ts',
  },
  format: ['esm'],
  platform: 'node',
  dts: options.dts !== false,
  splitting: false,
  clean: true,
  async onSuccess() {
    await build({ ...internalCssRuntimeBuild, config: false })
    writeInternalCssSource()
  },
}))
