// Generated by dts-bundle-generator v9.5.1

import { AnimationStyles, CompositionStyles, Config, CssKeyframes, ExtendableConditions, FirstThatWorksMember, GlobalFontface, GlobalStyleObject, LayerStyles, PandaPlugin, PatternConfig, PositionTry, Preset, PropertyConfig, RecipeConfig, RecipeVariantRecord, SemanticTokens, SlotRecipeConfig, SlotRecipeVariantRecord, SystemStyleObject, TextStyles, ThemeVariant, Tokens, UserConfig, ViewTransitions } from '@pandacss/types';

export type FirstThatWorksMemberOf<T> = Extract<T, FirstThatWorksMember>;
export declare function firstThatWorks<T = FirstThatWorksMember, A extends FirstThatWorksMemberOf<T> = FirstThatWorksMemberOf<T>, B extends FirstThatWorksMemberOf<T> = FirstThatWorksMemberOf<T>, C extends FirstThatWorksMemberOf<T> = never, D extends FirstThatWorksMemberOf<T> = never, E extends FirstThatWorksMemberOf<T> = never, F extends FirstThatWorksMemberOf<T> = never>(first: A, second: B, third?: C, fourth?: D, fifth?: E, sixth?: F): T extends FirstThatWorksMember ? A | B | C | D | E | F : FirstThatWorksMemberOf<T>;
export declare function defineConfig<const T extends Config>(config: T): T & {
	name: string;
};
export declare function defineRecipe<T extends RecipeVariantRecord>(config: RecipeConfig<T>): RecipeConfig<T>;
export declare function defineSlotRecipe<S extends string, T extends SlotRecipeVariantRecord<S>>(config: SlotRecipeConfig<S, T>): SlotRecipeConfig<S, T>;
export declare function definePattern<T extends PatternConfig>(config: T): PatternConfig;
export declare function definePreset<const T extends Preset>(preset: T): T;
export declare function defineKeyframes(keyframes: CssKeyframes): CssKeyframes;
export declare function defineGlobalStyles(definition: GlobalStyleObject): GlobalStyleObject;
export declare function defineGlobalFontface(definition: GlobalFontface): GlobalFontface;
export declare function defineUtility(utility: PropertyConfig): PropertyConfig;
export declare function defineConditions(definition: ExtendableConditions): ExtendableConditions;
export declare function definePlugin(plugin: PandaPlugin): PandaPlugin;
export declare function defineThemeVariant<T extends ThemeVariant>(theme: T): T;
export declare function defineThemeContract<C extends Partial<Omit<ThemeVariant, "selector">>>(_contract: C): <T extends C & ThemeVariant>(theme: T) => T;
export declare const defineTokens: {
	<Value>(definition: Value): Value;
} & {
	[K in keyof Required<Tokens>]: <Value>(definition: Value) => Value;
};
export declare const defineSemanticTokens: {
	<Value>(definition: Value): Value;
} & {
	[K in keyof Required<SemanticTokens>]: <Value>(definition: Value) => Value;
};
export declare function defineTextStyles(definition: CompositionStyles["textStyles"]): TextStyles;
export declare function defineLayerStyles(definition: CompositionStyles["layerStyles"]): LayerStyles;
export declare function defineStyles(definition: SystemStyleObject): SystemStyleObject;
export declare function defineAnimationStyles(definition: CompositionStyles["animationStyles"]): AnimationStyles;
export declare function defineViewTransitions(definition: ViewTransitions): ViewTransitions;
export declare function definePositionTry(definition: PositionTry): PositionTry;

export {
	Config,
	Preset,
	UserConfig,
};

export {};
