import { Inter } from '@next/font/google'
import { css } from '@/design-system/css'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <h1
          className={css({
            color: 'red.200',
            fontSize: '5xl',
            padding: '90px',
          })}
        >
          Let's build the playground
        </h1>
      </main>
    </>
  )
}
