import { css } from '@/design-system/css'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={css({ fontFamily: 'Inter' })}>
        <h1
          className={css({
            color: 'orange',
            fontSize: '5xl',
            padding: '40px',
          })}
        >
          Let's build the playground
        </h1>
      </main>
    </>
  )
}
