[package]
name = "pandacss_codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false
autotests = false

[[test]]
name = "integration"
path = "tests/main.rs"

[dependencies]
indoc = { workspace = true }
oxc_allocator = { workspace = true }
oxc_ast = { workspace = true }
oxc_ast_visit = { workspace = true }
oxc_parser = { workspace = true }
oxc_span = { workspace = true }
pandacss_config = { workspace = true }
pandacss_shared = { workspace = true }
pandacss_stylesheet = { workspace = true }
pandacss_tokens = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
