//! csstype `DataType.*` literal unions synced for generated TypeScript.
//! Regenerate: `python3 crates/pandacss_codegen/scripts/sync_strict_props.py --write`

pub(crate) static NAMED_COLORS: &[&str] = &[
    "aliceblue",
    "antiquewhite",
    "aqua",
    "aquamarine",
    "azure",
    "beige",
    "bisque",
    "black",
    "blanchedalmond",
    "blue",
    "blueviolet",
    "brown",
    "burlywood",
    "cadetblue",
    "chartreuse",
    "chocolate",
    "coral",
    "cornflowerblue",
    "cornsilk",
    "crimson",
    "cyan",
    "darkblue",
    "darkcyan",
    "darkgoldenrod",
    "darkgray",
    "darkgreen",
    "darkgrey",
    "darkkhaki",
    "darkmagenta",
    "darkolivegreen",
    "darkorange",
    "darkorchid",
    "darkred",
    "darksalmon",
    "darkseagreen",
    "darkslateblue",
    "darkslategray",
    "darkslategrey",
    "darkturquoise",
    "darkviolet",
    "deeppink",
    "deepskyblue",
    "dimgray",
    "dimgrey",
    "dodgerblue",
    "firebrick",
    "floralwhite",
    "forestgreen",
    "fuchsia",
    "gainsboro",
    "ghostwhite",
    "gold",
    "goldenrod",
    "gray",
    "green",
    "greenyellow",
    "grey",
    "honeydew",
    "hotpink",
    "indianred",
    "indigo",
    "ivory",
    "khaki",
    "lavender",
    "lavenderblush",
    "lawngreen",
    "lemonchiffon",
    "lightblue",
    "lightcoral",
    "lightcyan",
    "lightgoldenrodyellow",
    "lightgray",
    "lightgreen",
    "lightgrey",
    "lightpink",
    "lightsalmon",
    "lightseagreen",
    "lightskyblue",
    "lightslategray",
    "lightslategrey",
    "lightsteelblue",
    "lightyellow",
    "lime",
    "limegreen",
    "linen",
    "magenta",
    "maroon",
    "mediumaquamarine",
    "mediumblue",
    "mediumorchid",
    "mediumpurple",
    "mediumseagreen",
    "mediumslateblue",
    "mediumspringgreen",
    "mediumturquoise",
    "mediumvioletred",
    "midnightblue",
    "mintcream",
    "mistyrose",
    "moccasin",
    "navajowhite",
    "navy",
    "oldlace",
    "olive",
    "olivedrab",
    "orange",
    "orangered",
    "orchid",
    "palegoldenrod",
    "palegreen",
    "paleturquoise",
    "palevioletred",
    "papayawhip",
    "peachpuff",
    "peru",
    "pink",
    "plum",
    "powderblue",
    "purple",
    "rebeccapurple",
    "red",
    "rosybrown",
    "royalblue",
    "saddlebrown",
    "salmon",
    "sandybrown",
    "seagreen",
    "seashell",
    "sienna",
    "silver",
    "skyblue",
    "slateblue",
    "slategray",
    "slategrey",
    "snow",
    "springgreen",
    "steelblue",
    "tan",
    "teal",
    "thistle",
    "tomato",
    "turquoise",
    "violet",
    "wheat",
    "white",
    "whitesmoke",
    "yellow",
    "yellowgreen",
];

pub(crate) static SYSTEM_COLORS: &[&str] = &[
    "AccentColor",
    "AccentColorText",
    "ActiveText",
    "ButtonBorder",
    "ButtonFace",
    "ButtonText",
    "Canvas",
    "CanvasText",
    "Field",
    "FieldText",
    "GrayText",
    "Highlight",
    "HighlightText",
    "LinkText",
    "Mark",
    "MarkText",
    "SelectedItem",
    "SelectedItemText",
    "VisitedText",
];

pub(crate) static ABSOLUTE_SIZES: &[&str] = &[
    "large",
    "medium",
    "small",
    "x-large",
    "x-small",
    "xx-large",
    "xx-small",
    "xxx-large",
];

pub(crate) static BG_SIZE_KEYWORDS: &[&str] = &["auto", "contain", "cover"];

pub(crate) static FONT_WEIGHT_KEYWORDS: &[&str] = &["bold", "normal"];

pub(crate) static LINE_WIDTH_KEYWORDS: &[&str] = &["medium", "thick", "thin"];

pub(crate) static POSITION_KEYWORDS: &[&str] = &["bottom", "center", "left", "right", "top"];

pub(crate) static LINE_STYLE_KEYWORDS: &[&str] = &[
    "dashed", "dotted", "double", "groove", "hidden", "inset", "none", "outset", "ridge", "solid",
];

pub(crate) static REPEAT_STYLE_KEYWORDS: &[&str] = &[
    "no-repeat",
    "repeat",
    "repeat-x",
    "repeat-y",
    "round",
    "space",
];

pub(crate) static FONT_STRETCH_KEYWORDS: &[&str] = &[
    "condensed",
    "expanded",
    "extra-condensed",
    "extra-expanded",
    "normal",
    "semi-condensed",
    "semi-expanded",
    "ultra-condensed",
    "ultra-expanded",
];

pub(crate) static OVERFLOW_KEYWORDS: &[&str] = &[
    "-moz-hidden-unscrollable",
    "auto",
    "clip",
    "hidden",
    "overlay",
    "scroll",
    "visible",
];

pub(crate) static OVERFLOW_SHORT_KEYWORDS: &[&str] =
    &["auto", "clip", "hidden", "scroll", "visible"];

pub(crate) static OVERSCROLL_BEHAVIOR_KEYWORDS: &[&str] = &["auto", "contain", "none"];

pub(crate) static GENERIC_FAMILIES: &[&str] = &[
    "-apple-system",
    "cursive",
    "emoji",
    "fangsong",
    "fantasy",
    "math",
    "monospace",
    "sans-serif",
    "serif",
    "system-ui",
    "ui-monospace",
    "ui-rounded",
    "ui-sans-serif",
    "ui-serif",
];

pub(crate) fn literals_union(values: &[&str]) -> String {
    values
        .iter()
        .map(|value| format!("{value:?}"))
        .collect::<Vec<_>>()
        .join(" | ")
}
