//! Native CSS property value shapes for generated `PropertyValueMap` entries.
//!
//! Keyword unions cover the v1 `strictPropertyList`; composite kinds (`Length`,
//! `Color`, …) cover native length/color autocomplete on `SystemProperties`.
//!
//! Sourced from csstype@3.2.3 `index.d.ts`. Regenerate:
//! `python3 crates/pandacss_codegen/scripts/sync_strict_props.py --write`

#[derive(Clone, Copy)]
pub(crate) enum PropertyValueKind {
    Keywords {
        keywords: &'static [&'static str],
        open: bool,
    },
    Length,
    Color,
    Numeric,
    ZIndex,
    BgSize,
    FontSize,
    FontWeight,
    LineWidth,
    Position,
    FontFamily,
    LineStyle {
        open: bool,
    },
    RepeatStyle,
    FontStretch,
    Overflow {
        open: bool,
    },
    OverflowShort,
    OverscrollBehavior {
        open: bool,
    },
}

pub(crate) struct PropertyValueEntry {
    pub name: &'static str,
    pub kind: PropertyValueKind,
}

impl PropertyValueEntry {
    pub(crate) fn keywords_open(&self) -> Option<bool> {
        match self.kind {
            PropertyValueKind::Keywords { open, .. }
            | PropertyValueKind::LineStyle { open }
            | PropertyValueKind::Overflow { open }
            | PropertyValueKind::OverscrollBehavior { open } => Some(open),
            PropertyValueKind::RepeatStyle | PropertyValueKind::FontStretch => Some(true),
            PropertyValueKind::OverflowShort => Some(false),
            _ => None,
        }
    }

    pub(crate) fn is_keywords(&self) -> bool {
        matches!(
            self.kind,
            PropertyValueKind::Keywords { .. }
                | PropertyValueKind::LineStyle { .. }
                | PropertyValueKind::RepeatStyle
                | PropertyValueKind::FontStretch
                | PropertyValueKind::Overflow { .. }
                | PropertyValueKind::OverflowShort
                | PropertyValueKind::OverscrollBehavior { .. }
        )
    }
}

// @generated-start — sync_strict_props.py
#[rustfmt::skip]
pub(crate) const PROPERTY_VALUES: &[PropertyValueEntry] = &[
    PropertyValueEntry { name: "accentColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "alignContent", kind: PropertyValueKind::Keywords { keywords: &["baseline", "center", "end", "flex-end", "flex-start", "normal", "space-around", "space-between", "space-evenly", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "alignItems", kind: PropertyValueKind::Keywords { keywords: &["anchor-center", "baseline", "center", "end", "flex-end", "flex-start", "normal", "self-end", "self-start", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "alignSelf", kind: PropertyValueKind::Keywords { keywords: &["anchor-center", "auto", "baseline", "center", "end", "flex-end", "flex-start", "normal", "self-end", "self-start", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "alignmentBaseline", kind: PropertyValueKind::Keywords { keywords: &["alphabetic", "baseline", "central", "ideographic", "mathematical", "middle", "text-after-edge", "text-before-edge"], open: false } },
    PropertyValueEntry { name: "appearance", kind: PropertyValueKind::Keywords { keywords: &["auto", "button", "checkbox", "listbox", "menulist", "menulist-button", "meter", "none", "progress-bar", "radio", "searchfield", "textarea", "textfield"], open: false } },
    PropertyValueEntry { name: "backgroundColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "backgroundPosition", kind: PropertyValueKind::Position },
    PropertyValueEntry { name: "backgroundRepeat", kind: PropertyValueKind::RepeatStyle },
    PropertyValueEntry { name: "backgroundSize", kind: PropertyValueKind::BgSize },
    PropertyValueEntry { name: "baselineShift", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "blockSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderBlockColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderBlockEndColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderBlockEndStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderBlockEndWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderBlockStartColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderBlockStartStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderBlockStartWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderBlockStyle", kind: PropertyValueKind::LineStyle { open: true } },
    PropertyValueEntry { name: "borderBlockWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderBottomColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderBottomLeftRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderBottomRightRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderBottomStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderBottomWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderEndEndRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderEndStartRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderImage", kind: PropertyValueKind::Keywords { keywords: &["none", "repeat", "round", "space", "stretch"], open: true } },
    PropertyValueEntry { name: "borderImageWidth", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderInlineColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderInlineEndColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderInlineEndStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderInlineEndWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderInlineStartColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderInlineStartStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderInlineStartWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderInlineStyle", kind: PropertyValueKind::LineStyle { open: true } },
    PropertyValueEntry { name: "borderInlineWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderLeftColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderLeftStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderLeftWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderRightColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderRightStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderRightWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderSpacing", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderStartEndRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderStartStartRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderStyle", kind: PropertyValueKind::LineStyle { open: true } },
    PropertyValueEntry { name: "borderTopColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "borderTopLeftRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderTopRightRadius", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "borderTopStyle", kind: PropertyValueKind::LineStyle { open: false } },
    PropertyValueEntry { name: "borderTopWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "borderWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "bottom", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "boxAlign", kind: PropertyValueKind::Keywords { keywords: &["baseline", "center", "end", "start", "stretch"], open: false } },
    PropertyValueEntry { name: "breakAfter", kind: PropertyValueKind::Keywords { keywords: &["all", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "recto", "region", "right", "verso"], open: false } },
    PropertyValueEntry { name: "breakBefore", kind: PropertyValueKind::Keywords { keywords: &["all", "always", "auto", "avoid", "avoid-column", "avoid-page", "avoid-region", "column", "left", "page", "recto", "region", "right", "verso"], open: false } },
    PropertyValueEntry { name: "breakInside", kind: PropertyValueKind::Keywords { keywords: &["auto", "avoid", "avoid-column", "avoid-page", "avoid-region"], open: false } },
    PropertyValueEntry { name: "caret", kind: PropertyValueKind::Keywords { keywords: &["auto", "bar", "block", "currentColor", "underscore"], open: true } },
    PropertyValueEntry { name: "caretColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "clear", kind: PropertyValueKind::Keywords { keywords: &["both", "inline-end", "inline-start", "left", "none", "right"], open: false } },
    PropertyValueEntry { name: "clipPath", kind: PropertyValueKind::Keywords { keywords: &["fill-box", "margin-box", "none", "stroke-box", "view-box"], open: true } },
    PropertyValueEntry { name: "color", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "colorScheme", kind: PropertyValueKind::Keywords { keywords: &["dark", "light", "normal"], open: true } },
    PropertyValueEntry { name: "columnGap", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "columnRuleColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "columnRuleStyle", kind: PropertyValueKind::LineStyle { open: true } },
    PropertyValueEntry { name: "columnRuleWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "columnWidth", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "contain", kind: PropertyValueKind::Keywords { keywords: &["content", "inline-size", "layout", "none", "paint", "size", "strict", "style"], open: true } },
    PropertyValueEntry { name: "containIntrinsicBlockSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "containIntrinsicHeight", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "containIntrinsicInlineSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "containIntrinsicSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "containIntrinsicWidth", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "containerType", kind: PropertyValueKind::Keywords { keywords: &["inline-size", "normal", "scroll-state", "size"], open: true } },
    PropertyValueEntry { name: "content", kind: PropertyValueKind::Keywords { keywords: &["close-quote", "no-close-quote", "no-open-quote", "none", "normal", "open-quote"], open: true } },
    PropertyValueEntry { name: "cursor", kind: PropertyValueKind::Keywords { keywords: &["-moz-grab", "-moz-zoom-in", "-moz-zoom-out", "-webkit-grab", "-webkit-grabbing", "-webkit-zoom-in", "-webkit-zoom-out", "alias", "all-scroll", "auto", "cell", "col-resize", "context-menu", "copy", "crosshair", "default", "e-resize", "ew-resize", "grab", "grabbing", "help", "move", "n-resize", "ne-resize", "nesw-resize", "no-drop", "none", "not-allowed", "ns-resize", "nw-resize", "nwse-resize", "pointer", "progress", "row-resize", "s-resize", "se-resize", "sw-resize", "text", "vertical-text", "w-resize", "wait", "zoom-in", "zoom-out"], open: true } },
    PropertyValueEntry { name: "display", kind: PropertyValueKind::Keywords { keywords: &["-ms-flexbox", "-ms-grid", "-ms-inline-flexbox", "-ms-inline-grid", "-webkit-flex", "-webkit-inline-flex", "block", "contents", "flex", "flow", "flow-root", "grid", "inline", "inline-block", "inline-flex", "inline-grid", "inline-list-item", "inline-table", "list-item", "none", "ruby", "ruby-base", "ruby-base-container", "ruby-text", "ruby-text-container", "run-in", "table", "table-caption", "table-cell", "table-column", "table-column-group", "table-footer-group", "table-header-group", "table-row", "table-row-group"], open: true } },
    PropertyValueEntry { name: "dominantBaseline", kind: PropertyValueKind::Keywords { keywords: &["alphabetic", "auto", "central", "hanging", "ideographic", "mathematical", "middle", "text-bottom", "text-top"], open: false } },
    PropertyValueEntry { name: "fieldSizing", kind: PropertyValueKind::Keywords { keywords: &["content", "fixed"], open: false } },
    PropertyValueEntry { name: "flexBasis", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "flexFlow", kind: PropertyValueKind::Keywords { keywords: &["column", "column-reverse", "nowrap", "row", "row-reverse", "wrap", "wrap-reverse"], open: true } },
    PropertyValueEntry { name: "flexGrow", kind: PropertyValueKind::Numeric },
    PropertyValueEntry { name: "flexShrink", kind: PropertyValueKind::Numeric },
    PropertyValueEntry { name: "float", kind: PropertyValueKind::Keywords { keywords: &["inline-end", "inline-start", "left", "none", "right"], open: false } },
    PropertyValueEntry { name: "floodColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "font", kind: PropertyValueKind::Keywords { keywords: &["caption", "icon", "menu", "message-box", "small-caption", "status-bar"], open: true } },
    PropertyValueEntry { name: "fontFamily", kind: PropertyValueKind::FontFamily },
    PropertyValueEntry { name: "fontSize", kind: PropertyValueKind::FontSize },
    PropertyValueEntry { name: "fontSizeAdjust", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "fontStretch", kind: PropertyValueKind::FontStretch },
    PropertyValueEntry { name: "fontStyle", kind: PropertyValueKind::Keywords { keywords: &["italic", "normal", "oblique"], open: true } },
    PropertyValueEntry { name: "fontSynthesis", kind: PropertyValueKind::Keywords { keywords: &["none", "position", "small-caps", "style", "weight"], open: true } },
    PropertyValueEntry { name: "fontVariantCaps", kind: PropertyValueKind::Keywords { keywords: &["all-petite-caps", "all-small-caps", "normal", "petite-caps", "small-caps", "titling-caps", "unicase"], open: false } },
    PropertyValueEntry { name: "fontVariantEastAsian", kind: PropertyValueKind::Keywords { keywords: &["full-width", "jis04", "jis78", "jis83", "jis90", "normal", "proportional-width", "ruby", "simplified", "traditional"], open: true } },
    PropertyValueEntry { name: "fontVariantLigatures", kind: PropertyValueKind::Keywords { keywords: &["common-ligatures", "contextual", "discretionary-ligatures", "historical-ligatures", "no-common-ligatures", "no-contextual", "no-discretionary-ligatures", "no-historical-ligatures", "none", "normal"], open: true } },
    PropertyValueEntry { name: "fontVariantNumeric", kind: PropertyValueKind::Keywords { keywords: &["diagonal-fractions", "lining-nums", "normal", "oldstyle-nums", "ordinal", "proportional-nums", "slashed-zero", "stacked-fractions", "tabular-nums"], open: true } },
    PropertyValueEntry { name: "fontWeight", kind: PropertyValueKind::FontWeight },
    PropertyValueEntry { name: "fontWidth", kind: PropertyValueKind::FontStretch },
    PropertyValueEntry { name: "gap", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "gridAutoFlow", kind: PropertyValueKind::Keywords { keywords: &["column", "dense", "row"], open: true } },
    PropertyValueEntry { name: "gridColumnGap", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "gridGap", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "gridRowGap", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "hangingPunctuation", kind: PropertyValueKind::Keywords { keywords: &["allow-end", "first", "force-end", "last", "none"], open: true } },
    PropertyValueEntry { name: "height", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "hyphens", kind: PropertyValueKind::Keywords { keywords: &["auto", "manual", "none"], open: false } },
    PropertyValueEntry { name: "imageRendering", kind: PropertyValueKind::Keywords { keywords: &["-moz-crisp-edges", "-webkit-optimize-contrast", "auto", "crisp-edges", "pixelated", "smooth"], open: false } },
    PropertyValueEntry { name: "imeMode", kind: PropertyValueKind::Keywords { keywords: &["active", "auto", "disabled", "inactive", "normal"], open: false } },
    PropertyValueEntry { name: "inlineSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "inset", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "justifyContent", kind: PropertyValueKind::Keywords { keywords: &["center", "end", "flex-end", "flex-start", "left", "normal", "right", "space-around", "space-between", "space-evenly", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "justifyItems", kind: PropertyValueKind::Keywords { keywords: &["anchor-center", "baseline", "center", "end", "flex-end", "flex-start", "left", "legacy", "normal", "right", "self-end", "self-start", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "justifySelf", kind: PropertyValueKind::Keywords { keywords: &["anchor-center", "auto", "baseline", "center", "end", "flex-end", "flex-start", "left", "normal", "right", "self-end", "self-start", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "left", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "letterSpacing", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "lightingColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "lineBreak", kind: PropertyValueKind::Keywords { keywords: &["anywhere", "auto", "loose", "normal", "strict"], open: false } },
    PropertyValueEntry { name: "lineHeight", kind: PropertyValueKind::Numeric },
    PropertyValueEntry { name: "lineHeightStep", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "listStyleImage", kind: PropertyValueKind::Keywords { keywords: &["none"], open: true } },
    PropertyValueEntry { name: "listStylePosition", kind: PropertyValueKind::Keywords { keywords: &["inside", "outside"], open: false } },
    PropertyValueEntry { name: "listStyleType", kind: PropertyValueKind::Keywords { keywords: &["none"], open: true } },
    PropertyValueEntry { name: "margin", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "marginBottom", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "marginLeft", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "marginRight", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "marginTop", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "maskBorder", kind: PropertyValueKind::Keywords { keywords: &["alpha", "luminance", "none", "repeat", "round", "space", "stretch"], open: true } },
    PropertyValueEntry { name: "maskBorderWidth", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "maskPosition", kind: PropertyValueKind::Position },
    PropertyValueEntry { name: "maskRepeat", kind: PropertyValueKind::RepeatStyle },
    PropertyValueEntry { name: "maskSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "maxBlockSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "maxHeight", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "maxInlineSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "maxWidth", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "minBlockSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "minHeight", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "minInlineSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "minWidth", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "mixBlendMode", kind: PropertyValueKind::Keywords { keywords: &["color", "color-burn", "color-dodge", "darken", "difference", "exclusion", "hard-light", "hue", "lighten", "luminosity", "multiply", "normal", "overlay", "plus-darker", "plus-lighter", "saturation", "screen", "soft-light"], open: false } },
    PropertyValueEntry { name: "objectFit", kind: PropertyValueKind::Keywords { keywords: &["contain", "cover", "fill", "none", "scale-down"], open: false } },
    PropertyValueEntry { name: "objectPosition", kind: PropertyValueKind::Position },
    PropertyValueEntry { name: "offsetAnchor", kind: PropertyValueKind::Position },
    PropertyValueEntry { name: "offsetPosition", kind: PropertyValueKind::Position },
    PropertyValueEntry { name: "opacity", kind: PropertyValueKind::Numeric },
    PropertyValueEntry { name: "order", kind: PropertyValueKind::Numeric },
    PropertyValueEntry { name: "orphans", kind: PropertyValueKind::Numeric },
    PropertyValueEntry { name: "outlineColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "outlineOffset", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "outlineStyle", kind: PropertyValueKind::Keywords { keywords: &["auto", "dashed", "dotted", "double", "groove", "inset", "none", "outset", "ridge", "solid"], open: false } },
    PropertyValueEntry { name: "outlineWidth", kind: PropertyValueKind::LineWidth },
    PropertyValueEntry { name: "overflow", kind: PropertyValueKind::Overflow { open: true } },
    PropertyValueEntry { name: "overflowBlock", kind: PropertyValueKind::OverflowShort },
    PropertyValueEntry { name: "overflowClipMargin", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "overflowInline", kind: PropertyValueKind::OverflowShort },
    PropertyValueEntry { name: "overflowX", kind: PropertyValueKind::Overflow { open: false } },
    PropertyValueEntry { name: "overflowY", kind: PropertyValueKind::Overflow { open: false } },
    PropertyValueEntry { name: "overscrollBehavior", kind: PropertyValueKind::OverscrollBehavior { open: true } },
    PropertyValueEntry { name: "overscrollBehaviorX", kind: PropertyValueKind::OverscrollBehavior { open: false } },
    PropertyValueEntry { name: "overscrollBehaviorY", kind: PropertyValueKind::OverscrollBehavior { open: false } },
    PropertyValueEntry { name: "padding", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "paddingBottom", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "paddingLeft", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "paddingRight", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "paddingTop", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "pageBreakAfter", kind: PropertyValueKind::Keywords { keywords: &["always", "auto", "avoid", "left", "recto", "right", "verso"], open: false } },
    PropertyValueEntry { name: "pageBreakBefore", kind: PropertyValueKind::Keywords { keywords: &["always", "auto", "avoid", "left", "recto", "right", "verso"], open: false } },
    PropertyValueEntry { name: "perspective", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "perspectiveOrigin", kind: PropertyValueKind::Position },
    PropertyValueEntry { name: "placeContent", kind: PropertyValueKind::Keywords { keywords: &["baseline", "center", "end", "flex-end", "flex-start", "normal", "space-around", "space-between", "space-evenly", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "placeItems", kind: PropertyValueKind::Keywords { keywords: &["anchor-center", "baseline", "center", "end", "flex-end", "flex-start", "normal", "self-end", "self-start", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "placeSelf", kind: PropertyValueKind::Keywords { keywords: &["anchor-center", "auto", "baseline", "center", "end", "flex-end", "flex-start", "normal", "self-end", "self-start", "start", "stretch"], open: true } },
    PropertyValueEntry { name: "pointerEvents", kind: PropertyValueKind::Keywords { keywords: &["all", "auto", "fill", "none", "painted", "stroke", "visible", "visibleFill", "visiblePainted", "visibleStroke"], open: false } },
    PropertyValueEntry { name: "position", kind: PropertyValueKind::Keywords { keywords: &["-webkit-sticky", "absolute", "fixed", "relative", "static", "sticky"], open: false } },
    PropertyValueEntry { name: "positionTryOrder", kind: PropertyValueKind::Keywords { keywords: &["most-block-size", "most-height", "most-inline-size", "most-width", "normal"], open: false } },
    PropertyValueEntry { name: "resize", kind: PropertyValueKind::Keywords { keywords: &["block", "both", "horizontal", "inline", "none", "vertical"], open: false } },
    PropertyValueEntry { name: "right", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "rowGap", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginBlock", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginBlockEnd", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginBlockStart", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginBottom", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginInline", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginInlineEnd", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginInlineStart", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginLeft", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginRight", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollMarginTop", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingBlock", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingBlockEnd", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingBlockStart", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingBottom", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingInline", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingInlineEnd", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingInlineStart", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingLeft", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingRight", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollPaddingTop", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "scrollSnapAlign", kind: PropertyValueKind::Keywords { keywords: &["center", "end", "none", "start"], open: true } },
    PropertyValueEntry { name: "scrollSnapDestination", kind: PropertyValueKind::Position },
    PropertyValueEntry { name: "scrollSnapStop", kind: PropertyValueKind::Keywords { keywords: &["always", "normal"], open: false } },
    PropertyValueEntry { name: "scrollSnapType", kind: PropertyValueKind::Keywords { keywords: &["block", "both", "inline", "none", "x", "y"], open: true } },
    PropertyValueEntry { name: "shapeMargin", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "shapeOutside", kind: PropertyValueKind::Keywords { keywords: &["border-box", "content-box", "margin-box", "none", "padding-box"], open: true } },
    PropertyValueEntry { name: "speakAs", kind: PropertyValueKind::Keywords { keywords: &["digits", "literal-punctuation", "no-punctuation", "normal", "spell-out"], open: true } },
    PropertyValueEntry { name: "stopColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "strokeColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "strokeLinejoin", kind: PropertyValueKind::Keywords { keywords: &["arcs", "bevel", "miter", "miter-clip", "round"], open: false } },
    PropertyValueEntry { name: "strokeWidth", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "tabSize", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "tableLayout", kind: PropertyValueKind::Keywords { keywords: &["auto", "fixed"], open: false } },
    PropertyValueEntry { name: "textAlign", kind: PropertyValueKind::Keywords { keywords: &["-khtml-center", "-khtml-left", "-khtml-right", "-moz-center", "-moz-left", "-moz-right", "-webkit-center", "-webkit-left", "-webkit-match-parent", "-webkit-right", "center", "end", "justify", "left", "match-parent", "right", "start"], open: false } },
    PropertyValueEntry { name: "textAlignLast", kind: PropertyValueKind::Keywords { keywords: &["auto", "center", "end", "justify", "left", "right", "start"], open: false } },
    PropertyValueEntry { name: "textAutospace", kind: PropertyValueKind::Keywords { keywords: &["auto", "ideograph-alpha", "ideograph-numeric", "insert", "no-autospace", "normal", "punctuation", "replace"], open: true } },
    PropertyValueEntry { name: "textBox", kind: PropertyValueKind::Keywords { keywords: &["auto", "cap", "ex", "ideographic", "ideographic-ink", "none", "normal", "text", "trim-both", "trim-end", "trim-start"], open: true } },
    PropertyValueEntry { name: "textBoxEdge", kind: PropertyValueKind::Keywords { keywords: &["auto", "cap", "ex", "ideographic", "ideographic-ink", "text"], open: true } },
    PropertyValueEntry { name: "textDecorationColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "textDecorationLine", kind: PropertyValueKind::Keywords { keywords: &["blink", "grammar-error", "line-through", "none", "overline", "spelling-error", "underline"], open: true } },
    PropertyValueEntry { name: "textDecorationSkip", kind: PropertyValueKind::Keywords { keywords: &["box-decoration", "edges", "leading-spaces", "none", "objects", "spaces", "trailing-spaces"], open: true } },
    PropertyValueEntry { name: "textDecorationSkipInk", kind: PropertyValueKind::Keywords { keywords: &["all", "auto", "none"], open: false } },
    PropertyValueEntry { name: "textDecorationStyle", kind: PropertyValueKind::Keywords { keywords: &["dashed", "dotted", "double", "solid", "wavy"], open: false } },
    PropertyValueEntry { name: "textDecorationThickness", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "textEmphasis", kind: PropertyValueKind::Keywords { keywords: &["circle", "currentColor", "dot", "double-circle", "filled", "none", "open", "sesame", "triangle"], open: true } },
    PropertyValueEntry { name: "textEmphasisColor", kind: PropertyValueKind::Color },
    PropertyValueEntry { name: "textEmphasisPosition", kind: PropertyValueKind::Keywords { keywords: &["auto", "over", "under"], open: true } },
    PropertyValueEntry { name: "textEmphasisStyle", kind: PropertyValueKind::Keywords { keywords: &["circle", "dot", "double-circle", "filled", "none", "open", "sesame", "triangle"], open: true } },
    PropertyValueEntry { name: "textIndent", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "textJustify", kind: PropertyValueKind::Keywords { keywords: &["auto", "distribute", "inter-character", "inter-word", "none"], open: false } },
    PropertyValueEntry { name: "textOrientation", kind: PropertyValueKind::Keywords { keywords: &["mixed", "sideways", "sideways-right", "upright"], open: false } },
    PropertyValueEntry { name: "textOverflow", kind: PropertyValueKind::Keywords { keywords: &["clip", "ellipsis"], open: true } },
    PropertyValueEntry { name: "textRendering", kind: PropertyValueKind::Keywords { keywords: &["auto", "geometricPrecision", "optimizeLegibility", "optimizeSpeed"], open: false } },
    PropertyValueEntry { name: "textSizeAdjust", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "textTransform", kind: PropertyValueKind::Keywords { keywords: &["capitalize", "full-size-kana", "full-width", "lowercase", "math-auto", "none", "uppercase"], open: true } },
    PropertyValueEntry { name: "textUnderlineOffset", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "textUnderlinePosition", kind: PropertyValueKind::Keywords { keywords: &["auto", "from-font", "left", "right", "under"], open: true } },
    PropertyValueEntry { name: "textWrap", kind: PropertyValueKind::Keywords { keywords: &["auto", "balance", "nowrap", "pretty", "stable", "wrap"], open: true } },
    PropertyValueEntry { name: "textWrapMode", kind: PropertyValueKind::Keywords { keywords: &["nowrap", "wrap"], open: false } },
    PropertyValueEntry { name: "textWrapStyle", kind: PropertyValueKind::Keywords { keywords: &["auto", "balance", "pretty", "stable"], open: false } },
    PropertyValueEntry { name: "top", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "touchAction", kind: PropertyValueKind::Keywords { keywords: &["-ms-manipulation", "-ms-none", "-ms-pan-x", "-ms-pan-y", "-ms-pinch-zoom", "auto", "manipulation", "none", "pan-down", "pan-left", "pan-right", "pan-up", "pan-x", "pan-y", "pinch-zoom"], open: true } },
    PropertyValueEntry { name: "transformBox", kind: PropertyValueKind::Keywords { keywords: &["border-box", "content-box", "fill-box", "stroke-box", "view-box"], open: false } },
    PropertyValueEntry { name: "transitionBehavior", kind: PropertyValueKind::Keywords { keywords: &["allow-discrete", "normal"], open: true } },
    PropertyValueEntry { name: "transitionProperty", kind: PropertyValueKind::Keywords { keywords: &["all", "none"], open: true } },
    PropertyValueEntry { name: "unicodeBidi", kind: PropertyValueKind::Keywords { keywords: &["-moz-isolate", "-moz-isolate-override", "-moz-plaintext", "-webkit-isolate", "-webkit-isolate-override", "-webkit-plaintext", "bidi-override", "embed", "isolate", "isolate-override", "normal", "plaintext"], open: false } },
    PropertyValueEntry { name: "userSelect", kind: PropertyValueKind::Keywords { keywords: &["-moz-none", "all", "auto", "none", "text"], open: false } },
    PropertyValueEntry { name: "vectorEffect", kind: PropertyValueKind::Keywords { keywords: &["fixed-position", "non-rotation", "non-scaling-size", "non-scaling-stroke", "none"], open: false } },
    PropertyValueEntry { name: "verticalAlign", kind: PropertyValueKind::Keywords { keywords: &["baseline", "bottom", "middle", "sub", "super", "text-bottom", "text-top", "top"], open: true } },
    PropertyValueEntry { name: "viewTimelineInset", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "whiteSpace", kind: PropertyValueKind::Keywords { keywords: &["-moz-pre-wrap", "break-spaces", "collapse", "normal", "nowrap", "pre", "pre-line", "pre-wrap", "preserve", "preserve-breaks", "preserve-spaces", "wrap"], open: true } },
    PropertyValueEntry { name: "whiteSpaceCollapse", kind: PropertyValueKind::Keywords { keywords: &["break-spaces", "collapse", "preserve", "preserve-breaks", "preserve-spaces"], open: false } },
    PropertyValueEntry { name: "widows", kind: PropertyValueKind::Numeric },
    PropertyValueEntry { name: "width", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "wordBreak", kind: PropertyValueKind::Keywords { keywords: &["auto-phrase", "break-all", "break-word", "keep-all", "normal"], open: false } },
    PropertyValueEntry { name: "wordSpacing", kind: PropertyValueKind::Length },
    PropertyValueEntry { name: "wordWrap", kind: PropertyValueKind::Keywords { keywords: &["break-word", "normal"], open: false } },
    PropertyValueEntry { name: "writingMode", kind: PropertyValueKind::Keywords { keywords: &["horizontal-tb", "sideways-lr", "sideways-rl", "vertical-lr", "vertical-rl"], open: false } },
    PropertyValueEntry { name: "zIndex", kind: PropertyValueKind::ZIndex },
    PropertyValueEntry { name: "zoom", kind: PropertyValueKind::Numeric },
];
// @generated-end

pub(crate) fn property_value_entry(property: &str) -> Option<&'static PropertyValueEntry> {
    PROPERTY_VALUES
        .binary_search_by(|entry| entry.name.cmp(property))
        .ok()
        .map(|index| &PROPERTY_VALUES[index])
}

/// v1 `strictPropertyList` — only these props narrow under `strictPropertyValues`.
pub(crate) const STRICT_PROPERTY_LIST: &[&str] = &[
    "alignContent",
    "alignItems",
    "alignSelf",
    "all",
    "animationComposition",
    "animationDirection",
    "animationFillMode",
    "appearance",
    "backfaceVisibility",
    "backgroundAttachment",
    "backgroundClip",
    "borderCollapse",
    "borderBlockEndStyle",
    "borderBlockStartStyle",
    "borderBlockStyle",
    "borderBottomStyle",
    "borderInlineEndStyle",
    "borderInlineStartStyle",
    "borderInlineStyle",
    "borderLeftStyle",
    "borderRightStyle",
    "borderTopStyle",
    "boxDecorationBreak",
    "boxSizing",
    "breakAfter",
    "breakBefore",
    "breakInside",
    "captionSide",
    "clear",
    "columnFill",
    "columnRuleStyle",
    "contentVisibility",
    "direction",
    "display",
    "emptyCells",
    "flexDirection",
    "flexWrap",
    "float",
    "fontKerning",
    "forcedColorAdjust",
    "isolation",
    "lineBreak",
    "mixBlendMode",
    "objectFit",
    "outlineStyle",
    "overflow",
    "overflowX",
    "overflowY",
    "overflowBlock",
    "overflowInline",
    "overflowWrap",
    "pointerEvents",
    "position",
    "resize",
    "scrollBehavior",
    "touchAction",
    "transformBox",
    "transformStyle",
    "userSelect",
    "visibility",
    "wordBreak",
    "writingMode",
];

pub(crate) fn is_strict_property_list(property: &str) -> bool {
    STRICT_PROPERTY_LIST.binary_search(&property).is_ok()
}
