import { PropValue } from './prop-type'

export type StyleProps = {
  	MsAccelerator?: PropValue<'MsAccelerator'>
	MsBlockProgression?: PropValue<'MsBlockProgression'>
	MsContentZoomChaining?: PropValue<'MsContentZoomChaining'>
	MsContentZooming?: PropValue<'MsContentZooming'>
	MsContentZoomLimit?: PropValue<'MsContentZoomLimit'>
	MsContentZoomLimitMax?: PropValue<'MsContentZoomLimitMax'>
	MsContentZoomLimitMin?: PropValue<'MsContentZoomLimitMin'>
	MsContentZoomSnap?: PropValue<'MsContentZoomSnap'>
	MsContentZoomSnapPoints?: PropValue<'MsContentZoomSnapPoints'>
	MsContentZoomSnapType?: PropValue<'MsContentZoomSnapType'>
	MsFilter?: PropValue<'MsFilter'>
	MsFlowFrom?: PropValue<'MsFlowFrom'>
	MsFlowInto?: PropValue<'MsFlowInto'>
	MsGridColumns?: PropValue<'MsGridColumns'>
	MsGridRows?: PropValue<'MsGridRows'>
	MsHighContrastAdjust?: PropValue<'MsHighContrastAdjust'>
	MsHyphenateLimitChars?: PropValue<'MsHyphenateLimitChars'>
	MsHyphenateLimitLines?: PropValue<'MsHyphenateLimitLines'>
	MsHyphenateLimitZone?: PropValue<'MsHyphenateLimitZone'>
	MsImeAlign?: PropValue<'MsImeAlign'>
	MsOverflowStyle?: PropValue<'MsOverflowStyle'>
	MsScrollbar3dlightColor?: PropValue<'MsScrollbar3dlightColor'>
	MsScrollbarArrowColor?: PropValue<'MsScrollbarArrowColor'>
	MsScrollbarBaseColor?: PropValue<'MsScrollbarBaseColor'>
	MsScrollbarDarkshadowColor?: PropValue<'MsScrollbarDarkshadowColor'>
	MsScrollbarFaceColor?: PropValue<'MsScrollbarFaceColor'>
	MsScrollbarHighlightColor?: PropValue<'MsScrollbarHighlightColor'>
	MsScrollbarShadowColor?: PropValue<'MsScrollbarShadowColor'>
	MsScrollbarTrackColor?: PropValue<'MsScrollbarTrackColor'>
	MsScrollChaining?: PropValue<'MsScrollChaining'>
	MsScrollLimit?: PropValue<'MsScrollLimit'>
	MsScrollLimitXMax?: PropValue<'MsScrollLimitXMax'>
	MsScrollLimitXMin?: PropValue<'MsScrollLimitXMin'>
	MsScrollLimitYMax?: PropValue<'MsScrollLimitYMax'>
	MsScrollLimitYMin?: PropValue<'MsScrollLimitYMin'>
	MsScrollRails?: PropValue<'MsScrollRails'>
	MsScrollSnapPointsX?: PropValue<'MsScrollSnapPointsX'>
	MsScrollSnapPointsY?: PropValue<'MsScrollSnapPointsY'>
	MsScrollSnapType?: PropValue<'MsScrollSnapType'>
	MsScrollSnapX?: PropValue<'MsScrollSnapX'>
	MsScrollSnapY?: PropValue<'MsScrollSnapY'>
	MsScrollTranslation?: PropValue<'MsScrollTranslation'>
	MsTextAutospace?: PropValue<'MsTextAutospace'>
	MsTouchSelect?: PropValue<'MsTouchSelect'>
	MsUserSelect?: PropValue<'MsUserSelect'>
	MsWrapFlow?: PropValue<'MsWrapFlow'>
	MsWrapMargin?: PropValue<'MsWrapMargin'>
	MsWrapThrough?: PropValue<'MsWrapThrough'>
	MozAppearance?: PropValue<'MozAppearance'>
	MozBinding?: PropValue<'MozBinding'>
	MozBorderBottomColors?: PropValue<'MozBorderBottomColors'>
	MozBorderLeftColors?: PropValue<'MozBorderLeftColors'>
	MozBorderRightColors?: PropValue<'MozBorderRightColors'>
	MozBorderTopColors?: PropValue<'MozBorderTopColors'>
	MozContextProperties?: PropValue<'MozContextProperties'>
	MozFloatEdge?: PropValue<'MozFloatEdge'>
	MozForceBrokenImageIcon?: PropValue<'MozForceBrokenImageIcon'>
	MozImageRegion?: PropValue<'MozImageRegion'>
	MozOrient?: PropValue<'MozOrient'>
	MozOutlineRadius?: PropValue<'MozOutlineRadius'>
	MozOutlineRadiusBottomleft?: PropValue<'MozOutlineRadiusBottomleft'>
	MozOutlineRadiusBottomright?: PropValue<'MozOutlineRadiusBottomright'>
	MozOutlineRadiusTopleft?: PropValue<'MozOutlineRadiusTopleft'>
	MozOutlineRadiusTopright?: PropValue<'MozOutlineRadiusTopright'>
	MozStackSizing?: PropValue<'MozStackSizing'>
	MozTextBlink?: PropValue<'MozTextBlink'>
	MozUserFocus?: PropValue<'MozUserFocus'>
	MozUserInput?: PropValue<'MozUserInput'>
	MozUserModify?: PropValue<'MozUserModify'>
	MozWindowDragging?: PropValue<'MozWindowDragging'>
	MozWindowShadow?: PropValue<'MozWindowShadow'>
	WebkitAppearance?: PropValue<'WebkitAppearance'>
	WebkitBorderBefore?: PropValue<'WebkitBorderBefore'>
	WebkitBorderBeforeColor?: PropValue<'WebkitBorderBeforeColor'>
	WebkitBorderBeforeStyle?: PropValue<'WebkitBorderBeforeStyle'>
	WebkitBorderBeforeWidth?: PropValue<'WebkitBorderBeforeWidth'>
	WebkitBoxReflect?: PropValue<'WebkitBoxReflect'>
	WebkitLineClamp?: PropValue<'WebkitLineClamp'>
	WebkitMask?: PropValue<'WebkitMask'>
	WebkitMaskAttachment?: PropValue<'WebkitMaskAttachment'>
	WebkitMaskClip?: PropValue<'WebkitMaskClip'>
	WebkitMaskComposite?: PropValue<'WebkitMaskComposite'>
	WebkitMaskImage?: PropValue<'WebkitMaskImage'>
	WebkitMaskOrigin?: PropValue<'WebkitMaskOrigin'>
	WebkitMaskPosition?: PropValue<'WebkitMaskPosition'>
	WebkitMaskPositionX?: PropValue<'WebkitMaskPositionX'>
	WebkitMaskPositionY?: PropValue<'WebkitMaskPositionY'>
	WebkitMaskRepeat?: PropValue<'WebkitMaskRepeat'>
	WebkitMaskRepeatX?: PropValue<'WebkitMaskRepeatX'>
	WebkitMaskRepeatY?: PropValue<'WebkitMaskRepeatY'>
	WebkitMaskSize?: PropValue<'WebkitMaskSize'>
	WebkitOverflowScrolling?: PropValue<'WebkitOverflowScrolling'>
	WebkitTapHighlightColor?: PropValue<'WebkitTapHighlightColor'>
	WebkitTextFillColor?: PropValue<'WebkitTextFillColor'>
	WebkitTextStroke?: PropValue<'WebkitTextStroke'>
	WebkitTextStrokeColor?: PropValue<'WebkitTextStrokeColor'>
	WebkitTextStrokeWidth?: PropValue<'WebkitTextStrokeWidth'>
	WebkitTouchCallout?: PropValue<'WebkitTouchCallout'>
	WebkitUserModify?: PropValue<'WebkitUserModify'>
	accentColor?: PropValue<'accentColor'>
	alignContent?: PropValue<'alignContent'>
	alignItems?: PropValue<'alignItems'>
	alignSelf?: PropValue<'alignSelf'>
	alignTracks?: PropValue<'alignTracks'>
	all?: PropValue<'all'>
	animation?: PropValue<'animation'>
	animationComposition?: PropValue<'animationComposition'>
	animationDelay?: PropValue<'animationDelay'>
	animationDirection?: PropValue<'animationDirection'>
	animationDuration?: PropValue<'animationDuration'>
	animationFillMode?: PropValue<'animationFillMode'>
	animationIterationCount?: PropValue<'animationIterationCount'>
	animationName?: PropValue<'animationName'>
	animationPlayState?: PropValue<'animationPlayState'>
	animationTimingFunction?: PropValue<'animationTimingFunction'>
	animationTimeline?: PropValue<'animationTimeline'>
	appearance?: PropValue<'appearance'>
	aspectRatio?: PropValue<'aspectRatio'>
	azimuth?: PropValue<'azimuth'>
	backdropFilter?: PropValue<'backdropFilter'>
	backfaceVisibility?: PropValue<'backfaceVisibility'>
	background?: PropValue<'background'>
	backgroundAttachment?: PropValue<'backgroundAttachment'>
	backgroundBlendMode?: PropValue<'backgroundBlendMode'>
	backgroundClip?: PropValue<'backgroundClip'>
	backgroundColor?: PropValue<'backgroundColor'>
	backgroundImage?: PropValue<'backgroundImage'>
	backgroundOrigin?: PropValue<'backgroundOrigin'>
	backgroundPosition?: PropValue<'backgroundPosition'>
	backgroundPositionX?: PropValue<'backgroundPositionX'>
	backgroundPositionY?: PropValue<'backgroundPositionY'>
	backgroundRepeat?: PropValue<'backgroundRepeat'>
	backgroundSize?: PropValue<'backgroundSize'>
	blockOverflow?: PropValue<'blockOverflow'>
	blockSize?: PropValue<'blockSize'>
	border?: PropValue<'border'>
	borderBlock?: PropValue<'borderBlock'>
	borderBlockColor?: PropValue<'borderBlockColor'>
	borderBlockStyle?: PropValue<'borderBlockStyle'>
	borderBlockWidth?: PropValue<'borderBlockWidth'>
	borderBlockEnd?: PropValue<'borderBlockEnd'>
	borderBlockEndColor?: PropValue<'borderBlockEndColor'>
	borderBlockEndStyle?: PropValue<'borderBlockEndStyle'>
	borderBlockEndWidth?: PropValue<'borderBlockEndWidth'>
	borderBlockStart?: PropValue<'borderBlockStart'>
	borderBlockStartColor?: PropValue<'borderBlockStartColor'>
	borderBlockStartStyle?: PropValue<'borderBlockStartStyle'>
	borderBlockStartWidth?: PropValue<'borderBlockStartWidth'>
	borderBottom?: PropValue<'borderBottom'>
	borderBottomColor?: PropValue<'borderBottomColor'>
	borderBottomLeftRadius?: PropValue<'borderBottomLeftRadius'>
	borderBottomRightRadius?: PropValue<'borderBottomRightRadius'>
	borderBottomStyle?: PropValue<'borderBottomStyle'>
	borderBottomWidth?: PropValue<'borderBottomWidth'>
	borderCollapse?: PropValue<'borderCollapse'>
	borderColor?: PropValue<'borderColor'>
	borderEndEndRadius?: PropValue<'borderEndEndRadius'>
	borderEndStartRadius?: PropValue<'borderEndStartRadius'>
	borderImage?: PropValue<'borderImage'>
	borderImageOutset?: PropValue<'borderImageOutset'>
	borderImageRepeat?: PropValue<'borderImageRepeat'>
	borderImageSlice?: PropValue<'borderImageSlice'>
	borderImageSource?: PropValue<'borderImageSource'>
	borderImageWidth?: PropValue<'borderImageWidth'>
	borderInline?: PropValue<'borderInline'>
	borderInlineEnd?: PropValue<'borderInlineEnd'>
	borderInlineColor?: PropValue<'borderInlineColor'>
	borderInlineStyle?: PropValue<'borderInlineStyle'>
	borderInlineWidth?: PropValue<'borderInlineWidth'>
	borderInlineEndColor?: PropValue<'borderInlineEndColor'>
	borderInlineEndStyle?: PropValue<'borderInlineEndStyle'>
	borderInlineEndWidth?: PropValue<'borderInlineEndWidth'>
	borderInlineStart?: PropValue<'borderInlineStart'>
	borderInlineStartColor?: PropValue<'borderInlineStartColor'>
	borderInlineStartStyle?: PropValue<'borderInlineStartStyle'>
	borderInlineStartWidth?: PropValue<'borderInlineStartWidth'>
	borderLeft?: PropValue<'borderLeft'>
	borderLeftColor?: PropValue<'borderLeftColor'>
	borderLeftStyle?: PropValue<'borderLeftStyle'>
	borderLeftWidth?: PropValue<'borderLeftWidth'>
	borderRadius?: PropValue<'borderRadius'>
	borderRight?: PropValue<'borderRight'>
	borderRightColor?: PropValue<'borderRightColor'>
	borderRightStyle?: PropValue<'borderRightStyle'>
	borderRightWidth?: PropValue<'borderRightWidth'>
	borderSpacing?: PropValue<'borderSpacing'>
	borderStartEndRadius?: PropValue<'borderStartEndRadius'>
	borderStartStartRadius?: PropValue<'borderStartStartRadius'>
	borderStyle?: PropValue<'borderStyle'>
	borderTop?: PropValue<'borderTop'>
	borderTopColor?: PropValue<'borderTopColor'>
	borderTopLeftRadius?: PropValue<'borderTopLeftRadius'>
	borderTopRightRadius?: PropValue<'borderTopRightRadius'>
	borderTopStyle?: PropValue<'borderTopStyle'>
	borderTopWidth?: PropValue<'borderTopWidth'>
	borderWidth?: PropValue<'borderWidth'>
	bottom?: PropValue<'bottom'>
	boxAlign?: PropValue<'boxAlign'>
	boxDecorationBreak?: PropValue<'boxDecorationBreak'>
	boxDirection?: PropValue<'boxDirection'>
	boxFlex?: PropValue<'boxFlex'>
	boxFlexGroup?: PropValue<'boxFlexGroup'>
	boxLines?: PropValue<'boxLines'>
	boxOrdinalGroup?: PropValue<'boxOrdinalGroup'>
	boxOrient?: PropValue<'boxOrient'>
	boxPack?: PropValue<'boxPack'>
	boxShadow?: PropValue<'boxShadow'>
	boxSizing?: PropValue<'boxSizing'>
	breakAfter?: PropValue<'breakAfter'>
	breakBefore?: PropValue<'breakBefore'>
	breakInside?: PropValue<'breakInside'>
	captionSide?: PropValue<'captionSide'>
	caret?: PropValue<'caret'>
	caretColor?: PropValue<'caretColor'>
	caretShape?: PropValue<'caretShape'>
	clear?: PropValue<'clear'>
	clip?: PropValue<'clip'>
	clipPath?: PropValue<'clipPath'>
	color?: PropValue<'color'>
	printColorAdjust?: PropValue<'printColorAdjust'>
	colorScheme?: PropValue<'colorScheme'>
	columnCount?: PropValue<'columnCount'>
	columnFill?: PropValue<'columnFill'>
	columnGap?: PropValue<'columnGap'>
	columnRule?: PropValue<'columnRule'>
	columnRuleColor?: PropValue<'columnRuleColor'>
	columnRuleStyle?: PropValue<'columnRuleStyle'>
	columnRuleWidth?: PropValue<'columnRuleWidth'>
	columnSpan?: PropValue<'columnSpan'>
	columnWidth?: PropValue<'columnWidth'>
	columns?: PropValue<'columns'>
	contain?: PropValue<'contain'>
	containIntrinsicSize?: PropValue<'containIntrinsicSize'>
	containIntrinsicBlockSize?: PropValue<'containIntrinsicBlockSize'>
	containIntrinsicHeight?: PropValue<'containIntrinsicHeight'>
	containIntrinsicInlineSize?: PropValue<'containIntrinsicInlineSize'>
	containIntrinsicWidth?: PropValue<'containIntrinsicWidth'>
	content?: PropValue<'content'>
	contentVisibility?: PropValue<'contentVisibility'>
	counterIncrement?: PropValue<'counterIncrement'>
	counterReset?: PropValue<'counterReset'>
	counterSet?: PropValue<'counterSet'>
	cursor?: PropValue<'cursor'>
	direction?: PropValue<'direction'>
	display?: PropValue<'display'>
	emptyCells?: PropValue<'emptyCells'>
	filter?: PropValue<'filter'>
	flex?: PropValue<'flex'>
	flexBasis?: PropValue<'flexBasis'>
	flexDirection?: PropValue<'flexDirection'>
	flexFlow?: PropValue<'flexFlow'>
	flexGrow?: PropValue<'flexGrow'>
	flexShrink?: PropValue<'flexShrink'>
	flexWrap?: PropValue<'flexWrap'>
	float?: PropValue<'float'>
	font?: PropValue<'font'>
	fontFamily?: PropValue<'fontFamily'>
	fontFeatureSettings?: PropValue<'fontFeatureSettings'>
	fontKerning?: PropValue<'fontKerning'>
	fontLanguageOverride?: PropValue<'fontLanguageOverride'>
	fontOpticalSizing?: PropValue<'fontOpticalSizing'>
	fontVariationSettings?: PropValue<'fontVariationSettings'>
	fontSize?: PropValue<'fontSize'>
	fontSizeAdjust?: PropValue<'fontSizeAdjust'>
	fontSmooth?: PropValue<'fontSmooth'>
	fontStretch?: PropValue<'fontStretch'>
	fontStyle?: PropValue<'fontStyle'>
	fontSynthesis?: PropValue<'fontSynthesis'>
	fontVariant?: PropValue<'fontVariant'>
	fontVariantAlternates?: PropValue<'fontVariantAlternates'>
	fontVariantCaps?: PropValue<'fontVariantCaps'>
	fontVariantEastAsian?: PropValue<'fontVariantEastAsian'>
	fontVariantLigatures?: PropValue<'fontVariantLigatures'>
	fontVariantNumeric?: PropValue<'fontVariantNumeric'>
	fontVariantPosition?: PropValue<'fontVariantPosition'>
	fontWeight?: PropValue<'fontWeight'>
	forcedColorAdjust?: PropValue<'forcedColorAdjust'>
	gap?: PropValue<'gap'>
	grid?: PropValue<'grid'>
	gridArea?: PropValue<'gridArea'>
	gridAutoColumns?: PropValue<'gridAutoColumns'>
	gridAutoFlow?: PropValue<'gridAutoFlow'>
	gridAutoRows?: PropValue<'gridAutoRows'>
	gridColumn?: PropValue<'gridColumn'>
	gridColumnEnd?: PropValue<'gridColumnEnd'>
	gridColumnGap?: PropValue<'gridColumnGap'>
	gridColumnStart?: PropValue<'gridColumnStart'>
	gridGap?: PropValue<'gridGap'>
	gridRow?: PropValue<'gridRow'>
	gridRowEnd?: PropValue<'gridRowEnd'>
	gridRowGap?: PropValue<'gridRowGap'>
	gridRowStart?: PropValue<'gridRowStart'>
	gridTemplate?: PropValue<'gridTemplate'>
	gridTemplateAreas?: PropValue<'gridTemplateAreas'>
	gridTemplateColumns?: PropValue<'gridTemplateColumns'>
	gridTemplateRows?: PropValue<'gridTemplateRows'>
	hangingPunctuation?: PropValue<'hangingPunctuation'>
	height?: PropValue<'height'>
	hyphenateCharacter?: PropValue<'hyphenateCharacter'>
	hyphens?: PropValue<'hyphens'>
	imageOrientation?: PropValue<'imageOrientation'>
	imageRendering?: PropValue<'imageRendering'>
	imageResolution?: PropValue<'imageResolution'>
	imeMode?: PropValue<'imeMode'>
	initialLetter?: PropValue<'initialLetter'>
	initialLetterAlign?: PropValue<'initialLetterAlign'>
	inlineSize?: PropValue<'inlineSize'>
	inputSecurity?: PropValue<'inputSecurity'>
	inset?: PropValue<'inset'>
	insetBlock?: PropValue<'insetBlock'>
	insetBlockEnd?: PropValue<'insetBlockEnd'>
	insetBlockStart?: PropValue<'insetBlockStart'>
	insetInline?: PropValue<'insetInline'>
	insetInlineEnd?: PropValue<'insetInlineEnd'>
	insetInlineStart?: PropValue<'insetInlineStart'>
	isolation?: PropValue<'isolation'>
	justifyContent?: PropValue<'justifyContent'>
	justifyItems?: PropValue<'justifyItems'>
	justifySelf?: PropValue<'justifySelf'>
	justifyTracks?: PropValue<'justifyTracks'>
	left?: PropValue<'left'>
	letterSpacing?: PropValue<'letterSpacing'>
	lineBreak?: PropValue<'lineBreak'>
	lineClamp?: PropValue<'lineClamp'>
	lineHeight?: PropValue<'lineHeight'>
	lineHeightStep?: PropValue<'lineHeightStep'>
	listStyle?: PropValue<'listStyle'>
	listStyleImage?: PropValue<'listStyleImage'>
	listStylePosition?: PropValue<'listStylePosition'>
	listStyleType?: PropValue<'listStyleType'>
	margin?: PropValue<'margin'>
	marginBlock?: PropValue<'marginBlock'>
	marginBlockEnd?: PropValue<'marginBlockEnd'>
	marginBlockStart?: PropValue<'marginBlockStart'>
	marginBottom?: PropValue<'marginBottom'>
	marginInline?: PropValue<'marginInline'>
	marginInlineEnd?: PropValue<'marginInlineEnd'>
	marginInlineStart?: PropValue<'marginInlineStart'>
	marginLeft?: PropValue<'marginLeft'>
	marginRight?: PropValue<'marginRight'>
	marginTop?: PropValue<'marginTop'>
	marginTrim?: PropValue<'marginTrim'>
	mask?: PropValue<'mask'>
	maskBorder?: PropValue<'maskBorder'>
	maskBorderMode?: PropValue<'maskBorderMode'>
	maskBorderOutset?: PropValue<'maskBorderOutset'>
	maskBorderRepeat?: PropValue<'maskBorderRepeat'>
	maskBorderSlice?: PropValue<'maskBorderSlice'>
	maskBorderSource?: PropValue<'maskBorderSource'>
	maskBorderWidth?: PropValue<'maskBorderWidth'>
	maskClip?: PropValue<'maskClip'>
	maskComposite?: PropValue<'maskComposite'>
	maskImage?: PropValue<'maskImage'>
	maskMode?: PropValue<'maskMode'>
	maskOrigin?: PropValue<'maskOrigin'>
	maskPosition?: PropValue<'maskPosition'>
	maskRepeat?: PropValue<'maskRepeat'>
	maskSize?: PropValue<'maskSize'>
	maskType?: PropValue<'maskType'>
	masonryAutoFlow?: PropValue<'masonryAutoFlow'>
	mathDepth?: PropValue<'mathDepth'>
	mathShift?: PropValue<'mathShift'>
	mathStyle?: PropValue<'mathStyle'>
	maxBlockSize?: PropValue<'maxBlockSize'>
	maxHeight?: PropValue<'maxHeight'>
	maxInlineSize?: PropValue<'maxInlineSize'>
	maxLines?: PropValue<'maxLines'>
	maxWidth?: PropValue<'maxWidth'>
	minBlockSize?: PropValue<'minBlockSize'>
	minHeight?: PropValue<'minHeight'>
	minInlineSize?: PropValue<'minInlineSize'>
	minWidth?: PropValue<'minWidth'>
	mixBlendMode?: PropValue<'mixBlendMode'>
	objectFit?: PropValue<'objectFit'>
	objectPosition?: PropValue<'objectPosition'>
	offset?: PropValue<'offset'>
	offsetAnchor?: PropValue<'offsetAnchor'>
	offsetDistance?: PropValue<'offsetDistance'>
	offsetPath?: PropValue<'offsetPath'>
	offsetPosition?: PropValue<'offsetPosition'>
	offsetRotate?: PropValue<'offsetRotate'>
	opacity?: PropValue<'opacity'>
	order?: PropValue<'order'>
	orphans?: PropValue<'orphans'>
	outline?: PropValue<'outline'>
	outlineColor?: PropValue<'outlineColor'>
	outlineOffset?: PropValue<'outlineOffset'>
	outlineStyle?: PropValue<'outlineStyle'>
	outlineWidth?: PropValue<'outlineWidth'>
	overflow?: PropValue<'overflow'>
	overflowAnchor?: PropValue<'overflowAnchor'>
	overflowBlock?: PropValue<'overflowBlock'>
	overflowClipBox?: PropValue<'overflowClipBox'>
	overflowClipMargin?: PropValue<'overflowClipMargin'>
	overflowInline?: PropValue<'overflowInline'>
	overflowWrap?: PropValue<'overflowWrap'>
	overflowX?: PropValue<'overflowX'>
	overflowY?: PropValue<'overflowY'>
	overscrollBehavior?: PropValue<'overscrollBehavior'>
	overscrollBehaviorBlock?: PropValue<'overscrollBehaviorBlock'>
	overscrollBehaviorInline?: PropValue<'overscrollBehaviorInline'>
	overscrollBehaviorX?: PropValue<'overscrollBehaviorX'>
	overscrollBehaviorY?: PropValue<'overscrollBehaviorY'>
	padding?: PropValue<'padding'>
	paddingBlock?: PropValue<'paddingBlock'>
	paddingBlockEnd?: PropValue<'paddingBlockEnd'>
	paddingBlockStart?: PropValue<'paddingBlockStart'>
	paddingBottom?: PropValue<'paddingBottom'>
	paddingInline?: PropValue<'paddingInline'>
	paddingInlineEnd?: PropValue<'paddingInlineEnd'>
	paddingInlineStart?: PropValue<'paddingInlineStart'>
	paddingLeft?: PropValue<'paddingLeft'>
	paddingRight?: PropValue<'paddingRight'>
	paddingTop?: PropValue<'paddingTop'>
	pageBreakAfter?: PropValue<'pageBreakAfter'>
	pageBreakBefore?: PropValue<'pageBreakBefore'>
	pageBreakInside?: PropValue<'pageBreakInside'>
	paintOrder?: PropValue<'paintOrder'>
	perspective?: PropValue<'perspective'>
	perspectiveOrigin?: PropValue<'perspectiveOrigin'>
	placeContent?: PropValue<'placeContent'>
	placeItems?: PropValue<'placeItems'>
	placeSelf?: PropValue<'placeSelf'>
	pointerEvents?: PropValue<'pointerEvents'>
	position?: PropValue<'position'>
	quotes?: PropValue<'quotes'>
	resize?: PropValue<'resize'>
	right?: PropValue<'right'>
	rotate?: PropValue<'rotate'>
	rowGap?: PropValue<'rowGap'>
	rubyAlign?: PropValue<'rubyAlign'>
	rubyMerge?: PropValue<'rubyMerge'>
	rubyPosition?: PropValue<'rubyPosition'>
	scale?: PropValue<'scale'>
	scrollbarColor?: PropValue<'scrollbarColor'>
	scrollbarGutter?: PropValue<'scrollbarGutter'>
	scrollbarWidth?: PropValue<'scrollbarWidth'>
	scrollBehavior?: PropValue<'scrollBehavior'>
	scrollMargin?: PropValue<'scrollMargin'>
	scrollMarginBlock?: PropValue<'scrollMarginBlock'>
	scrollMarginBlockStart?: PropValue<'scrollMarginBlockStart'>
	scrollMarginBlockEnd?: PropValue<'scrollMarginBlockEnd'>
	scrollMarginBottom?: PropValue<'scrollMarginBottom'>
	scrollMarginInline?: PropValue<'scrollMarginInline'>
	scrollMarginInlineStart?: PropValue<'scrollMarginInlineStart'>
	scrollMarginInlineEnd?: PropValue<'scrollMarginInlineEnd'>
	scrollMarginLeft?: PropValue<'scrollMarginLeft'>
	scrollMarginRight?: PropValue<'scrollMarginRight'>
	scrollMarginTop?: PropValue<'scrollMarginTop'>
	scrollPadding?: PropValue<'scrollPadding'>
	scrollPaddingBlock?: PropValue<'scrollPaddingBlock'>
	scrollPaddingBlockStart?: PropValue<'scrollPaddingBlockStart'>
	scrollPaddingBlockEnd?: PropValue<'scrollPaddingBlockEnd'>
	scrollPaddingBottom?: PropValue<'scrollPaddingBottom'>
	scrollPaddingInline?: PropValue<'scrollPaddingInline'>
	scrollPaddingInlineStart?: PropValue<'scrollPaddingInlineStart'>
	scrollPaddingInlineEnd?: PropValue<'scrollPaddingInlineEnd'>
	scrollPaddingLeft?: PropValue<'scrollPaddingLeft'>
	scrollPaddingRight?: PropValue<'scrollPaddingRight'>
	scrollPaddingTop?: PropValue<'scrollPaddingTop'>
	scrollSnapAlign?: PropValue<'scrollSnapAlign'>
	scrollSnapCoordinate?: PropValue<'scrollSnapCoordinate'>
	scrollSnapDestination?: PropValue<'scrollSnapDestination'>
	scrollSnapPointsX?: PropValue<'scrollSnapPointsX'>
	scrollSnapPointsY?: PropValue<'scrollSnapPointsY'>
	scrollSnapStop?: PropValue<'scrollSnapStop'>
	scrollSnapType?: PropValue<'scrollSnapType'>
	scrollSnapTypeX?: PropValue<'scrollSnapTypeX'>
	scrollSnapTypeY?: PropValue<'scrollSnapTypeY'>
	scrollTimeline?: PropValue<'scrollTimeline'>
	scrollTimelineAxis?: PropValue<'scrollTimelineAxis'>
	scrollTimelineName?: PropValue<'scrollTimelineName'>
	shapeImageThreshold?: PropValue<'shapeImageThreshold'>
	shapeMargin?: PropValue<'shapeMargin'>
	shapeOutside?: PropValue<'shapeOutside'>
	tabSize?: PropValue<'tabSize'>
	tableLayout?: PropValue<'tableLayout'>
	textAlign?: PropValue<'textAlign'>
	textAlignLast?: PropValue<'textAlignLast'>
	textCombineUpright?: PropValue<'textCombineUpright'>
	textDecoration?: PropValue<'textDecoration'>
	textDecorationColor?: PropValue<'textDecorationColor'>
	textDecorationLine?: PropValue<'textDecorationLine'>
	textDecorationSkip?: PropValue<'textDecorationSkip'>
	textDecorationSkipInk?: PropValue<'textDecorationSkipInk'>
	textDecorationStyle?: PropValue<'textDecorationStyle'>
	textDecorationThickness?: PropValue<'textDecorationThickness'>
	textEmphasis?: PropValue<'textEmphasis'>
	textEmphasisColor?: PropValue<'textEmphasisColor'>
	textEmphasisPosition?: PropValue<'textEmphasisPosition'>
	textEmphasisStyle?: PropValue<'textEmphasisStyle'>
	textIndent?: PropValue<'textIndent'>
	textJustify?: PropValue<'textJustify'>
	textOrientation?: PropValue<'textOrientation'>
	textOverflow?: PropValue<'textOverflow'>
	textRendering?: PropValue<'textRendering'>
	textShadow?: PropValue<'textShadow'>
	textSizeAdjust?: PropValue<'textSizeAdjust'>
	textTransform?: PropValue<'textTransform'>
	textUnderlineOffset?: PropValue<'textUnderlineOffset'>
	textUnderlinePosition?: PropValue<'textUnderlinePosition'>
	top?: PropValue<'top'>
	touchAction?: PropValue<'touchAction'>
	transform?: PropValue<'transform'>
	transformBox?: PropValue<'transformBox'>
	transformOrigin?: PropValue<'transformOrigin'>
	transformStyle?: PropValue<'transformStyle'>
	transition?: PropValue<'transition'>
	transitionDelay?: PropValue<'transitionDelay'>
	transitionDuration?: PropValue<'transitionDuration'>
	transitionProperty?: PropValue<'transitionProperty'>
	transitionTimingFunction?: PropValue<'transitionTimingFunction'>
	translate?: PropValue<'translate'>
	unicodeBidi?: PropValue<'unicodeBidi'>
	userSelect?: PropValue<'userSelect'>
	verticalAlign?: PropValue<'verticalAlign'>
	visibility?: PropValue<'visibility'>
	whiteSpace?: PropValue<'whiteSpace'>
	widows?: PropValue<'widows'>
	width?: PropValue<'width'>
	willChange?: PropValue<'willChange'>
	wordBreak?: PropValue<'wordBreak'>
	wordSpacing?: PropValue<'wordSpacing'>
	wordWrap?: PropValue<'wordWrap'>
	writingMode?: PropValue<'writingMode'>
	zIndex?: PropValue<'zIndex'>
	zoom?: PropValue<'zoom'>
	pos?: PropValue<'pos'>
	flexDir?: PropValue<'flexDir'>
	p?: PropValue<'p'>
	pl?: PropValue<'pl'>
	pr?: PropValue<'pr'>
	pt?: PropValue<'pt'>
	pb?: PropValue<'pb'>
	pe?: PropValue<'pe'>
	ps?: PropValue<'ps'>
	px?: PropValue<'px'>
	py?: PropValue<'py'>
	ml?: PropValue<'ml'>
	mr?: PropValue<'mr'>
	mt?: PropValue<'mt'>
	mb?: PropValue<'mb'>
	m?: PropValue<'m'>
	mx?: PropValue<'mx'>
	my?: PropValue<'my'>
	me?: PropValue<'me'>
	ms?: PropValue<'ms'>
	w?: PropValue<'w'>
	h?: PropValue<'h'>
	minH?: PropValue<'minH'>
	maxH?: PropValue<'maxH'>
	minW?: PropValue<'minW'>
	maxW?: PropValue<'maxW'>
	bgAttachment?: PropValue<'bgAttachment'>
	bgClip?: PropValue<'bgClip'>
	bg?: PropValue<'bg'>
	bgColor?: PropValue<'bgColor'>
	bgPos?: PropValue<'bgPos'>
	bgOrigin?: PropValue<'bgOrigin'>
	bgImage?: PropValue<'bgImage'>
	bgRepeat?: PropValue<'bgRepeat'>
	bgBlend?: PropValue<'bgBlend'>
	bgSize?: PropValue<'bgSize'>
	bgGradient?: PropValue<'bgGradient'>
	shadow?: PropValue<'shadow'>
	shadowColor?: PropValue<'shadowColor'>
	x?: PropValue<'x'>
	y?: PropValue<'y'>
	start?: PropValue<'start'>
	end?: PropValue<'end'>
	insetX?: PropValue<'insetX'>
	insetY?: PropValue<'insetY'>
	paddingX?: PropValue<'paddingX'>
	paddingY?: PropValue<'paddingY'>
	marginX?: PropValue<'marginX'>
	marginY?: PropValue<'marginY'>
	spaceX?: PropValue<'spaceX'>
	spaceY?: PropValue<'spaceY'>
	fontSmoothing?: PropValue<'fontSmoothing'>
	truncate?: PropValue<'truncate'>
	backgroundGradient?: PropValue<'backgroundGradient'>
	textGradient?: PropValue<'textGradient'>
	gradientFrom?: PropValue<'gradientFrom'>
	gradientTo?: PropValue<'gradientTo'>
	gradientVia?: PropValue<'gradientVia'>
	borderTopRadius?: PropValue<'borderTopRadius'>
	borderRightRadius?: PropValue<'borderRightRadius'>
	borderBottomRadius?: PropValue<'borderBottomRadius'>
	borderLeftRadius?: PropValue<'borderLeftRadius'>
	borderStartRadius?: PropValue<'borderStartRadius'>
	borderEndRadius?: PropValue<'borderEndRadius'>
	borderXColor?: PropValue<'borderXColor'>
	borderYColor?: PropValue<'borderYColor'>
	borderX?: PropValue<'borderX'>
	borderY?: PropValue<'borderY'>
	divideX?: PropValue<'divideX'>
	divideY?: PropValue<'divideY'>
	divideColor?: PropValue<'divideColor'>
	divideStyle?: PropValue<'divideStyle'>
	boxShadowColor?: PropValue<'boxShadowColor'>
	brightness?: PropValue<'brightness'>
	contrast?: PropValue<'contrast'>
	grayscale?: PropValue<'grayscale'>
	hueRotate?: PropValue<'hueRotate'>
	invert?: PropValue<'invert'>
	saturate?: PropValue<'saturate'>
	sepia?: PropValue<'sepia'>
	dropShadow?: PropValue<'dropShadow'>
	blur?: PropValue<'blur'>
	backdropBlur?: PropValue<'backdropBlur'>
	backdropBrightness?: PropValue<'backdropBrightness'>
	backdropContrast?: PropValue<'backdropContrast'>
	backdropGrayscale?: PropValue<'backdropGrayscale'>
	backdropHueRotate?: PropValue<'backdropHueRotate'>
	backdropInvert?: PropValue<'backdropInvert'>
	backdropOpacity?: PropValue<'backdropOpacity'>
	backdropSaturate?: PropValue<'backdropSaturate'>
	backdropSepia?: PropValue<'backdropSepia'>
	borderSpacingX?: PropValue<'borderSpacingX'>
	borderSpacingY?: PropValue<'borderSpacingY'>
	scaleX?: PropValue<'scaleX'>
	scaleY?: PropValue<'scaleY'>
	translateX?: PropValue<'translateX'>
	translateY?: PropValue<'translateY'>
	skewX?: PropValue<'skewX'>
	skewY?: PropValue<'skewY'>
	scrollMarginX?: PropValue<'scrollMarginX'>
	scrollMarginY?: PropValue<'scrollMarginY'>
	scrollPaddingX?: PropValue<'scrollPaddingX'>
	scrollPaddingY?: PropValue<'scrollPaddingY'>
	scrollSnapStrictness?: PropValue<'scrollSnapStrictness'>
	scrollSnapMargin?: PropValue<'scrollSnapMargin'>
	scrollSnapMarginTop?: PropValue<'scrollSnapMarginTop'>
	scrollSnapMarginBottom?: PropValue<'scrollSnapMarginBottom'>
	scrollSnapMarginLeft?: PropValue<'scrollSnapMarginLeft'>
	scrollSnapMarginRight?: PropValue<'scrollSnapMarginRight'>
	fill?: PropValue<'fill'>
	stroke?: PropValue<'stroke'>
	srOnly?: PropValue<'srOnly'>
	debug?: PropValue<'debug'>
	borderSlim?: PropValue<'borderSlim'>
	colorPalette?: PropValue<'colorPalette'>
	textStyle?: PropValue<'textStyle'>
}