blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/chakra-ui/panda/discussions
    about: Ask questions and discuss topics with other community members
  - name: Documentation Request
    url: https://github.com/chakra-ui/panda/issues/new/choose
    about: Request for documentation to be added/altered
  - name: Chat with other community members
    url: https://discord.gg/VQrkpsgSx7
    about: The official Panda CSS Discord community
