import {
  outdirBasename,
  type DesignSystemManifest,
  type ImportMapInput,
  type ImportMapOption,
} from '@pandacss/compiler-shared'
import type { UserConfig } from '@pandacss/types'
import { readFileSync, statSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'
import { createConfigDiagnostic, createConfigError, PandaError } from './error'
import { resolveFrom, type ResolveOutcome } from './resolve'
import { ensureConfigObject, errorMessage, isPlainObject, type ExtendableConfig } from './shared'

export interface ResolvedDesignSystem {
  name: string
  specifier: string
  manifest: DesignSystemManifest
  manifestPath: string
  buildInfoPath: string
  files: string[]
  tokenPaths: string[]
  importMap?: DesignSystemManifest['importMap']
  /** Class-name options (`hash`/`prefix`/`separator`) the consumer overrode away
   * from this design system's, which would break its prebuilt class names. */
  optionMismatch?: string[]
}

export interface DesignSystemLevel {
  preset: ExtendableConfig
  info: ResolvedDesignSystem
}

export async function loadDesignSystemChain(
  spec: string,
  cwd: string,
  deps: Set<string>,
): Promise<DesignSystemLevel[]> {
  const levels: DesignSystemLevel[] = []
  const seenAt = new Map<string, number>()
  const seenNames = new Map<string, string>()

  let currentSpec = spec
  let fromDir = cwd
  let declaredBy: string | undefined

  while (true) {
    const manifestPath = resolveManifestPath(currentSpec, fromDir)
    if (manifestPath === undefined) {
      throw declaredBy === undefined ? notResolvedError(currentSpec) : parentNotResolvedError(declaredBy, currentSpec)
    }
    const seen = seenAt.get(manifestPath)
    if (seen !== undefined) {
      throw cycleError([...levels.slice(seen).map((level) => level.info.name), levels[seen].info.name])
    }
    seenAt.set(manifestPath, levels.length)
    deps.add(manifestPath)

    const { level, parent } = await loadManifestLevel(currentSpec, manifestPath, deps)

    const priorPath = seenNames.get(level.info.name)
    if (priorPath !== undefined && priorPath !== manifestPath) {
      throw duplicateNameError(level.info.name, priorPath, manifestPath)
    }
    seenNames.set(level.info.name, manifestPath)

    levels.push(level)

    if (parent === undefined) break
    declaredBy = level.info.name
    fromDir = dirname(manifestPath)
    currentSpec = parent
  }

  return levels.reverse()
}

export function withDesignSystemImportMap(config: UserConfig, infos: ResolvedDesignSystem[]): UserConfig {
  const existing: ImportMapOption[] =
    config.importMap === undefined ? [] : Array.isArray(config.importMap) ? config.importMap : [config.importMap]
  const roots: ImportMapOption[] = infos.map((info) =>
    info.importMap ? designSystemImportMap(info.importMap, info.specifier) : info.specifier,
  )
  return { ...config, importMap: [...roots, outdirBasename(config.outdir ?? 'styled-system'), ...existing] }
}

function resolveManifestPath(spec: string, fromDir: string): string | undefined {
  const protocol = specifierProtocol(spec)
  if (protocol) throw unsupportedSpecifierError(spec, protocol)

  let outcome: ResolveOutcome
  try {
    outcome = resolveFrom(`${spec}/panda.lib.json`, fromDir)
  } catch (error) {
    const message = `Failed to resolve designSystem ${JSON.stringify(spec)} from ${JSON.stringify(fromDir)}: ${errorMessage(error)}`
    throw createConfigError(message, [createConfigDiagnostic('design_system_resolve_failed', message)])
  }
  if (outcome.kind === 'resolved') return outcome.path
  if (outcome.kind === 'not-exported') throw manifestNotExportedError(spec)
  return undefined
}

function manifestNotExportedError(spec: string): PandaError {
  const message = `designSystem ${JSON.stringify(spec)} is installed but doesn't expose \`./panda.lib.json\`. If it's a Panda design system, rebuild it with \`panda lib\`; otherwise it can't be consumed as a design system.`
  return createConfigError(message, [
    createConfigDiagnostic('design_system_manifest_not_exported', message, [
      `Rebuild ${JSON.stringify(spec)} with \`panda lib\`, or check its package.json \`exports\` includes \`./panda.lib.json\`.`,
    ]),
  ])
}

async function loadManifestLevel(
  spec: string,
  manifestPath: string,
  deps: Set<string>,
): Promise<{ level: DesignSystemLevel; parent: string | undefined }> {
  let parsed: unknown
  try {
    parsed = JSON.parse(readFileSync(manifestPath, 'utf8'))
  } catch (error) {
    const message = `Failed to parse ${JSON.stringify(manifestPath)} as JSON: ${errorMessage(error)}. This file must be generated by \`panda lib\`, not hand-written or added to \`include\`.`
    throw createConfigError(message, [
      { ...createConfigDiagnostic('design_system_manifest_invalid', message), file: manifestPath },
    ])
  }
  const manifest = validateManifest(spec, manifestPath, parsed)

  const presetPath = resolve(dirname(manifestPath), manifest.preset)
  const buildInfoPath = resolve(dirname(manifestPath), manifest.buildInfo)
  deps.add(presetPath)
  deps.add(buildInfoPath)

  let preset: ExtendableConfig
  try {
    const mod = await import(presetImportUrl(presetPath))
    preset = ensureConfigObject('default' in mod ? mod.default : mod, manifest.name ?? spec)
  } catch (error) {
    if (error instanceof PandaError && error.diagnostics?.length) throw error
    const message = `Failed to load the preset for designSystem ${JSON.stringify(spec)} (${JSON.stringify(manifest.preset)}): ${errorMessage(error)}`
    throw createConfigError(message, [
      createConfigDiagnostic('design_system_preset_load_failed', message, [
        `Check that ${JSON.stringify(manifest.preset)} is valid and rebuild ${JSON.stringify(spec)} with \`panda lib\`.`,
      ]),
    ])
  }

  const parent =
    typeof manifest.designSystem === 'string' && manifest.designSystem.length > 0 ? manifest.designSystem : undefined

  return {
    parent,
    level: {
      preset,
      info: {
        name: manifest.name ?? spec,
        specifier: spec,
        manifest,
        manifestPath,
        buildInfoPath,
        files: manifest.files ?? [],
        tokenPaths: [],
        ...(manifest.importMap ? { importMap: manifest.importMap } : {}),
      },
    },
  }
}

function presetImportUrl(path: string): string {
  const url = pathToFileURL(path)
  url.searchParams.set('mtime', String(statSync(path).mtimeMs))
  return url.href
}

function designSystemImportMap(map: NonNullable<DesignSystemManifest['importMap']>, spec: string): ImportMapInput {
  return {
    css: map.css ?? `${spec}/css`,
    recipes: map.recipes ?? `${spec}/recipes`,
    patterns: map.patterns ?? `${spec}/patterns`,
    jsx: map.jsx ?? `${spec}/jsx`,
    tokens: map.tokens ?? `${spec}/tokens`,
  }
}

const IMPORT_MAP_FIELDS = ['css', 'recipes', 'patterns', 'jsx', 'tokens'] as const

function validateManifest(spec: string, manifestPath: string, value: unknown): DesignSystemManifest {
  if (!isPlainObject(value)) {
    throw invalidManifestError(spec, manifestPath, ['must contain a JSON object'])
  }

  const issues: string[] = []
  requiredString(value, 'name', issues)
  requiredString(value, 'panda', issues)
  requiredString(value, 'preset', issues)
  requiredString(value, 'buildInfo', issues)

  if (!Number.isInteger(value.schemaVersion) || (value.schemaVersion as number) < 1) {
    issues.push('must contain a positive integer "schemaVersion" entry')
  }

  if (value.version !== undefined && typeof value.version !== 'string') {
    issues.push('has a "version" entry that must be a string')
  }

  if (value.designSystem !== undefined && !isNonEmptyString(value.designSystem)) {
    issues.push('has a "designSystem" entry that must be a non-empty string')
  }

  if (
    value.files !== undefined &&
    (!Array.isArray(value.files) || !value.files.every((file) => isNonEmptyString(file)))
  ) {
    issues.push('has a "files" entry that must be an array of non-empty strings')
  }

  if (value.importMap !== undefined) {
    if (!isPlainObject(value.importMap)) {
      issues.push('has an "importMap" entry that must be an object')
    } else {
      for (const field of IMPORT_MAP_FIELDS) {
        const entry = value.importMap[field]
        if (entry !== undefined && !isNonEmptyString(entry)) {
          issues.push(`has an "importMap.${field}" entry that must be a non-empty string`)
        }
      }
    }
  }

  if (issues.length > 0) {
    throw invalidManifestError(spec, manifestPath, issues)
  }

  return value as unknown as DesignSystemManifest
}

function requiredString(value: Record<string, unknown>, field: string, issues: string[]): void {
  if (!isNonEmptyString(value[field])) {
    issues.push(`is missing a "${field}" entry or it is empty`)
  }
}

function isNonEmptyString(value: unknown): value is string {
  return typeof value === 'string' && value.trim().length > 0
}

function notResolvedError(spec: string): PandaError {
  const message = `designSystem ${JSON.stringify(spec)} could not be resolved. Install it, or — if it isn't a Panda design system — build it with \`panda lib\`.`
  return createConfigError(message, [
    createConfigDiagnostic('design_system_manifest_not_found', message, [
      `Install ${JSON.stringify(spec)}, or build it with \`panda lib\` if it is a Panda design system.`,
    ]),
  ])
}

function parentNotResolvedError(child: string, parent: string): PandaError {
  const message = `designSystem ${JSON.stringify(child)} extends ${JSON.stringify(parent)}, which isn't installed alongside it. Install it where ${JSON.stringify(child)} can resolve it, or rebuild that library with \`panda lib\`.`
  return createConfigError(message, [
    createConfigDiagnostic('design_system_parent_not_found', message, [
      `Install ${JSON.stringify(parent)} where ${JSON.stringify(child)} can resolve it, or rebuild ${JSON.stringify(child)} with \`panda lib\`.`,
    ]),
  ])
}

function cycleError(cycle: string[]): PandaError {
  const message = `Design-system cycle: ${cycle.join(' → ')}. A design system can't depend on itself.`
  return createConfigError(message, [createConfigDiagnostic('design_system_cycle', message)])
}

function invalidManifestError(spec: string, manifestPath: string, issues: string[]): PandaError {
  const message = `${JSON.stringify(spec)} manifest ${issues.join('; ')}.`
  return createConfigError(message, [
    {
      ...createConfigDiagnostic('design_system_manifest_invalid', message, [
        `Rebuild ${JSON.stringify(spec)} with \`panda lib\`.`,
      ]),
      file: manifestPath,
    },
  ])
}

function duplicateNameError(name: string, firstPath: string, secondPath: string): PandaError {
  const message = `Two different packages in the design-system chain are both named ${JSON.stringify(name)} (${JSON.stringify(firstPath)} and ${JSON.stringify(secondPath)}). Their styles would overwrite each other; give each package a unique name.`
  return createConfigError(message, [createConfigDiagnostic('design_system_duplicate_name', message)])
}

function specifierProtocol(spec: string): string | undefined {
  const match = spec.match(/^([a-z][a-z0-9+.-]*):/i)
  return match ? match[1] : undefined
}

function unsupportedSpecifierError(spec: string, protocol: string): PandaError {
  const message = `designSystem ${JSON.stringify(spec)} uses the "${protocol}:" protocol, which isn't supported. Use the published package name (e.g. "@acme/design-system") that resolves to its \`panda.lib.json\`.`
  return createConfigError(message, [createConfigDiagnostic('design_system_unsupported_specifier', message)])
}
