/**
 * The design system spec: `styled-system/specs/design-system.json`.
 *
 * A public contract generated by the Rust engine
 * (`crates/pandacss_codegen/src/artifacts/specs.rs`) and read by tooling with
 * no access to the compiler — token viewers, docs builds, dashboards.
 *
 * Distinct from `Spec` in `types/output.ts`, which is the typegen index
 * `compiler.spec()` returns.
 */

export * from './types'
export * from './read'
