/**
 * Shape of the JSON Panda writes to `styled-system/specs/`.
 *
 * A public contract: the file is generated by the Rust engine
 * (`crates/pandacss_codegen/src/artifacts/specs.rs`) and read by tooling that
 * has no access to the compiler — token viewers, docs builds, design-system
 * dashboards. `schemaVersion` keeps the two sides honest.
 */

/**
 * Shaped for two access patterns at once: `tokens` is keyed by path so lookup
 * needs no index, and `paths` + `categories` let a viewer render a category by
 * slicing a range rather than grouping every token first. Value rows keep the
 * token references they resolve through, so the reference graph survives
 * codegen.
 */
export interface DesignSystemSpec {
  schemaVersion: number
  /** Category name to `[from, to)` range into {@link DesignSystemSpec.paths}. */
  categories: Record<string, [number, number]>
  /** Every token path, grouped by category then sorted — render order. */
  paths: string[]
  /** Path-keyed metadata that does not vary by condition or theme. */
  tokens: Record<string, DesignSystemToken>
  /** Condition name to its raw query, as configured. */
  conditions: Record<string, unknown>
  themes: Record<string, DesignSystemTheme>
  /** Flat value table, keyed by `(token, theme, condition)` and sorted by it. */
  values: DesignSystemValue[]
}

export interface DesignSystemToken {
  category: string
  /** The custom property, e.g. `--colors-red-500`. Absent for derived tokens. */
  cssVar?: string
  description?: string
  deprecated?: boolean
  deprecatedReason?: string
  semantic?: boolean
}

export interface DesignSystemTheme {
  id: string
  selector: string | null
}

/** One token value. No `condition` and no `theme` means the base value. */
export interface DesignSystemValue {
  token: string
  condition?: string
  theme?: string
  /** Fully resolved, ready to paint. */
  value: string
  /** Token paths this value points at through `var(--…)`. */
  refs?: string[]
}
