import type { Context } from '../engines'

export function generatePackageJson(ctx: Context) {
  const {
    config: { outdir, outExtension: ext = 'mjs' },
  } = ctx

  const pkg = {
    name: outdir,
    description: 'This package is auto-generated by Panda CSS',
    version: `0.0.0-${performance.now()}`,
    type: 'module',
    exports: {
      './css': {
        types: './css/index.d.ts',
        require: `./css/index.${ext}`,
        import: `./css/index.${ext}`,
      },
      './jsx': {
        types: './jsx/index.d.ts',
        require: `./jsx/index.${ext}`,
        import: `./jsx/index.${ext}`,
      },
      './patterns': {
        types: './patterns/index.d.ts',
        require: `./patterns/index.${ext}`,
        import: `./patterns/index.${ext}`,
      },
      './recipes': {
        types: './recipes/index.d.ts',
        require: `./recipes/index.${ext}`,
        import: `./recipes/index.${ext}`,
      },
      './tokens': {
        types: './tokens/index.d.ts',
        require: `./tokens/index.${ext}`,
        import: `./tokens/index.${ext}`,
      },
      './types': {
        types: './types/index.d.ts',
      },
      './styles.css': './styles.css',
    },
  }

  return JSON.stringify(pkg, null, 2)
}
