import type { Context } from '../engines'

export function generatePackageJson(ctx: Context) {
  const {
    config: { outdir },
  } = ctx

  const pkg = {
    name: outdir,
    description: 'This package is auto-generated by CSS Panda',
    version: `0.0.0-${performance.now()}`,
    type: 'module',
    exports: {
      './css': {
        types: './css/index.d.ts',
        require: './css/index.mjs',
        import: './css/index.mjs',
      },
      './jsx': {
        types: './jsx/index.d.ts',
        require: './jsx/index.mjs',
        import: './jsx/index.mjs',
      },
      './patterns': {
        types: './patterns/index.d.ts',
        require: './patterns/index.mjs',
        import: './patterns/index.mjs',
      },
      './recipes': {
        types: './recipes/index.d.ts',
        require: './recipes/index.mjs',
        import: './recipes/index.mjs',
      },
      './tokens': {
        types: './tokens/index.d.ts',
        require: './tokens/index.mjs',
        import: './tokens/index.mjs',
      },
      './types': {
        types: './types/index.d.ts',
      },
      './styles.css': './styles.css',
    },
  }

  return JSON.stringify(pkg, null, 2)
}
