import type { Context } from '@pandacss/core'

export function generatePackageJson(ctx: Context) {
  const {
    config: { outdir },
  } = ctx

  const pkg = {
    name: outdir,
    description: 'This package is auto-generated by Panda CSS',
    version: `0.0.0-${performance.now()}`,
    type: 'module',
    exports: {
      './css': {
        types: ctx.file.extDts('./css/index'),
        require: ctx.file.ext(`./css/index`),
        import: ctx.file.ext(`./css/index`),
      },
      './jsx': {
        types: ctx.file.extDts('./jsx/index'),
        require: ctx.file.ext(`./jsx/index`),
        import: ctx.file.ext(`./jsx/index`),
      },
      './patterns': {
        types: ctx.file.extDts('./patterns/index'),
        require: ctx.file.ext(`./patterns/index`),
        import: ctx.file.ext(`./patterns/index`),
      },
      './recipes': {
        types: ctx.file.extDts('./recipes/index'),
        require: ctx.file.ext(`./recipes/index`),
        import: ctx.file.ext(`./recipes/index`),
      },
      './themes': {
        types: ctx.file.extDts('./themes/index'),
        require: ctx.file.ext(`./themes/index`),
        import: ctx.file.ext(`./themes/index`),
      },
      './tokens': {
        types: ctx.file.extDts('./tokens/index'),
        require: ctx.file.ext(`./tokens/index`),
        import: ctx.file.ext(`./tokens/index`),
      },
      './types': {
        types: ctx.file.extDts('./types/index'),
      },
      './styles.css': './styles.css',
    },
  }

  return JSON.stringify(pkg, null, 2)
}
