import { mkdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import mdnProperties from 'mdn-data/css/properties.json'
import { properties as svgProperties } from './svg'

const dashRegex = /-+(.)/g
const omitRegex = /^(?:-moz|-ms|--\*)/

function camelCaseProperty(str: string) {
  return str.replace(dashRegex, (_, p1) => p1.toUpperCase())
}

function addCamelProperty(out: Set<string>, property: unknown) {
  if (typeof property !== 'string' || omitRegex.test(property)) return
  out.add(camelCaseProperty(property))
}

function fromMdn() {
  const properties = new Set<string>()
  for (const property of Object.keys(mdnProperties)) addCamelProperty(properties, property)
  for (const property of Object.keys(svgProperties)) addCamelProperty(properties, property)
  return properties
}

function rustString(value: string) {
  return JSON.stringify(value)
}

function renderRust(properties: string[]) {
  const rows = properties.map((property) => `    ${rustString(property)},`).join('\n')
  return `// @generated by packages/is-valid-prop/scripts/rust.ts
// Source: mdn-data css/properties.json + Panda SVG property additions.

pub(crate) static CSS_PROPERTIES: &[&str] = &[
${rows}
];
`
}

const root = join(dirname(fileURLToPath(import.meta.url)), '../../..')
const rustPath = join(root, 'crates/pandacss_extractor/src/generated/css_properties.rs')
const properties = [...fromMdn()].sort()

mkdirSync(dirname(rustPath), { recursive: true })
writeFileSync(rustPath, renderRust(properties))

console.log(`Generated ${properties.length} Rust CSS properties from mdn-data.`)
