import { mkdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import mdnProperties from 'mdn-data/css/properties.json'
import { properties as svgProperties } from './svg'

const dashRegex = /-+(.)/g
const omitRegex = /^(?:-moz|-ms|--\*)/

function camelCaseProperty(str: string) {
  return str.replace(dashRegex, (_, p1) => p1.toUpperCase())
}

function addCamelProperty(out: Set<string>, property: unknown) {
  if (typeof property !== 'string' || omitRegex.test(property)) return
  out.add(camelCaseProperty(property))
}

function fromMdn() {
  const properties = new Set<string>()
  for (const property of Object.keys(mdnProperties)) addCamelProperty(properties, property)
  for (const property of Object.keys(svgProperties)) addCamelProperty(properties, property)
  return properties
}

function rustString(value: string) {
  return JSON.stringify(value)
}

function renderRust(properties: string[]) {
  const rows = properties.map((property) => `    ${rustString(property)},`).join('\n')
  return `// @generated by packages/is-valid-prop/scripts/rust.ts
// Source: mdn-data css/properties.json + Panda SVG property additions.

//! The single source of truth for valid CSS property names: standard, \`-webkit-\`,
//! and SVG (the \`-moz-\`/\`-ms-\` prefixes are dropped). Shared by the extractor's
//! \`is_css_property\` membership check and the codegen's \`CssProperties\` interface,
//! sorted so the extractor can \`binary_search\` and the codegen emits in order.
pub static CSS_PROPERTY_NAMES: &[&str] = &[
${rows}
];

#[must_use]
pub fn is_css_property(prop: &str) -> bool {
    prop.starts_with("--")
        || prop.contains('&')
        || prop.contains('@')
        || CSS_PROPERTY_NAMES.binary_search(&prop).is_ok()
}

#[must_use]
pub fn css_property_names() -> &'static [&'static str] {
    CSS_PROPERTY_NAMES
}
`
}

const root = join(dirname(fileURLToPath(import.meta.url)), '../../..')
const rustPath = join(root, 'crates/pandacss_shared/src/css_properties.rs')
const properties = [...fromMdn()].sort()

mkdirSync(dirname(rustPath), { recursive: true })
writeFileSync(rustPath, renderRust(properties))

console.log(`Generated ${properties.length} CSS property names (shared) from mdn-data.`)
