[package]
name = "pandacss_literal"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pandacss_shared = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
