import { writeFile } from 'fs-extra'
import { outdent } from 'outdent'

function withNote(text: string) {
  return outdent`
  /**
   * This is an autogenerated file created by the Panda 🐼.
   * Do not edit this file directly.
   */
  
  ${text}
  `
}

export function writeFileWithNote(path: string, text: string) {
  return writeFile(path, withNote(text))
}
