import type { PackageJson } from 'pkg-types'

export function generatePackageJSON() {
  const pkg: PackageJson = {
    name: 'dot-panda',
    description: 'This package is auto-generated by Panda',
    version: `0.0.0-${performance.now()}`,
    exports: {
      './css': './css/index.js',
      './tokens': './tokens/index.js',
      './jsx': './jsx/index.jsx',
      './tokens.css': './tokens/index.css',
      './styles.css': './styles.css',
      './package.json': './package.json',
    },
    typeVersions: {
      '*': {
        css: ['./css'],
        jsx: ['./jsx'],
        tokens: ['./tokens'],
      },
    },
  }

  return JSON.stringify(pkg, null, 2)
}
