/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Compiler {
  /**
   * Low-level build-info primitive — serialize the project's encoded atoms
   * (string-interned, per-module provenance). The public surface is the
   * `buildInfo.create` namespace in JS; `configFingerprint` is engine-owned.
   *
   * # Errors
   * Returns an error if the build info fails to serialize.
   */
  serializeBuildInfo(panda: string): any
  /**
   * Low-level build-info primitive — hydrate a deserialized build info into
   * this project (additive), optionally restricted to imported modules
   * (tree-shaking). Returns `false` on schema-version mismatch. The public
   * surface (with validation) is the `buildInfo.hydrate` namespace in JS.
   *
   * # Errors
   * Returns an error if `buildInfo` isn't a valid build-info document.
   */
  applyBuildInfo(name: string, buildInfo: any, onlyModules?: Array<string> | undefined | null): boolean
  /**
   * The build-info wire-format version this binding reads/writes. The JS
   * `buildInfo.validate` compares an artifact's `schemaVersion` against it.
   */
  buildInfoSchemaVersion(): number
  /**
   * Generate artifacts and write them under `outdir`.
   *
   * # Errors
   * Returns an error if a file fails to write.
   */
  writeArtifacts(options: WriteArtifactsOptions): Array<string>
  generateArtifacts(options?: GenerateArtifactOptions | undefined | null): Array<CodegenArtifact>
  generateArtifact(id: string, options?: GenerateArtifactOptions | undefined | null): CodegenArtifact | null
  generateAffectedArtifacts(dependencies: Array<string>, options?: GenerateArtifactOptions | undefined | null): Array<CodegenArtifact>
  /**
   * Return the serialized config snapshot this project was constructed
   * with.
   */
  config(): any
  /**
   * The resolved cascade-layer names (config overrides merged over defaults).
   * The host needs these to recognize the user's `@layer …;` directive
   * without re-deriving the Rust defaults.
   */
  layers(): LayerNames
  /**
   * Whether `css` declares Panda's cascade layers (`@layer reset, base, …;`),
   * marking it as the stylesheet root to inject the compiled CSS into.
   */
  hasLayerDeclaration(css: string): boolean
  /** Remove Panda `@layer a, b;` order statements; leave unrelated ones. */
  stripLayerOrderStatements(css: string): string
  /**
   * Tooling introspection snapshot (read once, index on the host).
   *
   * # Errors
   * Returns an error if the snapshot fails to serialize.
   */
  spec(): any
  /**
   * Engine-owned fingerprint of the resolved config's output-affecting fields.
   * Stamped into build info as `configFingerprint`; also exposed so a consumer
   * host can compare its own config against a library's artifact.
   */
  configFingerprint(): string
  /** Rust-built token dictionary projected into the small JS interop shape. */
  token_dictionary(): TokenDictionary | null
  compile(options?: CompileOptions | undefined | null): CompileOutput
  writeCss(options: WriteCssOptions): WriteCssResult
  writeSplitCss(options: WriteSplitCssOptions): WriteSplitCssResult
  /** Theme `@keyframes` CSS only (no token vars or other layers). */
  getKeyframeCss(options?: CompileOptions | undefined | null): CompileOutput
  /**
   * CSS for the named cascade layers, concatenated in order. Sliced in Rust
   * (byte offsets stay valid); unknown layer names are skipped.
   */
  getLayerCss(options: LayerCssOptions): CompileOutput
  writeLayerCss(options: WriteLayerCssOptions): WriteCssResult
  /**
   * Split the stylesheet into per-file outputs (one per layer + per recipe,
   * plus `recipes.css` / `styles.css` index files) for `--splitting`.
   */
  getSplitCss(options?: CssOutputOptions | undefined | null): SplitCssResult
  /**
   * Build a `panda/lib.json` value from host-supplied fields, stamping the
   * engine-owned schema version. Backs the `designSystem.create` JS namespace.
   *
   * # Errors
   * Returns an error if `input` is invalid or the manifest fails to serialize.
   */
  createDesignSystemManifest(input: any): any
  /**
   * The manifest wire-format version this binding reads/writes. The JS
   * `designSystem.validate` compares a manifest's `schemaVersion` against it.
   */
  designSystemManifestSchemaVersion(): number
  /** Read a source file from the native filesystem and parse it. */
  parseFile(path: string): ParseFileReport
  /**
   * Extract + encode provided source text. Re-parsing a path replaces its
   * prior contribution (atoms, recipes, diagnostics) — safe for watch mode.
   */
  parseFileSource(path: string, source: string): ParseFileReport
  /**
   * Source paths matching the config's `include`/`exclude` (overridable via
   * `options`), via the platform filesystem engine. Useful for file
   * discovery and the host's watch dependency list.
   *
   * # Errors
   * Returns an error when the scan fails (e.g. a non-existent `cwd`).
   */
  scan(options?: ScanOptions | undefined | null): Array<string>
  /**
   * Per-package import selections from one scan of `include` sources.
   * Each entry is `null` = hydrate all, or export names to narrow.
   *
   * # Errors
   * Returns an error when the scan fails (e.g. a non-existent `cwd`).
   */
  designSystemImportSelections(packages: Array<DesignSystemImportPackageQuery>): Array<Array<string> | undefined | null>
  /**
   * Resolve a path to its real on-disk location (absolute, symlinks followed) so
   * two paths to the same file compare equal. Lenient: returns the input path when
   * it can't be resolved (e.g. it was just deleted), so callers can still match it.
   */
  realpath(path: string): string
  readFile(path: string): string | null
  exists(path: string): boolean
  /**
   * Whether `path` is a source file the project extracts from — its
   * `cwd`-relative form matches the configured `include`/`exclude` globs.
   * For routing a watch event to `applyChange` vs ignoring it.
   */
  isSourceFile(path: string): boolean
  /**
   * Read + parse source paths from `scan()`. One report per requested path;
   * a read miss keeps last-good state and reports a warning diagnostic.
   */
  parseFiles(paths: Array<string>): Array<ParseFileReport>
  /**
   * Stateless single-file extraction — raw `calls` + `jsx` + diagnostics,
   * using the project's configured matchers + token dictionary. Unlike
   * `parseFile`, it registers nothing; it's the read-only peek companion.
   */
  extractFileSource(path: string, source: string): ExtractResult
  /**
   * Re-parse a path *only if* it is already known to the project.
   * Returns `true` if the path was present and got re-parsed; `false`
   * if the path is unknown (no-op). Watch-mode contract.
   */
  refreshFile(path: string): boolean
  /** Re-parse provided source text only if the path is already known. */
  refreshFileSource(path: string, source: string): boolean
  /** Drop a file's contribution. Returns `true` if the path was known. */
  removeFile(path: string): boolean
  /**
   * Files whose folded imports changed since the last call. Clears on read.
   * Re-parse each via `refreshFile`, then call again until empty.
   */
  affectedFiles(): Array<string>
  /**
   * Drop every path's state. Keeps the config-derived extractor,
   * token dictionary, and cross-file resolver intact.
   */
  clear(): void
  /** Returns `true` when the project has no files and no accumulated output. */
  isEmpty(): boolean
  /**
   * `(path, hex source_hash)` for every known file, sorted by path.
   * The hash matches the one the re-parse short-circuit uses.
   */
  fileManifest(): Array<CompileFileManifest>
  /** Per-file view; returns `null` when `path` isn't known. */
  getFile(path: string): ParsedFileView | null
  resolvePath(path: string, cwd?: string | undefined | null): string
  joinPath(parts: Array<string>): string
  dirname(path: string): string
  /**
   * Stateless source inspection for tooling (reporting, lint, IDE). Returns
   * classified Panda usage sites plus file-local extraction diagnostics.
   *
   * # Errors
   * Returns an error if the result fails to serialize.
   */
  inspectFileSource(path: string, source: string): any
  /**
   * Resolve selector and CSS metadata for one utility value.
   *
   * # Errors
   * Returns an error if the value cannot be represented by the extractor
   * literal model.
   */
  resolveUtilityValue(input: ResolveUtilityValueInput): ResolvedUtilityValue | null
  /**
   * Tokens that carry a hardcoded value, ranked (safe equivalents first).
   * Empty when nothing matches. The rule lists these for the developer.
   */
  suggestTokens(prop: string, value: string): any
  /** Semantic tokens that carry the same value as a token path. */
  suggestSemanticTokens(path: string): any
  /**
   * Source globs + their static base dirs for the host watcher. `pattern` is
   * relative to `base`, so `(base, pattern)` is a ready-to-use `(dir, glob)` pair.
   */
  sources(): Array<SourceEntry>
  /**
   * Config validation diagnostics from construction. Per-file and
   * compile diagnostics live on [`ParseFileReport`] / [`CompileOutput`].
   */
  diagnostics(): Array<Diagnostic>
  /** Aggregate counts. */
  summary(): ProjectSummary
  /**
   * Deduplicated atoms across every currently-known file. Sorted by
   * `(prop, conditions, value)` for stable iteration / snapshot tests.
   */
  atoms(): Array<Atom>
  /** Every `cva()` recipe entry, in `(file, span_start)` order. */
  recipes(): Array<RecipeEntry>
  /** Every `sva()` slot recipe entry, in `(file, span_start)` order. */
  slotRecipes(): Array<RecipeEntry>
  /** Encoded config recipe styles, separate from atomic utility atoms. */
  encodedRecipes(): any
  /**
   * `staticCss.patterns` expansion as raw atoms, without compiling.
   * Routes through the same callback host as `parseFile`.
   */
  staticPatternAtoms(): StaticPatternResult
  /** Rewrite one source file to inline static Panda class strings where safe. */
  transformSource(input: TransformSourceInput): TransformSourceResult
  /** Register a JS-backed utility transform callback. */
  registerUtilityTransform(id: string, callback: UtilityTransformRef): void
  /** Register a JS-backed pattern transform callback. */
  registerPatternTransform(id: string, callback: (arg0: any) => any): void
  /** Register a JS-backed `parser:before` source transform. */
  registerSourceTransform(id: string, filter: any | undefined | null, callback: SourceTransformRef): void
  /** Construct a compiler from the resolved, JSON-safe Panda config snapshot. */
  static fromConfig(config: any, options?: ProjectOptions | undefined | null, utilityValuesCallbacks?: UtilityValueCallbacks | undefined | null): Compiler
}

/**
 * ```js
 * const extractor = new Extractor(matchers)
 * for (const file of files) {
 *   const result = extractor.extract(file.path, file.source)
 * }
 * ```
 */
export declare class Extractor {
  /**
   * Token dictionary (if any) is materialized once so each subsequent
   * `extract` call is a lean parse + visit.
   */
  constructor(matchers: Matchers)
  extract(path: string, source: string): ExtractResult
  extractDebug(path: string, source: string): ExtractDebugResult
  /**
   * Run the matched-imports filter without re-parsing. Uses the
   * session's `Matchers` config.
   */
  matchImports(scan: ImportScanResult): Array<MatchedImport>
}

/**
 * One atomic style declaration: `(prop, value, conditions)`. Returned by
 * `Compiler::atoms()`. Mirrors `pandacss_encoder::Atom` but with the
 * internal `Box<str>` Number form parsed back to a JS-native number.
 */
export interface Atom {
  prop: string
  /** `string | number | boolean | null`. */
  value: any
  /** Outer-to-inner condition chain. Empty for unconditional atoms. */
  conditions: Array<string>
}

export interface CodegenArtifact {
  id: string
  files: Array<CodegenFile>
}

export interface CodegenFile {
  path: string
  code: string
  dependencies: Array<string>
}

export interface CodegenOverlay {
  jsx: string
  recipes: string
  patterns: string
  css: string
  helpers: string
  ownedRecipes: Array<string>
  ownedPatterns: Array<string>
  virtualizeHelpers: boolean
  virtualizeCss: boolean
}

/**
 * One-shot stateless compile. Callback-bearing configs are not
 * supported — use `Compiler.fromConfig(...)` + `registerPatternTransform`
 * / `registerUtilityTransform` for that.
 */
export declare function compile(input?: CompileInput | undefined | null): CompileOutput

export interface CompileFileManifest {
  path: string
  hash: string
}

export interface CompileInput {
  files?: Array<InputFile>
  config?: any
  cwd?: string
  cacheDir?: string
  emitLayerDeclaration?: boolean
}

export interface CompileLayerRange {
  start: number
  end: number
}

/**
 * Byte slices into `CompileOutput.css` so callers can pull a single
 * layer without re-parsing. `None` when the layer wasn't emitted.
 */
export interface CompileLayerRanges {
  reset?: CompileLayerRange
  base?: CompileLayerRange
  tokens?: CompileLayerRange
  recipes?: CompileLayerRange
  utilities?: CompileLayerRange
}

export interface CompileManifest {
  files: Array<CompileFileManifest>
  tokens: Array<string>
}

export interface CompileOptions {
  emitLayerDeclaration?: boolean
  minify?: boolean
  polyfill?: boolean
}

export interface CompileOutput {
  css: string
  sourceMap?: string
  manifest: CompileManifest
  layerRanges: CompileLayerRanges
  diagnostics: Array<Diagnostic>
}

export interface CssOutputOptions {
  layers?: Array<string>
  emitLayerDeclaration?: boolean
  minify?: boolean
  polyfill?: boolean
}

export interface DesignSystemImportPackageQuery {
  packageRoots: Array<string>
  excludeModules?: Array<string>
}

export interface Diagnostic {
  code: string
  message: string
  severity: DiagnosticSeverity
  file?: string
  category?: string
  /** UTF-8 byte offsets. */
  span?: Span
  /** Human-readable line/column range covering `span`. */
  location?: SourceRange
  labels?: Array<DiagnosticLabel>
  help?: Array<string>
}

export interface DiagnosticLabel {
  message?: string
  /** UTF-8 byte offsets. */
  span?: Span
  /** Human-readable line/column range covering `span`. */
  location?: SourceRange
}

export declare const enum DiagnosticSeverity {
  Info = 'info',
  Warning = 'warning',
  Error = 'error'
}

export declare function extract(path: string, source: string, matchers: Matchers): ExtractResult

export declare function extractCalls(path: string, source: string, matched: Array<MatchedImport>, matchers: Matchers): ExtractedCallsResult

export declare function extractDebug(path: string, source: string, matchers: Matchers): ExtractDebugResult

/**
 * Kitchen-sink result with raw `imports` and Panda-filtered `matched`,
 * for tooling and parity-compare flows.
 */
export interface ExtractDebugResult {
  imports: Array<ImportRecord>
  matched: Array<MatchedImport>
  calls: Array<ExtractedCall>
  jsx: Array<ExtractedJsx>
  diagnostics: Array<Diagnostic>
}

export interface ExtractedArg {
  kind: ExtractedArgKind
  value?: any
}

/**
 * Tagged so a real `null` literal (`{ kind: "value", value: null }`) is
 * distinguishable from a non-foldable argument (`{ kind: "missing",
 * value: undefined }`). The previous `Array<unknown | null>` shape
 * collapsed those two cases.
 */
export declare const enum ExtractedArgKind {
  Value = 'value',
  Missing = 'missing'
}

export interface ExtractedCall {
  category: MatchCategory
  name: string
  alias: string
  /**
   * Per-argument values in source order; `data.length` matches the
   * source arity. Each entry is tagged so a real `null` literal stays
   * distinct from a non-foldable argument — see [`ExtractedArg`].
   */
  data: Array<ExtractedArg>
  span: Span
}

export interface ExtractedCallsResult {
  calls: Array<ExtractedCall>
  diagnostics: Array<Diagnostic>
}

export interface ExtractedJsx {
  category: MatchCategory
  kind: JsxKind
  name: string
  alias: string
  data: any
  span: Span
}

export interface ExtractedJsxResult {
  jsx: Array<ExtractedJsx>
  diagnostics: Array<Diagnostic>
}

export declare function extractJsx(path: string, source: string, matched: Array<MatchedImport>, matchers: Matchers): ExtractedJsxResult

/**
 * Lean result for the production hot path — `imports` and `matched` are
 * stripped so callers don't pay NAPI serialization cost for debug data.
 */
export interface ExtractResult {
  calls: Array<ExtractedCall>
  jsx: Array<ExtractedJsx>
  diagnostics: Array<Diagnostic>
}

export declare function flushTracing(): void

export interface GenerateArtifactOptions {
  forceImportExtension?: boolean
  overlay?: CodegenOverlay
}

export declare const enum ImportKind {
  SideEffect = 'sideEffect',
  Value = 'value'
}

export interface ImportRecord {
  module: string
  kind: ImportKind
  typeOnly: boolean
  specifiers: Array<ImportSpecifier>
  span: Span
}

export interface ImportScanResult {
  imports: Array<ImportRecord>
  diagnostics: Array<Diagnostic>
}

export interface ImportSpecifier {
  kind: ImportSpecifierKind
  imported: string
  local: string
  typeOnly: boolean
  span: Span
}

export declare const enum ImportSpecifierKind {
  Named = 'named',
  Default = 'default',
  Namespace = 'namespace'
}

export interface InputFile {
  path: string
  content: string
}

export declare const enum JsxKind {
  Factory = 'factory',
  Pattern = 'pattern',
  Recipe = 'recipe',
  Component = 'component'
}

export interface LayerCssOptions {
  layers: Array<string>
  emitLayerDeclaration?: boolean
  minify?: boolean
  polyfill?: boolean
}

/** The resolved cascade-layer names (config overrides + defaults applied). */
export interface LayerNames {
  reset: string
  base: string
  tokens: string
  recipes: string
  utilities: string
}

export declare const enum MatchCategory {
  Css = 'css',
  Recipe = 'recipe',
  Pattern = 'pattern',
  Jsx = 'jsx',
  Tokens = 'tokens'
}

export interface MatchedImport {
  category: MatchCategory
  module: string
  name: string
  alias: string
  kind: ImportSpecifierKind
}

export interface Matcher {
  modules: Array<string>
  /** Omit to match any imported name (used for recipes/patterns). */
  names?: Array<string>
}

export interface Matchers {
  css: Matcher
  recipe: Matcher
  pattern: Matcher
  jsx?: Matcher
  tokens: Matcher
  jsxFramework?: string
  /**
   * When present, `token('path')` / `token.var('path')` fold during
   * extraction. Pass parallel JS maps: `values[path]` → raw value,
   * `vars[path]` → CSS-var form. Omit to disable.
   */
  tokenDictionary?: TokenDictionary
  /**
   * Resolved JSX factory names accepting member-chain tags
   * (`<styled.div>`). Config loaders should pass the default explicitly.
   */
  jsxFactories?: Array<string>
}

export declare function matchImports(scan: ImportScanResult, matchers: Matchers): Array<MatchedImport>

export interface ParsedFileView {
  path: string
  atoms: Array<Atom>
  diagnostics: Array<Diagnostic>
  recipes: Array<RecipeEntry>
  slotRecipes: Array<RecipeEntry>
}

/** Per-call telemetry from `parseFile`. Mirrors `pandacss_project::ParseFileReport`. */
export interface ParseFileReport {
  /** Source path parsed for this report. */
  path: string
  cssCalls: number
  cvaCalls: number
  svaCalls: number
  jsxUsages: number
  diagnostics: Array<Diagnostic>
}

/** Optional project-construction inputs. */
export interface ProjectOptions {
  /**
   * When `true` (default), construct a `CrossFileResolver` over the
   * native filesystem. Set to `false` to disable cross-file folding.
   */
  crossFile?: boolean
}

/** Aggregate counts across the project. Cheap; doesn't recompute anything. */
export interface ProjectSummary {
  filesProcessed: number
  atomCount: number
  recipeCount: number
  slotRecipeCount: number
}

/**
 * One `(file, span_start, value)` entry for the recipe and slot-recipe
 * iterators. `value` is the serialized recipe shape (matches
 * `pandacss_recipes::Recipe` / `SlotRecipe`).
 */
export interface RecipeEntry {
  file: string
  spanStart: number
  recipe: any
}

export interface ResolvedUtilityValue {
  utility: string
  className: string
  cssValue: any
  important: boolean
  source: any
}

export interface ResolveUtilityValueInput {
  prop: string
  value: any
}

export declare function scanImports(path: string, source: string): ImportScanResult

/**
 * Glob overrides for `scan`. Omitted fields fall back to the
 * config's `include`/`exclude`/`cwd`.
 */
export interface ScanOptions {
  include?: Array<string>
  exclude?: Array<string>
  cwd?: string
}

export declare function shutdownTracing(): boolean

/**
 * A source glob paired with its static base directory. `base` is the dir a watcher
 * subscribes to; `pattern` is the glob relative to `base`.
 */
export interface SourceEntry {
  base: string
  pattern: string
}

/** 1-indexed line, 1-indexed UTF-16 column (matches `tsc`/IDE output). */
export interface SourceLocation {
  line: number
  column: number
}

export interface SourceRange {
  start: SourceLocation
  end: SourceLocation
}

export interface Span {
  start: number
  end: number
}

/** One file in a `--splitting` output set. Host writes `path -> code`. */
export interface SplitCssFile {
  path: string
  code: string
}

export interface SplitCssResult {
  files: Array<SplitCssFile>
  diagnostics: Array<Diagnostic>
}

export declare function startTracing(options?: TraceOptions | undefined | null): boolean

export interface StaticPatternResult {
  atoms: Array<Atom>
  diagnostics: Array<Diagnostic>
}

/** Renders `timings.json`. Call before `shutdownTracing`, which consumes the same data. */
export declare function takeTimingsJson(): string | null

export interface TokenDictionary {
  values: Record<string, string>
  vars: Record<string, string>
}

export interface TraceOptions {
  filter?: string
  output?: string
  file?: string
}

export interface TransformSourceHelperFacts {
  needsCx: boolean
  needsCva: boolean
  needsSva: boolean
}

export interface TransformSourceInput {
  path: string
  source: string
  mode?: string
  helperCx?: string
  targetsCss?: boolean
  targetsPatterns?: boolean
  targetsRecipes?: boolean
  targetsTokens?: boolean
  targetsJsx?: boolean
}

export interface TransformSourceResult {
  code: string
  map?: string
  changed: boolean
  bailed: boolean
  diagnostics: Array<Diagnostic>
  dependencies: Array<string>
  helper: TransformSourceHelperFacts
}

export interface WriteArtifactsOptions {
  outdir: string
  cwd?: string
  forceImportExtension?: boolean
  artifacts?: Array<CodegenArtifact>
  overlay?: CodegenOverlay
}

export interface WriteCssOptions {
  outfile: string
  cwd?: string
  emitLayerDeclaration?: boolean
  minify?: boolean
  polyfill?: boolean
}

export interface WriteCssResult {
  path: string
  css: string
  sourceMap?: string
  manifest: CompileManifest
  layerRanges: CompileLayerRanges
  diagnostics: Array<Diagnostic>
}

export interface WriteLayerCssOptions {
  outfile: string
  layers: Array<string>
  cwd?: string
  emitLayerDeclaration?: boolean
  minify?: boolean
  polyfill?: boolean
}

export interface WriteSplitCssOptions {
  outdir?: string
  cwd?: string
  layers?: Array<string>
  emitLayerDeclaration?: boolean
  minify?: boolean
  polyfill?: boolean
}

export interface WriteSplitCssResult {
  root: string
  paths: Array<string>
  files: Array<SplitCssFile>
  diagnostics: Array<Diagnostic>
}
