/**
 * Vendor a terse `csstype.d.ts` for the Rust codegen crate (`pnpm vendor:csstype`).
 *
 * Fetches upstream `csstype`, keeps only what Panda's generated types consume —
 * the camelCase property interfaces + `Properties` aggregate, the `Property` /
 * `DataType` / `Globals` unions, and `Pseudos` — and drops the rest: all JSDoc
 * (~75% of the file), the `*Hyphen` / `*Fallback` families, `HtmlAttributes` /
 * `SvgAttributes`, the `AtRule` namespace, and the `PropertyValue` / `Fallback`
 * helpers. The committed result is embedded into the crate via `include_str!`.
 *
 * Also exports the `DataType` members: upstream leaves them bare (valid only as a
 * `.d.ts` under `skipLibCheck`); exporting makes the terse file a valid `.ts`.
 */
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))

// Pinned to match the csstype version Panda's v1 types use.
const CSSTYPE_VERSION = '3.2.3'
const SOURCE_URL = `https://unpkg.com/csstype@${CSSTYPE_VERSION}/index.d.ts`

const KEEP_EXACT = new Set([
  'StandardLonghandProperties',
  'StandardShorthandProperties',
  'StandardProperties',
  'VendorLonghandProperties',
  'VendorShorthandProperties',
  'VendorProperties',
  'ObsoleteProperties',
  'SvgProperties',
  'Properties',
  'Globals',
  'AdvancedPseudos',
  'SimplePseudos',
  'Pseudos',
])
const KEEP_NAMESPACE = new Set(['Property', 'DataType'])

interface Decl {
  kind: 'interface' | 'type' | 'namespace'
  name: string
  text: string
}

/** Split top-level declarations, tracking `<>`/`()` so a body `{` is found correctly. */
function splitDeclarations(src: string): Decl[] {
  const decls: Decl[] = []
  const n = src.length
  let i = 0

  while (i < n) {
    while (i < n && /\s/.test(src[i])) i++
    if (i >= n) break
    const start = i
    let angle = 0
    let paren = 0

    while (i < n) {
      const c = src[i]
      if (c === '<') angle++
      else if (c === '>') angle--
      else if (c === '(') paren++
      else if (c === ')') paren--
      else if (c === ';' && angle === 0 && paren === 0) {
        i++
        break
      } else if (c === '{' && angle === 0 && paren === 0) {
        let depth = 1
        i++
        while (i < n && depth > 0) {
          if (src[i] === '{') depth++
          else if (src[i] === '}') depth--
          i++
        }
        while (i < n && (src[i] === ' ' || src[i] === '\t' || src[i] === ';')) i++
        break
      }
      i++
    }

    const text = src.slice(start, i).trim()
    const match = /^(?:export\s+)?(?:declare\s+)?(interface|type|namespace)\s+([A-Za-z0-9_]+)/.exec(text)
    if (match) decls.push({ kind: match[1] as Decl['kind'], name: match[2], text })
  }

  return decls
}

/** Add `export` to bare `type` members so the namespace is valid outside a `.d.ts`. */
function exportNamespaceMembers(text: string): string {
  return text.replace(/^(\s+)type /gm, '$1export type ')
}

async function main() {
  const res = await fetch(SOURCE_URL)
  if (!res.ok) throw new Error(`Failed to fetch ${SOURCE_URL}: ${res.status} ${res.statusText}`)
  const raw = await res.text()

  // Strip JSDoc / block comments first — they are ~75% of the file.
  const stripped = raw.replace(/\/\*[\s\S]*?\*\//g, '')

  const kept = splitDeclarations(stripped)
    .filter(({ kind, name }) => {
      if (name.includes('Hyphen') || name.includes('Fallback')) return false
      return KEEP_EXACT.has(name) || (kind === 'namespace' && KEEP_NAMESPACE.has(name))
    })
    .map((decl) => (decl.name === 'DataType' ? { ...decl, text: exportNamespaceMembers(decl.text) } : decl))

  const header =
    `// GENERATED by crates/pandacss_codegen/scripts/vendor-csstype.ts — do not edit.\n` +
    `// Source: csstype@${CSSTYPE_VERSION} (${SOURCE_URL})\n` +
    `// Regenerate with: pnpm vendor:csstype\n`

  const body = kept.map((decl) => decl.text).join('\n\n')
  const cssProperties = 'export interface CssProperties extends Properties<(string & {}) | number, string & {}> {}'

  // Comments are gone, so the blank lines they left between members are pure
  // padding — collapse them all, then re-add a single blank line before each
  // top-level (non-indented) declaration for diff readability.
  const out = `${header}\n${body}\n\n${cssProperties}\n`.replace(/\n[ \t]*\n/g, '\n').replace(/\n(export )/g, '\n\n$1')

  const outPath = join(scriptDir, '..', 'assets', 'csstype.d.ts')
  writeFileSync(outPath, out, 'utf8')

  const kb = (out.length / 1024).toFixed(1)
  const pct = Math.round((out.length / raw.length) * 100)
  console.log(
    `[vendor:csstype] csstype@${CSSTYPE_VERSION}: ${raw.length} → ${out.length} bytes (${kb}KB, ${pct}% of source)`,
  )
  console.log(`[vendor:csstype] kept ${kept.length} declarations → ${outPath}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
