[package]
name = "pandacss_system"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
pandacss_config = { workspace = true }
pandacss_encoder = { workspace = true }
pandacss_extractor = { workspace = true }
pandacss_literal = { workspace = true }
pandacss_recipes = { workspace = true }
pandacss_shared = { workspace = true }
pandacss_tokens = { workspace = true }
pandacss_utility = { workspace = true }
regex = { workspace = true }
rustc-hash = { workspace = true }
serde_json = { workspace = true }
smallvec = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
