/* eslint-disable */
import type { ConditionalValue } from './conditions'
import type { PropertyValue } from './prop-type'
import type { Token } from '../tokens'

export type CssVarProperties = {
  [key in `--${string}`]?: ConditionalValue<Token | (string & {}) | (number & {})>
}

export type SystemProperties = {
  	all?: PropertyValue<'all'>
	animation?: PropertyValue<'animation'>
	appearance?: PropertyValue<'appearance'>
	azimuth?: PropertyValue<'azimuth'>
	background?: PropertyValue<'background'>
	border?: PropertyValue<'border'>
	bottom?: PropertyValue<'bottom'>
	caret?: PropertyValue<'caret'>
	clear?: PropertyValue<'clear'>
	clip?: PropertyValue<'clip'>
	color?: PropertyValue<'color'>
	columns?: PropertyValue<'columns'>
	contain?: PropertyValue<'contain'>
	container?: PropertyValue<'container'>
	content?: PropertyValue<'content'>
	cursor?: PropertyValue<'cursor'>
	direction?: PropertyValue<'direction'>
	display?: PropertyValue<'display'>
	filter?: PropertyValue<'filter'>
	flex?: PropertyValue<'flex'>
	float?: PropertyValue<'float'>
	font?: PropertyValue<'font'>
	gap?: PropertyValue<'gap'>
	grid?: PropertyValue<'grid'>
	height?: PropertyValue<'height'>
	hyphens?: PropertyValue<'hyphens'>
	inset?: PropertyValue<'inset'>
	isolation?: PropertyValue<'isolation'>
	left?: PropertyValue<'left'>
	margin?: PropertyValue<'margin'>
	mask?: PropertyValue<'mask'>
	maxBlockSize?: PropertyValue<'maxBlockSize'>
	maxHeight?: PropertyValue<'maxHeight'>
	maxInlineSize?: PropertyValue<'maxInlineSize'>
	maxLines?: PropertyValue<'maxLines'>
	maxWidth?: PropertyValue<'maxWidth'>
	minBlockSize?: PropertyValue<'minBlockSize'>
	minHeight?: PropertyValue<'minHeight'>
	minInlineSize?: PropertyValue<'minInlineSize'>
	minWidth?: PropertyValue<'minWidth'>
	offset?: PropertyValue<'offset'>
	opacity?: PropertyValue<'opacity'>
	order?: PropertyValue<'order'>
	orphans?: PropertyValue<'orphans'>
	outline?: PropertyValue<'outline'>
	overflow?: PropertyValue<'overflow'>
	padding?: PropertyValue<'padding'>
	page?: PropertyValue<'page'>
	pageBreakAfter?: PropertyValue<'pageBreakAfter'>
	pageBreakBefore?: PropertyValue<'pageBreakBefore'>
	pageBreakInside?: PropertyValue<'pageBreakInside'>
	perspective?: PropertyValue<'perspective'>
	position?: PropertyValue<'position'>
	quotes?: PropertyValue<'quotes'>
	resize?: PropertyValue<'resize'>
	right?: PropertyValue<'right'>
	rotate?: PropertyValue<'rotate'>
	scale?: PropertyValue<'scale'>
	top?: PropertyValue<'top'>
	transform?: PropertyValue<'transform'>
	transition?: PropertyValue<'transition'>
	translate?: PropertyValue<'translate'>
	visibility?: PropertyValue<'visibility'>
	widows?: PropertyValue<'widows'>
	width?: PropertyValue<'width'>
	willChange?: PropertyValue<'willChange'>
	zIndex?: PropertyValue<'zIndex'>
	zoom?: PropertyValue<'zoom'>
	pos?: PropertyValue<'pos'>
	insetEnd?: PropertyValue<'insetEnd'>
	end?: PropertyValue<'end'>
	insetStart?: PropertyValue<'insetStart'>
	start?: PropertyValue<'start'>
	flexDir?: PropertyValue<'flexDir'>
	p?: PropertyValue<'p'>
	pl?: PropertyValue<'pl'>
	pr?: PropertyValue<'pr'>
	pt?: PropertyValue<'pt'>
	pb?: PropertyValue<'pb'>
	py?: PropertyValue<'py'>
	paddingY?: PropertyValue<'paddingY'>
	paddingX?: PropertyValue<'paddingX'>
	px?: PropertyValue<'px'>
	pe?: PropertyValue<'pe'>
	paddingEnd?: PropertyValue<'paddingEnd'>
	ps?: PropertyValue<'ps'>
	paddingStart?: PropertyValue<'paddingStart'>
	ml?: PropertyValue<'ml'>
	mr?: PropertyValue<'mr'>
	mt?: PropertyValue<'mt'>
	mb?: PropertyValue<'mb'>
	m?: PropertyValue<'m'>
	my?: PropertyValue<'my'>
	marginY?: PropertyValue<'marginY'>
	mx?: PropertyValue<'mx'>
	marginX?: PropertyValue<'marginX'>
	me?: PropertyValue<'me'>
	marginEnd?: PropertyValue<'marginEnd'>
	ms?: PropertyValue<'ms'>
	marginStart?: PropertyValue<'marginStart'>
	ringWidth?: PropertyValue<'ringWidth'>
	ringColor?: PropertyValue<'ringColor'>
	ring?: PropertyValue<'ring'>
	ringOffset?: PropertyValue<'ringOffset'>
	w?: PropertyValue<'w'>
	minW?: PropertyValue<'minW'>
	maxW?: PropertyValue<'maxW'>
	h?: PropertyValue<'h'>
	minH?: PropertyValue<'minH'>
	maxH?: PropertyValue<'maxH'>
	bgPosition?: PropertyValue<'bgPosition'>
	bgPositionX?: PropertyValue<'bgPositionX'>
	bgPositionY?: PropertyValue<'bgPositionY'>
	bgAttachment?: PropertyValue<'bgAttachment'>
	bgClip?: PropertyValue<'bgClip'>
	bg?: PropertyValue<'bg'>
	bgColor?: PropertyValue<'bgColor'>
	bgOrigin?: PropertyValue<'bgOrigin'>
	bgImage?: PropertyValue<'bgImage'>
	bgRepeat?: PropertyValue<'bgRepeat'>
	bgBlendMode?: PropertyValue<'bgBlendMode'>
	bgSize?: PropertyValue<'bgSize'>
	bgGradient?: PropertyValue<'bgGradient'>
	rounded?: PropertyValue<'rounded'>
	roundedTopLeft?: PropertyValue<'roundedTopLeft'>
	roundedTopRight?: PropertyValue<'roundedTopRight'>
	roundedBottomRight?: PropertyValue<'roundedBottomRight'>
	roundedBottomLeft?: PropertyValue<'roundedBottomLeft'>
	roundedTop?: PropertyValue<'roundedTop'>
	roundedRight?: PropertyValue<'roundedRight'>
	roundedBottom?: PropertyValue<'roundedBottom'>
	roundedLeft?: PropertyValue<'roundedLeft'>
	roundedStartStart?: PropertyValue<'roundedStartStart'>
	roundedStartEnd?: PropertyValue<'roundedStartEnd'>
	roundedStart?: PropertyValue<'roundedStart'>
	roundedEndStart?: PropertyValue<'roundedEndStart'>
	roundedEndEnd?: PropertyValue<'roundedEndEnd'>
	roundedEnd?: PropertyValue<'roundedEnd'>
	borderX?: PropertyValue<'borderX'>
	borderXWidth?: PropertyValue<'borderXWidth'>
	borderXColor?: PropertyValue<'borderXColor'>
	borderY?: PropertyValue<'borderY'>
	borderYWidth?: PropertyValue<'borderYWidth'>
	borderYColor?: PropertyValue<'borderYColor'>
	borderStart?: PropertyValue<'borderStart'>
	borderStartWidth?: PropertyValue<'borderStartWidth'>
	borderStartColor?: PropertyValue<'borderStartColor'>
	borderEnd?: PropertyValue<'borderEnd'>
	borderEndWidth?: PropertyValue<'borderEndWidth'>
	borderEndColor?: PropertyValue<'borderEndColor'>
	shadow?: PropertyValue<'shadow'>
	shadowColor?: PropertyValue<'shadowColor'>
	x?: PropertyValue<'x'>
	y?: PropertyValue<'y'>
	aspectRatio?: PropertyValue<'aspectRatio'>
	boxDecorationBreak?: PropertyValue<'boxDecorationBreak'>
	boxSizing?: PropertyValue<'boxSizing'>
	objectPosition?: PropertyValue<'objectPosition'>
	objectFit?: PropertyValue<'objectFit'>
	overscrollBehavior?: PropertyValue<'overscrollBehavior'>
	overscrollBehaviorX?: PropertyValue<'overscrollBehaviorX'>
	overscrollBehaviorY?: PropertyValue<'overscrollBehaviorY'>
	insetInline?: PropertyValue<'insetInline'>
	insetBlock?: PropertyValue<'insetBlock'>
	insetBlockEnd?: PropertyValue<'insetBlockEnd'>
	insetBlockStart?: PropertyValue<'insetBlockStart'>
	insetInlineEnd?: PropertyValue<'insetInlineEnd'>
	insetInlineStart?: PropertyValue<'insetInlineStart'>
	insetX?: PropertyValue<'insetX'>
	insetY?: PropertyValue<'insetY'>
	hideFrom?: PropertyValue<'hideFrom'>
	hideBelow?: PropertyValue<'hideBelow'>
	flexBasis?: PropertyValue<'flexBasis'>
	flexDirection?: PropertyValue<'flexDirection'>
	flexGrow?: PropertyValue<'flexGrow'>
	flexShrink?: PropertyValue<'flexShrink'>
	gridTemplateColumns?: PropertyValue<'gridTemplateColumns'>
	gridTemplateRows?: PropertyValue<'gridTemplateRows'>
	gridColumn?: PropertyValue<'gridColumn'>
	gridRow?: PropertyValue<'gridRow'>
	gridColumnStart?: PropertyValue<'gridColumnStart'>
	gridColumnEnd?: PropertyValue<'gridColumnEnd'>
	gridAutoFlow?: PropertyValue<'gridAutoFlow'>
	gridAutoColumns?: PropertyValue<'gridAutoColumns'>
	gridAutoRows?: PropertyValue<'gridAutoRows'>
	gridGap?: PropertyValue<'gridGap'>
	gridRowGap?: PropertyValue<'gridRowGap'>
	gridColumnGap?: PropertyValue<'gridColumnGap'>
	rowGap?: PropertyValue<'rowGap'>
	columnGap?: PropertyValue<'columnGap'>
	justifyContent?: PropertyValue<'justifyContent'>
	alignContent?: PropertyValue<'alignContent'>
	alignItems?: PropertyValue<'alignItems'>
	alignSelf?: PropertyValue<'alignSelf'>
	paddingLeft?: PropertyValue<'paddingLeft'>
	paddingRight?: PropertyValue<'paddingRight'>
	paddingTop?: PropertyValue<'paddingTop'>
	paddingBottom?: PropertyValue<'paddingBottom'>
	paddingBlock?: PropertyValue<'paddingBlock'>
	paddingBlockEnd?: PropertyValue<'paddingBlockEnd'>
	paddingBlockStart?: PropertyValue<'paddingBlockStart'>
	paddingInline?: PropertyValue<'paddingInline'>
	paddingInlineEnd?: PropertyValue<'paddingInlineEnd'>
	paddingInlineStart?: PropertyValue<'paddingInlineStart'>
	marginLeft?: PropertyValue<'marginLeft'>
	marginRight?: PropertyValue<'marginRight'>
	marginTop?: PropertyValue<'marginTop'>
	marginBottom?: PropertyValue<'marginBottom'>
	marginBlock?: PropertyValue<'marginBlock'>
	marginBlockEnd?: PropertyValue<'marginBlockEnd'>
	marginBlockStart?: PropertyValue<'marginBlockStart'>
	marginInline?: PropertyValue<'marginInline'>
	marginInlineEnd?: PropertyValue<'marginInlineEnd'>
	marginInlineStart?: PropertyValue<'marginInlineStart'>
	outlineWidth?: PropertyValue<'outlineWidth'>
	outlineColor?: PropertyValue<'outlineColor'>
	outlineOffset?: PropertyValue<'outlineOffset'>
	divideX?: PropertyValue<'divideX'>
	divideY?: PropertyValue<'divideY'>
	divideColor?: PropertyValue<'divideColor'>
	divideStyle?: PropertyValue<'divideStyle'>
	inlineSize?: PropertyValue<'inlineSize'>
	blockSize?: PropertyValue<'blockSize'>
	fontFamily?: PropertyValue<'fontFamily'>
	fontSize?: PropertyValue<'fontSize'>
	fontWeight?: PropertyValue<'fontWeight'>
	fontSmoothing?: PropertyValue<'fontSmoothing'>
	fontVariantNumeric?: PropertyValue<'fontVariantNumeric'>
	letterSpacing?: PropertyValue<'letterSpacing'>
	lineHeight?: PropertyValue<'lineHeight'>
	textAlign?: PropertyValue<'textAlign'>
	textDecoration?: PropertyValue<'textDecoration'>
	textDecorationColor?: PropertyValue<'textDecorationColor'>
	textEmphasisColor?: PropertyValue<'textEmphasisColor'>
	textDecorationStyle?: PropertyValue<'textDecorationStyle'>
	textDecorationThickness?: PropertyValue<'textDecorationThickness'>
	textUnderlineOffset?: PropertyValue<'textUnderlineOffset'>
	textTransform?: PropertyValue<'textTransform'>
	textIndent?: PropertyValue<'textIndent'>
	textShadow?: PropertyValue<'textShadow'>
	textOverflow?: PropertyValue<'textOverflow'>
	verticalAlign?: PropertyValue<'verticalAlign'>
	wordBreak?: PropertyValue<'wordBreak'>
	textWrap?: PropertyValue<'textWrap'>
	truncate?: PropertyValue<'truncate'>
	lineClamp?: PropertyValue<'lineClamp'>
	listStyleType?: PropertyValue<'listStyleType'>
	listStylePosition?: PropertyValue<'listStylePosition'>
	listStyleImage?: PropertyValue<'listStyleImage'>
	backgroundPosition?: PropertyValue<'backgroundPosition'>
	backgroundPositionX?: PropertyValue<'backgroundPositionX'>
	backgroundPositionY?: PropertyValue<'backgroundPositionY'>
	backgroundAttachment?: PropertyValue<'backgroundAttachment'>
	backgroundClip?: PropertyValue<'backgroundClip'>
	backgroundColor?: PropertyValue<'backgroundColor'>
	backgroundOrigin?: PropertyValue<'backgroundOrigin'>
	backgroundImage?: PropertyValue<'backgroundImage'>
	backgroundRepeat?: PropertyValue<'backgroundRepeat'>
	backgroundBlendMode?: PropertyValue<'backgroundBlendMode'>
	backgroundSize?: PropertyValue<'backgroundSize'>
	backgroundGradient?: PropertyValue<'backgroundGradient'>
	textGradient?: PropertyValue<'textGradient'>
	gradientFrom?: PropertyValue<'gradientFrom'>
	gradientTo?: PropertyValue<'gradientTo'>
	gradientVia?: PropertyValue<'gradientVia'>
	borderRadius?: PropertyValue<'borderRadius'>
	borderTopLeftRadius?: PropertyValue<'borderTopLeftRadius'>
	borderTopRightRadius?: PropertyValue<'borderTopRightRadius'>
	borderBottomRightRadius?: PropertyValue<'borderBottomRightRadius'>
	borderBottomLeftRadius?: PropertyValue<'borderBottomLeftRadius'>
	borderTopRadius?: PropertyValue<'borderTopRadius'>
	borderRightRadius?: PropertyValue<'borderRightRadius'>
	borderBottomRadius?: PropertyValue<'borderBottomRadius'>
	borderLeftRadius?: PropertyValue<'borderLeftRadius'>
	borderStartStartRadius?: PropertyValue<'borderStartStartRadius'>
	borderStartEndRadius?: PropertyValue<'borderStartEndRadius'>
	borderStartRadius?: PropertyValue<'borderStartRadius'>
	borderEndStartRadius?: PropertyValue<'borderEndStartRadius'>
	borderEndEndRadius?: PropertyValue<'borderEndEndRadius'>
	borderEndRadius?: PropertyValue<'borderEndRadius'>
	borderColor?: PropertyValue<'borderColor'>
	borderInline?: PropertyValue<'borderInline'>
	borderInlineWidth?: PropertyValue<'borderInlineWidth'>
	borderInlineColor?: PropertyValue<'borderInlineColor'>
	borderBlock?: PropertyValue<'borderBlock'>
	borderBlockWidth?: PropertyValue<'borderBlockWidth'>
	borderBlockColor?: PropertyValue<'borderBlockColor'>
	borderLeft?: PropertyValue<'borderLeft'>
	borderLeftColor?: PropertyValue<'borderLeftColor'>
	borderInlineStart?: PropertyValue<'borderInlineStart'>
	borderInlineStartWidth?: PropertyValue<'borderInlineStartWidth'>
	borderInlineStartColor?: PropertyValue<'borderInlineStartColor'>
	borderRight?: PropertyValue<'borderRight'>
	borderRightColor?: PropertyValue<'borderRightColor'>
	borderInlineEnd?: PropertyValue<'borderInlineEnd'>
	borderInlineEndWidth?: PropertyValue<'borderInlineEndWidth'>
	borderInlineEndColor?: PropertyValue<'borderInlineEndColor'>
	borderTop?: PropertyValue<'borderTop'>
	borderTopColor?: PropertyValue<'borderTopColor'>
	borderBottom?: PropertyValue<'borderBottom'>
	borderBottomColor?: PropertyValue<'borderBottomColor'>
	borderBlockEnd?: PropertyValue<'borderBlockEnd'>
	borderBlockEndColor?: PropertyValue<'borderBlockEndColor'>
	borderBlockStart?: PropertyValue<'borderBlockStart'>
	borderBlockStartColor?: PropertyValue<'borderBlockStartColor'>
	boxShadow?: PropertyValue<'boxShadow'>
	boxShadowColor?: PropertyValue<'boxShadowColor'>
	mixBlendMode?: PropertyValue<'mixBlendMode'>
	brightness?: PropertyValue<'brightness'>
	contrast?: PropertyValue<'contrast'>
	grayscale?: PropertyValue<'grayscale'>
	hueRotate?: PropertyValue<'hueRotate'>
	invert?: PropertyValue<'invert'>
	saturate?: PropertyValue<'saturate'>
	sepia?: PropertyValue<'sepia'>
	dropShadow?: PropertyValue<'dropShadow'>
	blur?: PropertyValue<'blur'>
	backdropFilter?: PropertyValue<'backdropFilter'>
	backdropBlur?: PropertyValue<'backdropBlur'>
	backdropBrightness?: PropertyValue<'backdropBrightness'>
	backdropContrast?: PropertyValue<'backdropContrast'>
	backdropGrayscale?: PropertyValue<'backdropGrayscale'>
	backdropHueRotate?: PropertyValue<'backdropHueRotate'>
	backdropInvert?: PropertyValue<'backdropInvert'>
	backdropOpacity?: PropertyValue<'backdropOpacity'>
	backdropSaturate?: PropertyValue<'backdropSaturate'>
	backdropSepia?: PropertyValue<'backdropSepia'>
	borderCollapse?: PropertyValue<'borderCollapse'>
	borderSpacing?: PropertyValue<'borderSpacing'>
	borderSpacingX?: PropertyValue<'borderSpacingX'>
	borderSpacingY?: PropertyValue<'borderSpacingY'>
	tableLayout?: PropertyValue<'tableLayout'>
	transitionTimingFunction?: PropertyValue<'transitionTimingFunction'>
	transitionDelay?: PropertyValue<'transitionDelay'>
	transitionDuration?: PropertyValue<'transitionDuration'>
	transitionProperty?: PropertyValue<'transitionProperty'>
	animationDelay?: PropertyValue<'animationDelay'>
	transformOrigin?: PropertyValue<'transformOrigin'>
	scaleX?: PropertyValue<'scaleX'>
	scaleY?: PropertyValue<'scaleY'>
	translateX?: PropertyValue<'translateX'>
	translateY?: PropertyValue<'translateY'>
	accentColor?: PropertyValue<'accentColor'>
	caretColor?: PropertyValue<'caretColor'>
	scrollBehavior?: PropertyValue<'scrollBehavior'>
	scrollbar?: PropertyValue<'scrollbar'>
	scrollMargin?: PropertyValue<'scrollMargin'>
	scrollMarginX?: PropertyValue<'scrollMarginX'>
	scrollMarginY?: PropertyValue<'scrollMarginY'>
	scrollMarginLeft?: PropertyValue<'scrollMarginLeft'>
	scrollMarginRight?: PropertyValue<'scrollMarginRight'>
	scrollMarginTop?: PropertyValue<'scrollMarginTop'>
	scrollMarginBottom?: PropertyValue<'scrollMarginBottom'>
	scrollMarginBlock?: PropertyValue<'scrollMarginBlock'>
	scrollMarginBlockEnd?: PropertyValue<'scrollMarginBlockEnd'>
	scrollMarginBlockStart?: PropertyValue<'scrollMarginBlockStart'>
	scrollMarginInline?: PropertyValue<'scrollMarginInline'>
	scrollMarginInlineEnd?: PropertyValue<'scrollMarginInlineEnd'>
	scrollMarginInlineStart?: PropertyValue<'scrollMarginInlineStart'>
	scrollPadding?: PropertyValue<'scrollPadding'>
	scrollPaddingBlock?: PropertyValue<'scrollPaddingBlock'>
	scrollPaddingBlockStart?: PropertyValue<'scrollPaddingBlockStart'>
	scrollPaddingBlockEnd?: PropertyValue<'scrollPaddingBlockEnd'>
	scrollPaddingInline?: PropertyValue<'scrollPaddingInline'>
	scrollPaddingInlineEnd?: PropertyValue<'scrollPaddingInlineEnd'>
	scrollPaddingInlineStart?: PropertyValue<'scrollPaddingInlineStart'>
	scrollPaddingX?: PropertyValue<'scrollPaddingX'>
	scrollPaddingY?: PropertyValue<'scrollPaddingY'>
	scrollPaddingLeft?: PropertyValue<'scrollPaddingLeft'>
	scrollPaddingRight?: PropertyValue<'scrollPaddingRight'>
	scrollPaddingTop?: PropertyValue<'scrollPaddingTop'>
	scrollPaddingBottom?: PropertyValue<'scrollPaddingBottom'>
	scrollSnapAlign?: PropertyValue<'scrollSnapAlign'>
	scrollSnapStop?: PropertyValue<'scrollSnapStop'>
	scrollSnapType?: PropertyValue<'scrollSnapType'>
	scrollSnapStrictness?: PropertyValue<'scrollSnapStrictness'>
	scrollSnapMargin?: PropertyValue<'scrollSnapMargin'>
	scrollSnapMarginTop?: PropertyValue<'scrollSnapMarginTop'>
	scrollSnapMarginBottom?: PropertyValue<'scrollSnapMarginBottom'>
	scrollSnapMarginLeft?: PropertyValue<'scrollSnapMarginLeft'>
	scrollSnapMarginRight?: PropertyValue<'scrollSnapMarginRight'>
	touchAction?: PropertyValue<'touchAction'>
	userSelect?: PropertyValue<'userSelect'>
	fill?: PropertyValue<'fill'>
	stroke?: PropertyValue<'stroke'>
	srOnly?: PropertyValue<'srOnly'>
	debug?: PropertyValue<'debug'>
	backfaceVisibility?: PropertyValue<'backfaceVisibility'>
	clipPath?: PropertyValue<'clipPath'>
	maskImage?: PropertyValue<'maskImage'>
	maskSize?: PropertyValue<'maskSize'>
	textSizeAdjust?: PropertyValue<'textSizeAdjust'>
	colorPalette?: PropertyValue<'colorPalette'>
	textStyle?: PropertyValue<'textStyle'>
}