[package]
name = "pandacss_sfc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dev-dependencies]
serde_json = { workspace = true }
oxc_ast = { workspace = true }
oxc_ast_visit = { workspace = true }
indoc = { workspace = true }
insta = { workspace = true }
oxc_allocator = { workspace = true }
oxc_parser = { workspace = true }
oxc_span = { workspace = true }

[lints]
workspace = true
