name: Publish Extension

on:
  workflow_dispatch:

  push:
    paths:
      - 'extension/**'
    branches:
      - main

jobs:
  create_timestamp:
    runs-on: ubuntu-latest

    outputs:
      timestamp: ${{ steps.set_timestamp.outputs.timestamp }}

    steps:
      - name: Set Timestamp
        id: set_timestamp
        run: |
          echo "::set-output name=timestamp::$(date +'%s' | cut -c1-8)"
  release:
    name: VSCode Marketplace
    needs: create_timestamp
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: win32-x64
            npm_config_arch: x64
          - os: windows-latest
            target: win32-ia32
            npm_config_arch: ia32
          - os: windows-latest
            target: win32-arm64
            npm_config_arch: arm
          - os: ubuntu-latest
            target: linux-x64
            npm_config_arch: x64
          - os: ubuntu-latest
            target: linux-arm64
            npm_config_arch: arm64
          - os: ubuntu-latest
            target: linux-armhf
            npm_config_arch: arm
          - os: ubuntu-latest
            target: alpine-x64
            npm_config_arch: x64
          - os: macos-latest
            target: darwin-x64
            npm_config_arch: x64
          - os: macos-latest
            target: darwin-arm64
            npm_config_arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

      - name: Set Environment Variable
        run: echo "VSCE_RELEASE_VERSION=$(date +'%s' | cut -c1-8)" >> $GITHUB_ENV

      - name: Prepare npm install
        working-directory: ./extension/vscode
        run: pnpm rewrite-deps && pnpm clean

      - name: Overrides esbuild
        working-directory: ./extension/vscode
        if: contains(matrix.target, 'darwin-arm64')
        run: pnpm override-esbuild

      - name: Install with npm
        working-directory: ./extension/vscode
        run: |
          npm i --ignore-scripts
        env:
          npm_config_arch: ${{ matrix.npm_config_arch }}

      - name: Publish RC
        working-directory: ./extension/vscode
        run: |
          pnpm release
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
          VSCE_RELEASE_VERSION: ${{ needs.create_timestamp.outputs.timestamp }}
          VSCE_RELEASE_TYPE: rc
          VSCE_TARGET: ${{ matrix.target }}
