name: Publish Extension

on:
  workflow_dispatch:

  push:
    paths:
      - ".changeset/**"
      - "extension/**"
    branches:
      - main
      - ci/extension-multiplatform

jobs:
  release:
    name: VSCode Marketplace
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            target: win32-x64
            npm_config_arch: x64
          - os: windows-latest
            target: win32-ia32
            npm_config_arch: ia32
          - os: windows-latest
            target: win32-arm64
            npm_config_arch: arm
          - os: ubuntu-latest
            target: linux-x64
            npm_config_arch: x64
          - os: ubuntu-latest
            target: linux-arm64
            npm_config_arch: arm64
          - os: ubuntu-latest
            target: linux-armhf
            npm_config_arch: arm
          - os: ubuntu-latest
            target: alpine-x64
            npm_config_arch: x64
          # - os: macos-latest
          #   target: darwin-arm64
          #   npm_config_arch: x64
          - os: macos-latest
            target: darwin-arm64
            npm_config_arch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build packages
        run: pnpm build

      - name: Publish RC
        working-directory: ./extension/vscode
        run: |
          pnpm rewrite-deps
          pnpm clean
          npm i
          pnpm release
        env:
          VSCE_TOKEN: ${{secrets.VSCE_TOKEN}}
          VSCE_RELEASE_TYPE: rc
          VSCE_TARGET: ${{ matrix.target }}
